### ISSUE TITLE
[0.2.4] Problème d'URL / Route ?

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#100]
Bonjour,

A nouveau un soucis depuis la MAJ GeoNature 2.7.2/Monitoring 0.2.4:

Pour chaque niveau du sous-module, l'URL présente une erreur avec les caractères `%2F`:
![image](https://user-images.githubusercontent.com/66769358/125286030-99452600-e31b-11eb-8237-511a3e79ad61.png)

Sauriez-vous d'où peut venir le problème ?
Merci d'avance,
Maxime

**Comment by joelclems** [comment]
Corrigé et présent dans la version 0.2.5

**Comment by camillemonchicourt** [comment]
La 0.2.5 n'est compatible qu'avec GN 2.7 et plus ou rien à voir ?

**Comment by joelclems** [comment]
Oui ça reste compatible, je pense que  c'était un effet de bord d'un changement dans la 2.7 su l'url des module ??
