### ISSUE TITLE
[0.2.5] Images sous-modules non-trouvées

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#102]
On va dire que je m'acharne :)

En passant en 0.2.5, **les images des sous-modules ne sont plus trouvés...** Par contre je ne comprends pas d'où ça vient, les liens symboliques ramènent pourtant au bon endroit...

![image](https://user-images.githubusercontent.com/66769358/125411132-eaa5f180-e3bd-11eb-9eca-39300ea39706.png)

![image](https://user-images.githubusercontent.com/66769358/125411294-dfe50d1c-7ff4-4dec-92f7-bf2198289e9e.png)

![image](https://user-images.githubusercontent.com/66769358/125411584-577931c0-605c-48a8-91cc-e6fec4a6c58c.png)

**Comment by joelclems** [comment]
Dans un monde ideal il faudrait que ces images soient dans le dossier static du backend
de la sorte on aurait plus à rebuilder le frontend à l'installation d'un sous module

Je me penche sur le pb

est ce qu'il y a des espaces dans les noms des images?

**Comment by joelclems** [comment]
66f815ee0d358e4288e205471a2f7c3138231c49

J'ai fait en sorte de mettre les assets dans le dossier `backend/static/monitorings/assets/` de geonature, ce qui permet de ne plus avoir à rebuilder le frontend
- quand on installe un module
- quand on change l'image

la mise à jour pour tous les modules se fait grace à la commande

```
flask monitorings process_img
``` 

@maximetoma est ce que tu peux tester sur develop ?

**Comment by maximetoma** [comment]
- Lors de l'exécution de `flask monitorings process_img`:
![image](https://user-images.githubusercontent.com/66769358/125435705-af5add75-7c39-4201-8f9c-46047583769b.png)

- Lors de la compilation :
![image](https://user-images.githubusercontent.com/66769358/125435790-58830487-538d-40a8-a03e-3c63d4545477.png)

- Fichier de log:
[2021-07-13T10_16_29_631Z-debug.log](https://github.com/PnX-SI/gn_module_monitoring/files/6808098/2021-07-13T10_16_29_631Z-debug.log)

**Comment by joelclems** [comment]
C'est corrigé pour le frontend, il faudra gérer les warning du backend mais ça ne devriat pas poser de soucis sur ce sujet

**Comment by maximetoma** [comment]
Okay je confirme que ça marche bien !
Et la modification d'image se fait bien également

**Comment by camillemonchicourt** [comment]
Je ré-ouvre en attendant que cela soit intégré dans une release.
A voir si cela implique des conséquences ou des choses à faire lors de la prochaine mise à jour ?

**Comment by joelclems** [comment]
J'ai renseigné les maj et les changelog dans 66f815ee0d358e4288e205471a2f7c3138231c49

**Comment by joelclems** [comment]
La conséquence c'est de jouer la commande 

```
flask monitorings process_img
```

pour pouvoir avoir les images
