### ISSUE TITLE
Observateurs en texte libre

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/gn_module_monitoring#106]
Bonjour,

Comment faire pour permettre l'ajout des observateurs en texte libre, plutôt qu'avec la liste des utilisateurs de UsersHub ?
J'ai essayé de supprimer "observers" et de rajouter un champ text "observateurs", mais "observers" semble obligatoire ?

Merci pour votre retour !

**Comment by camillemonchicourt** [comment]
Tu parles dans Occtax ? Au niveau de la saisie ?
C'est un paramètre dans la conf du module Occtax.
Il ne faut surtout pas modifier la BDD des schémas de GeoNature.
On peut d'ajouter les schémas et tables que l'on veut pas pas modifier ceux existant utilisés par l'application

**Comment by camillemonchicourt** [comment]
Ah j'y étais pas, c'est dans Monitoring...
Idem il ne faut pas modifier les champs existants.

Pas certain que cela soit possible dans Monitoring comme ça l'est dans Occtax.

**Comment by RNF-SI** [comment]
Oui c'est bien dans monitorings, pour importer mes données historiques qui ressemblent plus à "personnel de telle structure" qu'à "nom prenom" donc je peux pas les ajouter à UsersHub... 
Je peux pas simplement désactiver le champs observers dans un module monitoring ? 
Sinon pour les données anciennes je rajoute un champs dans le json, et pour les nouvelles données saisies ça sera à partir de UsersHub.

**Comment by RNF-SI** [comment]
Ah finalement j'avais du mal rebuild le front.  Finalement en rajoutant dans les attributs spécifiques un attribut qui porte le nom observers ça remplace bien le champs des observers classique : 
```
"specific": {
    "observers": {
      "type_widget": "text",
      "attribut_label": "Observateurs",
      "required": true
    },
```

**Comment by RNF-SI** [comment]
mais pour l'appel des données par contre ça marche pas. 
J'ai donc caché et rendu optionnel le champ observers et créé un champs texte observateurs : 
```
  "specific": {
    "observers": {
      "hidden": true,
      "required": false
    },
    "obsv_histo": {
      "type_widget": "text",
      "attribut_label": "Observateurs",
      "required": true
    },
```

**Comment by camillemonchicourt** [comment]
OK, si tes données alimentent la Synthèse, il faudra bien remplacer l'alimentation de la table de correspondance cor_role_synthese par directement le champs observers_txt dans la table Synthèse.

**Comment by amandine-sahl** [comment]
Je peux fermer le tiquet?

**Comment by camillemonchicourt** [comment]
Je ne suis pas certain que cela doit être configuré sous-module par sous-module avec uniquement le fait de cacher/masquer un champs ou l'autre.
Il était plutôt prévu que ce soit un paramètre global du module, comme dans Occtax.

Il me semble que c'est global à une instance d'avoir les observateurs gérés dans des listes, ou alors de ne pas les maîtriser et donc préférer un champs texte.
Par ailleurs, la manière de gérer/stocker les observateurs a des conséquences sur l'alimentation automatique de la Synthèse depuis Monitoring - https://github.com/PnX-SI/gn_module_monitoring/blob/main/data/synthese_svo.sql#L66-L75

**Comment by andriacap** [comment]
Tous les sous modules ont en commun le fait de pouvoir mettre "observers_txt" ou observers en list ?  Il n'y a aucun sous modules qui préféraient avoir des particularités de choix d'observateur présent dans GN plutot que renseigner des observteurs en txt ? Je trouve que c'est hyper contraignant de le mettre au niveau globale de la config MONITORINGS .. 

Surtout que la solution proposée met en place par défaut l'observteur liste et donc ne demande aucune configuration en plus . Si pour la majorité des sous modules installés sur une instance GN  on préfère renseigner des observateurs extérieurs  et donc en champ libre alors on  change le choix par défaut à l'installation de MONITORINGS.

Comme si on configurait un paramètre dans MONITORING à l'exception près que si on préfère proposé une liste d'observareurs de GN ne serait ce que pour un sous module alors c'est possible dans ce que je propose mais pas dans le cas où la config est globle à MONITORINGS

**Comment by camillemonchicourt** [comment]
OK, en effet ça reste un plus de pouvoir configurer ça au niveau de chaque sous-module. 
Je craignais que cela soit moins structurant et plus complexe pour l'envoi des données automatique vers la Synthèse, mais comme la vue SQL alimentant la Synthèse depuis un sous-module est surcouchable/adaptable cela devrait pas être un soucis.

OK aussi pour @amandine-sahl pour gérer ça dans la configuration de chaque sous-module.

**Comment by andriacap** [comment]
Ok, merci pour ton retour Camille

**Comment by camillemonchicourt** [comment]
Ajout d'un champs "observers_txt", masqué par défaut. Voir doc sur le sujet : https://github.com/PnX-SI/gn_module_monitoring/pull/238/commits/2e1096d5a0ea9940a5693b57550003a1633463c3

**Comment by camillemonchicourt** [comment]
Intégré dans la 1.0.0
