### ISSUE TITLE
Sous-module : problème sur la saisie de dates

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_module_monitoring#107]
Bonjour,
j'ai défini dans le sous-module une saisie de date spécifique.
"dateDeb": {
	  "type_widget": "date",
      "attribut_label": "Date début observation",
      "required": true
	},
	"dateFin": {
	  "type_widget": "date",
      "attribut_label": "Date fin observation",
      "required": true
	},
La saisie semble fonctionner avec un widget de saisie de date.
Le problème c'est que quand on saisie une date on enregistre en base date - 1.
si je saisie une date 10/06/2021 il enregistre 09/06/2021.

![SaisieDate](https://user-images.githubusercontent.com/68022220/127996475-feab7edd-b61a-4bc0-8ae7-b6a236cdc757.png)
![ObservationEnregistree](https://user-images.githubusercontent.com/68022220/127996515-12e5e73c-80b9-4987-b283-4983fb881a31.png)

Cela ressemble fortement à 1 problème déjà rencontré avec la saisie des widget dates dans les applications angular et qui tient compte du décalage horaire mais qui n'est pas nécessairement le même en base.

Il y a donc un problème, surtout que si on ne fait pas attention, à la modification de l'observation, on enregistre des dates - 1 systématiquement.

j'ai donc demandé à mes utilisateurs de saisir date + 1 mais est-il possible de corriger ce problème ?

D'avance merci
Christian Bièche
Cistude Nature

**Comment by christianbieche** [comment]
Bonjour,
En complément de ce que je viens d'écrire, je viens de tester sous le navigateur firefox et là la saisie des dates est correcte.
Contrairement à ce que je pensais le problème vient donc du navigateur et du widget utilisé.
Christian

**Comment by christianbieche** [comment]
bonjour,
Un avis sur ce problème ?

**Comment by joelclems** [comment]
Cela ne marche pas sur chrome ?

**Comment by christianbieche** [comment]
non c'est bien ce que j'ai découvert. Oui j'avais oublié de préciser.

**Comment by christianbieche** [comment]
mais cela fonctionne correctement sous firefox.

**Comment by joelclems** [comment]
j'essaye de regarder ça cette semaine ou celle qui vient

**Comment by joelclems** [comment]
je n'ai pas réusii à reproduire l'erreur sous chrome
christian peux tu me dire si la date saisie est bonne en base de donnée auquel cas il s'agit d'un soucis d'affichage

**Comment by christianbieche** [comment]
bonjour,
oui comme je l'ai écrit. La date est correcte en base mais avec un jour de moins.
Quand on saisie une donnée et que l'on valide, l'observation est réaffichée et on voit bien ce qui a été saisie en base, mais j'ai vérifié.
Ce n'est pas un problème d'affichage uniquement la date est enregistrée comme cela en base.
De plus ce sont les utilisateurs qui m'ont signalé le problème, je n'utilise ni la même machine, ni le même chrome et j'ai reproduit donc il y a bien un problème.
Par contre, étrange que personne d'autre n'est eu le problème. L'air de la Gironde peut être ....
Avec firefox cela fonctionne donc pas d'urgence si tu ne vois pas d'où vient le problème.
Peut être le problème sera résolu quand je changerais de version.

autre info, dans mes modules actuels, on avait corrigé gn_module_monitoring\backend\routes\decorators.py sinon cela fonctionnait pas en commentant la ligne 51 #append_to_select=append,
Est ce que cela peut expliquer le comportement différent ? 

Christian

**Comment by joelclems** [comment]
ça ne doit pas venir de la modification du décorateur


pour la meme observation, il s'affiche les mêmes chose entre chrome et firefox ?

**Comment by christianbieche** [comment]
Non justement, c'est ce que je dis.
en base on a bien : une date qui est date debut date fin 2021-7-21	2021-7-21
L'affichage est correct sous firefox et pas sous chrome 
![ComparaisonChromeFireFox](https://user-images.githubusercontent.com/68022220/132510606-d19ccdf1-c5f3-45a9-ad8d-988cacd8f4c3.gif)

**Comment by joelclems** [comment]
c'est donc à priori l'affichage de la date qui n'est pas bon et la saisie qui ne poserait pas de problème

**Comment by christianbieche** [comment]
Je viens de vérifier en version 0.2.6 le problème est toujours là. Les dates ne sont pas correctes sous chrome par contre cela fonctionne sous firefox.
Qu'elle version de chrome est utilisé pour les tests ? La mienne est la version 
Version 94.0.4606.71 (Build officiel) (64 bits)
A priori c'est la dernière.

**Comment by joelclems** [comment]
J'ai la même version Version 94.0.4606.71 (Build officiel) snap (64 bits), peut être une histoire d'heure locale ??
Pouvez vous essayer le path présent dans le commit 0d3fe52c83d0acd7b02c9de4f771547e0fc0446b
