### ISSUE TITLE
sous-module : affichage de la date d'observation

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_module_monitoring#108]
Quand on a réaffiche une observation saisie. Le titre de l'observation affiche la date 01/01/1970.
j'ai testé en prod et sur mon serveur de test et cette date est toujours la même quelque soit les observations affichées.

D'où vient cette date ?? 
si l'on regarde la table  t_observations il n'y a pas de date alors qu'une date existe pour les visites.
Dans l'idéal, il faudrait dans mon cas pouvoir alimenter cette date avec la date spécifique que l'on saisie dans les observations
ou alors supprimer l'affiche de cette date qui perturbe mes utilisateurs.

Exemple :
 
![DateObservation](https://user-images.githubusercontent.com/68022220/127998341-fc902940-59ec-4e22-9ac2-85406b481fa7.png)

christian Bièche
Cistude nature

**Comment by christianbieche** [comment]
bonjour, 
Peut être est ce corrigé dans les autres versions ?  oui ? non ?

**Comment by maximetoma** [comment]
@christianbieche salut oui il me semble, je ne sais plus depuis quelle version mais dans la dernière, c'est corrigé

**Comment by christianbieche** [comment]
Parfait.

**Comment by christianbieche** [comment]
Ok c'est bien corrigé en version 0.2.6 on affiche l'id de l'observation à la place de la date
