### ISSUE TITLE
Affichage des champs obligatoires / Clarification

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#11]
Actuellement les champs obligatoires sont marqués par un trait rouge au début du champs, comme dans les autres modules de GeoNature. 

Mais il y a aussi un grand trait rouge en plus affiché sur tout le module, qui rend difficile l'identification des champs obligatoires ou non, ajoute de la confusion et n'est pas utile selon moi : 
![image](https://user-images.githubusercontent.com/4418840/78714179-b4a4d280-791b-11ea-8d69-24b53b270e28.png)

Je garderai plutôt le fonctionnement de base, comme ailleurs dans GeoNature, où uniquement les chamsp obligatoires sont marqués en rouge, et le bouton ENREGISTRER n'est pas actif tant qu'ils ne sont pas renseignés.

**Comment by joelclems** [comment]
dans 6978682
