### ISSUE TITLE
Problème à l'installation de la version 0.6.2 : solutions et questions

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_module_monitoring#115]
04/10/2021 : Erreur à l'install
Bonjour, suite à l'installation de la version 0.2.6 de monitorings, j'ai noté quelques erreurs dans la doc d'install.

1) Au lancement de l'installation,script : migration.sh, j'obtients le message d'erreur suivant :

	ERROR in e2e/app.po.ts(1,38): error TS2307: Cannot find module 'protractor'.

	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! geonature@0.0.0 build: `. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the geonature@0.0.0 build script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/geonatureadmin/.npm/_logs/2021-10-04T12_53_52_253Z-debug.log

Visiblement, protractor qui ne sert qu'aux tests n'est pas au bon endroit.
Il faut taper la commande suivante pour le mettre en local et que cela fonctionne :

npm install --save protractor

2) Rapatriez le fichier de configuration du module
	cp /home/`whoami`/gn_module_monitoring_old/config/conf_gn_module.toml  /home/`whoami`/gn_module_monitoring/config/conf_gn_module.toml
    ==> ce fichier est vide

Dans mon installation ce fichier est toujours vide. A quoi sert-il ?

3) Récupérez les sous-modules, recréer les liens symboliques pour la config
	cp -r /home/`whoami`/gn_module_monitoring_old/contrib/*  /home/`whoami`/gn_module_monitoring/contrib
	ln -s /home/`whoami`/gn_module_monitoring/contrib/* /home/`whoami`/gn_module_monitoring/config/monitoring/.
	
	Je ne comprends pas cette action. Je n'ai pas les modules dans contrib du coup mes modules pour Cistude n'apparaissent pas.
	
	Mon  module Lepidoptes est dans /home/geonatureadmin/  il faut donc faire :
ln -s  /home/geonatureadmin/mod_lepidopteres sentinelle_lepidopteres

et cela fonctionne.

je pense qu'une modification de la doc d'install est souhaitable.

4) Recréez les liens des images des modules dans le dossier backend/static/monitorings/assets
il est indiqué :
	cd /home/`whoami`/geonature/backend
	   source venv/bin/activate
	   export FLASK_APP=/home/`whoami`/geonature/backend/geonature/app.py
	   flask monitorings process_img                                      
	   
	   ==> la commande monitorings l'existe pas et le répertoire backend/static/monitorings non plus !!

A priori dixit les informations sur github les images seraient là : 
		cd /home/`whoami`/geonature/backend/static/external_assets/monitorings/assets

Ce n'est pas correct

après debug sous explorateur les images sont attendues sous :
/home/geonatureadmin/geonature/backend/static/external_assets/monitorings

	De plus avec le nom correspondant au module dans mon cas :

	   /home/geonatureadmin/geonature/backend/static/external_assets/monitorings/sentinelle_lepidopteres.jpg
	   /home/geonatureadmin/geonature/backend/static/external_assets/monitorings/sentinelle_odonates.jpg
	   
c'est une bonne chose mais il faudrait modifier la doc d'install

Christian Bièche
Cistude Nature

**Comment by joelclems** [comment]
Bonjour Christian

quelle est votre version de geonature ?

1) il faut que je regarde en detail, il est désormais dans le package.json de GeoNature depuis 5 mois depuis la release 2.7.0 je crois, je n'ai pas retrouvé ce soucis en faisait des installations *fraiches* recemment

2) c'est un fichier pour la configuration classique du module dont on ne se sert pas mais dont la présence est nécessaire  (la gestion de la configuration est différente pour le module monitoring). Il n'est pas commité (comme pour tous les modules) on pourrais l'enlever de .gitignore et ne plus s'en soucier

3)  4) oui il faudrait rafraichir la doc d'install, pour les dernieres version de geonature la commande deviens 
geonature monitorings process_img et on a plus qu'à activer le venv pour avior accès à la commande

**Comment by joelclems** [comment]
dans cette nouvelle version plus besoin de rebuild le frontend à l'installation d'un module (les images étant dans le dossier static de geonature)

**Comment by christianbieche** [comment]
Ma version de GEONATURE est la 2.6.2 (celle qui correspond aux dépendances de monitorings)
Pour le point 3) on est d'accord que ce que je fais est correct (de toute façon je constate que cela fonctionne comme cela et pas autrement).
