### ISSUE TITLE
Pouvoir entrer par sites

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#117]
Sur la page d'accueil du module, on liste actuellement les différents protocoles (sous-modules) existants et auquel l'utilisateur a les droits d'accéder.
Une fois dans un protocole, on liste les sites qui lui sont associés.

Il est souhaité de pouvoir accéder directement à la liste de tous les sites depuis la page d'accueil, tous protocoles confondus.
En effet la BDD prévoit actuellement qu'un site puisse être utilisé dans différents protocoles, mais le module actuel ne le permet pas.

Pour cela on ajoute un bouton "Liste des sites" sur la page d'accueil. 
Ce fonctionnement est paramétrable : 
- Soit je n'affiche que le bouton d'accès à la liste des sites
- Soit je n'affiche que les protocoles
- Soit les 2

Quand je clique sur le bouton LISTE DES SITES, j'accède à la page Carte-Liste avec tous les sites affichés selon les droits dont je dispose.
Dans la liste des sites, j'affiche leur nom, leur type, leur nombre de visites et la dernière visite.

Si j'ai défini des groupes de site, j'arrive sur la Carte-Liste des groupes de sites, et non pas sur celle des sites.
Pour cela, il est souhaité d'ajouter une géométrie aux groupes de sites (dessinée ou agrégation dynamique des géométries des sites le composant).

A voir si on peut conserver un double affichage sur la même page en onglet où l'on peut passer des groupes de sites aux sites comme actuellement : 

![Capture d’écran de 2021-10-07 15-20-09](https://user-images.githubusercontent.com/4418840/136392742-115a5491-0397-4b95-a3a2-ffbb3c77db98.png)

Si j'ai des groupes de sites, quand je clique sur l'un deux, j'accède à sa fiche détail. Celle-ci affiche les infos générales sur le groupe de sites, ainsi que la liste des sites qui le composent. La carte affiche l'éventuelle géométrie du groupe de site + les géométries des sites qui le composent.

Si je n'ai pas de groupe de sites, j'accède directement à la Carte-Liste des sites.

Une fois sur la fiche détail d'un site, j'affiche sa géométrie sur la carte, ses infos générales et la liste des visites qui lui sont rattachées. Les visites d'un site peuvent être dans différents protocoles. Dans la liste des visites d'un site, je dois donc afficher le protocole auquel chaque visite est rattachée.

Depuis la liste des groupes de sites, j'ai un bouton AJOUTER UN GROUPE DE SITES qui amène à son formulaire. Dans celui-ci je peux dessiner la géométrie du groupe de sites et le décrire. De la même manière je peux modifier un groupe de sites.
Actuellement un groupe de sites est associé à un module (protocole) : https://github.com/PnX-SI/gn_module_monitoring/blob/master/data/monitoring.sql#L42
Il faut certainement supprimer cette association. >> Voir les conséquences si on est rentré directement par un protocole.

Depuis la liste des sites, je peux modifier ou ajouter un site. Dans le formulaire je dois associer le site à un ou plusieurs modules (protocoles). 
Le problème de cela est que c'est chaque utilisateur qui va devoir le définir, sans forcément de cohérence. Cela pourrait être défini au niveau du type de site. Quand je créé un protocole je peux alors l'associer à un type de site (ou inversement ?).
Si cela n'est pas défini au niveau du type de site, alors on demande de la saisir au niveau de chaque site.
Si j'ajoute un site depuis la fiche d'un groupe de sites, alors ce site est automatiquement rattaché au groupe de sites.

Une conséquence importante de cela, est qu'actuellement on définit les champs d'un site dans la conf de chaque module (site.json). Cela n'est alors plus pertinent ni adapté car un site est utilisé potentiellement par plusieurs protocoles.
Il est proposé de définir les champs additionnels d'un site, au niveau global de Monitoring en fonction de leur type. 
Éventuellement pouvoir continuer à les compléter avec des champs additionnels au niveau de chaque protocole.

Revoir ``gn_monitoring.t_site_complements`` et ``t_sites_groups`` qui incluent un champs ``id_module``.
Et plutôt utiliser ``cor_site_module`` ?

![MCD](https://github.com/PnX-SI/gn_module_monitoring/blob/develop/docs/images/2021-10-MCD-monitoring.png?raw=true)

Quand je suis sur un site, je peux y ajouter une visite. Je dois commencer par choisir le protocole, en fonction de ceux disponibles pour ce site.

Vérifier les conséquences sur la fonctionnement actuel par protocole qui doit pouvoir toujours fonctionner.

Voir les répercussions sur les permissions au niveau des sites. Pouvoir quand même définir les permissions sur les sites par sous-module (protocole) ?

**Comment by Adrien-Pajot** [comment]
Salut, 

Merci pour ce ticket très complet sur la gestion des sites monitorés. Hâte de voir les évolutions (y a-t-il une branche qui ne citerait pas le ticket qui est commencée ?).

C'est exactement comme nous l'imaginions j'ai l'impression, avoir une entrée par sites avec protocoles et modules associés. 
À ce sujet, et en lien avec un travail avec les Terres Australes et Antarctiques Françaises, nous serons amenés à tester le module et à essayer de lui apporter des développements supplémentaires s'ils s'avéraient nécessaires. 
Nous pourrions aussi convenir d'un partage des tâches en fonction du temps alloué par les TAAF à ce sujet. Il peut être intéressant d'en discuter quand nous en saurons plus !

**Comment by Adrien-Pajot** [comment]
Un point qui je pense va ici : la géométrie du site monitoré devrait pouvoir évoluer le temps, une demande dans le suivi de sites comme les habitats ou des colonies d'animaux ou de stations botaniques

**Comment by vprunet** [comment]
> Un point qui je pense va ici : la géométrie du site monitoré devrait pouvoir évoluer le temps, une demande dans le suivi de sites comme les habitats ou des colonies d'animaux ou de stations botaniques

De façon plus générale, nous avons identifié le besoin de faire évoluer les attributs d'un site dans le temps. Par exemple, un site de chiroptères peut être mis en protection, dégradé ou détruit, ou encore des aménagements favorables peuvent être réalisés sur le site.

Dans notre cas, il s'agit donc des attributs spécifiques au module.

J'ai imaginé faire cela en clonant le site à l'instant t-1 vers un nouveau site valide à partir de l'instant t, avec des attributs mis à jour et d'associer tous ces sites dans un même regroupement de sites.

Cette approche ne nécessite pas forcément d'évolution du modèle de données sql, chaque visite pointant sur le site correspondant au statut le jour de la visite. Eventuellement ajouter des attributs `first_use_date` et `last_use_date` à la table `gn_monitoring.t_site_complements` pour guider les observateurs (ou le logiciel) dans le choix du site à présenter à la saisie.

Mais je me rends compte que cette approche contrevient au principe de sites multi-modules. Créer un nouveau site n'a pas de sens alors que seul ses attributs relatifs à un module donné ont changé.

Une approche plus rigoureuse consisterait à conserver la notion de site partagé par tous les modules (hormis pour les changements liés au site même comme ses coordonnées) et créer un nouvel enregistrement dans la table `gn_monitoring.t_site_complements` en conservant les enregistrements précédents (plusieurs compléments en relation avec un site et un module donnés, chacun avec une période de validité distincte). Et idéalement, la visite pointerait non plus sur le site mais sur le site_complement en vigueur le jour de la visite pour le module (refonte non triviale des modèles éclatés entre geonature/data/core et  gn_monitoring/data/. Accessoirement id_module ne serait plus nécessaire dans t_base_visits et on serait sûr que le site pointé par la visite est ouvert pour le module, ce qui n'est pas le cas aujourd'hui avec la seule contrainte `fk_t_base_visits_id_base_site` ).

C'est un peu complexe, j'en conviens, mais cela rendrait le modèle de données plus puissant et plus robuste.

Sur le front end pour gérer la dimension temporelle des sites :

- faciliter la création du nouveau site (ou site complément)  comme une copie à modifier du site (ou complément) précédent.
- ouvrir à la saisie de visites les seuls sites (ou compléments) actifs à la date de visite.
- présenter un historique de l'évolution d'un site (ou des compléments du site) pour le module.

**Comment by camillemonchicourt** [comment]
Je déplace le sujet de l'évolution des sites dans un ticket dédié (https://github.com/PnX-SI/gn_module_monitoring/issues/132) car il n'a que peu de lien avec l'entrée par site.

**Comment by camillemonchicourt** [comment]
Concernant l'entrée par site, voir la réflexion sur le modèle de données ici : https://github.com/PnX-SI/GeoNature/issues/1263#issuecomment-1015346622

**Comment by camillemonchicourt** [comment]
Nous avons travaillé sur le MCD et le fonctionnement à mettre en place pour pouvoir gérer le fait que les sites soient multi-protocoles et que leurs définition de champs soient liées à leur type et non plus leur protocole (module) : 

![MCD-monitoring](https://user-images.githubusercontent.com/4418840/165844126-e05ef8e8-5897-4bd8-b4c6-db8a42bca5fb.png)

- On définit les champs additionnels des sites au niveau de leur catégorie
- La notion de catégories de sites est ajoutée. On garde la notion de types de sites pour décrire plus finement un site. Par exemple "Gite" peut être une catégorie de site avec sa définition de champs. Et avoir différents types comme "Grotte", "Eglise", "Grenier", "Pont"...
- Pour gérer les catégories de sites, on peut créer une table dédiée (``bib_categories_site`` dans le MCD ci-dessus) si elle a des spécificités, ou utiliser les nomenclatures génériques de GeoNature comme c'est le cas pour les types de sites. La deuxième solution est privilégiée, sauf si des spécificités sont à prévoir
- Les fichiers json de configuration des champs additionnels des sites ne sont plus à gérer dans les fichiers de chaque sous-module, mais à un niveau plus global par catégorie. A voir où stocker et gérer ces fichiers
- Bien prévoir aussi la migration de l'ancien fonctionnement au nouveau pour ceux qui ont des modules existants
- En évolution, on peut quand même imaginer afficher ou non certains champs du site en fonction du protocole (sous-module) en fonction de la configuration de celui-ci
- On supprime le champs ``id_module`` des tables ``t_site_complements`` et ``t_sites_groups`` pour utiliser uniquement ``cor_site_module`` pour relier un site à ses protocoles (sous-modules)
- On relie aussi les catégories de sites aux modules pour pouvoir (optionnellement) définir quels catégories de sites peuvent être associées à quelles modules, et ainsi ne pas avoir d'incohérences en associant n'importe site à n'importe quel module
- Pas de changements au niveau des visites et des sites qui continuent à être associées à un seul site dans le cadre d'un seul protocole

A terme on prévoir aussi de supprimer les tables de compléments connectées en 1-1 pour basculer leur contenu dans les tables de base de ``gn_monitoring``. Cela simplifiera la gestion des données et notamment leur import. A faire dans une V2, dans un second temps.

**Comment by camillemonchicourt** [comment]
Le MCD avant ces évolutions (version 0.7) : 

![MCD 0.7](https://github.com/PnX-SI/gn_module_monitoring/blob/0.7.3/docs/images/2020-06-MCD-monitoring.jpg?raw=true)

Le MCD après ces évolutions (version 1.0.0) : 

![MCD 1.0.0](https://github.com/PnX-SI/gn_module_monitoring/blob/release/1.0.0/docs/images/2024-11-MCD_schema_monitoring.png?raw=true)

Exemples de répercussions des évolutions de modèle entre les versions 0.7 et 1.0 à faire sur les éventuels fichiers `synthese.sql`
et `export_csv.sql` de vos sous-modules : https://github.com/PnX-SI/protocoles_suivi/pull/38/files#diff-ae13e0bdc9ecdf9f27209ffc0b44ba601acbbedb4c9a2d05e1fc4bf14e655130
