### ISSUE TITLE
[0.2.7] Module html2canvas manquant

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#119]
Salut,
Il me manque un module pour cette installation :
![image](https://user-images.githubusercontent.com/66769358/139084562-e4398722-de08-4cfe-b6ac-8dba70039ccd.png)

Voici les logs au cas-où : 

    0 info it worked if it ends with ok
    1 verbose cli [ '/home/geonatureadmin/.nvm/versions/node/v10.15.3/bin/node',
    1 verbose cli   '/home/geonatureadmin/.nvm/versions/node/v10.15.3/bin/npm',
    1 verbose cli   'run',
    1 verbose cli   'build' ]
    2 info using npm@6.4.1
    3 info using node@v10.15.3
    4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
    5 info lifecycle geonature@0.0.0~prebuild: geonature@0.0.0
    6 info lifecycle geonature@0.0.0~build: geonature@0.0.0
    7 verbose lifecycle geonature@0.0.0~build: unsafe-perm in lifecycle true
    8 verbose lifecycle geonature@0.0.0~build: PATH: /home/geonatureadmin/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/geonatureadmin/geonature/frontend/node_modules/.bin:/home/geonatureadmin/geonature/backend/venv/bin:/home/geonatureadmin/.local/bin:/home/geonatureadmin/.nvm/versions/node/v10.15.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    9 verbose lifecycle geonature@0.0.0~build: CWD: /home/geonatureadmin/geonature/frontend
    10 silly lifecycle geonature@0.0.0~build: Args: [ '-c',
    10 silly lifecycle   '. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false' ]
    11 silly lifecycle geonature@0.0.0~build: Returned: code: 1  signal: null
    12 info lifecycle geonature@0.0.0~build: Failed to exec build script
    13 verbose stack Error: geonature@0.0.0 build: `. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false`
    13 verbose stack Exit status 1
    13 verbose stack     at EventEmitter.<anonymous> (/home/geonatureadmin/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
    13 verbose stack     at EventEmitter.emit (events.js:189:13)
    13 verbose stack     at ChildProcess.<anonymous> (/home/geonatureadmin/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    13 verbose stack     at ChildProcess.emit (events.js:189:13)
    13 verbose stack     at maybeClose (internal/child_process.js:970:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
    14 verbose pkgid geonature@0.0.0
    15 verbose cwd /home/geonatureadmin/geonature/frontend
    16 verbose Linux 4.19.0-12-amd64
    17 verbose argv "/home/geonatureadmin/.nvm/versions/node/v10.15.3/bin/node" "/home/geonatureadmin/.nvm/versions/node/v10.15.3/bin/npm" "run" "build"
    18 verbose node v10.15.3
    19 verbose npm  v6.4.1
    20 error code ELIFECYCLE
    21 error errno 1
    22 error geonature@0.0.0 build: `. ~/.nvm/nvm.sh; nvm use; ng build --prod --aot=false --build-optimizer=false`
    22 error Exit status 1
    23 error Failed at the geonature@0.0.0 build script.
    23 error This is probably not a problem with npm. There is likely additional logging output above.
    24 verbose exit [ 1, true ]

**Comment by maximetoma** [comment]
Alors html2canevas a bien été installé mais j'ai une erreur 2500 sur l'url `http://xx.x.xxx.xxx/geonature/api/monitoring/modules?`

Logs:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/modules/repositories.py", line 90, in get_modules
    DB.session.query(TMonitoringModules)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) ERREUR:  la colonne t_module_complements.meta_create_date n'existe pas
LINE 1: ...odule_order AS gn_commons_t_modules_module_order, gn_monitor...
                                                             ^

[SQL: SELECT gn_commons.t_modules.type AS gn_commons_t_modules_type, gn_monitoring.t_module_complements.id_module AS gn_monitoring_t_module_complements_id_module, gn_commons.t_modules.id_module AS gn_commons_t_modules_id_module, gn_commons.t_modules.module_code AS gn_commons_t_modules_module_code, gn_commons.t_modules.module_label AS gn_commons_t_modules_module_label, gn_commons.t_modules.module_picto AS gn_commons_t_modules_module_picto, gn_commons.t_modules.module_desc AS gn_commons_t_modules_module_desc, gn_commons.t_modules.module_group AS gn_commons_t_modules_module_group, gn_commons.t_modules.module_path AS gn_commons_t_modules_module_path, gn_commons.t_modules.module_external_url AS gn_commons_t_modules_module_external_url, gn_commons.t_modules.module_target AS gn_commons_t_modules_module_target, gn_commons.t_modules.module_comment AS gn_commons_t_modules_module_comment, gn_commons.t_modules.active_frontend AS gn_commons_t_modules_active_frontend, gn_commons.t_modules.active_backend AS gn_commons_t_modules_active_backend, gn_commons.t_modules.module_doc_url AS gn_commons_t_modules_module_doc_url, gn_commons.t_modules.module_order AS gn_commons_t_modules_module_order, gn_monitoring.t_module_complements.meta_create_date AS gn_monitoring_t_module_complements_meta_create_date, gn_commons.t_modules.meta_create_date AS gn_commons_t_modules_meta_create_date, gn_monitoring.t_module_complements.meta_update_date AS gn_monitoring_t_module_complements_meta_update_date, gn_commons.t_modules.meta_update_date AS gn_commons_t_modules_meta_update_date, gn_monitoring.t_module_complements.uuid_module_complement AS gn_monitoring_t_module_complements_uuid_module_complement, gn_monitoring.t_module_complements.id_list_observer AS gn_monitoring_t_module_complements_id_list_observer, gn_monitoring.t_module_complements.id_list_taxonomy AS gn_monitoring_t_module_complements_id_list_taxonomy, gn_monitoring.t_module_complements.taxonomy_display_field_name AS gn_monitoring_t_module_complements_taxonomy_display_field_1, gn_monitoring.t_module_complements.b_synthese AS gn_monitoring_t_module_complements_b_synthese, gn_monitoring.t_module_complements.data AS gn_monitoring_t_module_complements_data, t_medias_1.id_media AS t_medias_1_id_media, t_medias_1.id_nomenclature_media_type AS t_medias_1_id_nomenclature_media_type, t_medias_1.id_table_location AS t_medias_1_id_table_location, t_medias_1.unique_id_media AS t_medias_1_unique_id_media, t_medias_1.uuid_attached_row AS t_medias_1_uuid_attached_row, t_medias_1.title_fr AS t_medias_1_title_fr, t_medias_1.title_en AS t_medias_1_title_en, t_medias_1.title_it AS t_medias_1_title_it, t_medias_1.title_es AS t_medias_1_title_es, t_medias_1.title_de AS t_medias_1_title_de, t_medias_1.media_url AS t_medias_1_media_url, t_medias_1.media_path AS t_medias_1_media_path, t_medias_1.author AS t_medias_1_author, t_medias_1.description_fr AS t_medias_1_description_fr, t_medias_1.description_en AS t_medias_1_description_en, t_medias_1.description_it AS t_medias_1_description_it, t_medias_1.description_es AS t_medias_1_description_es, t_medias_1.description_de AS t_medias_1_description_de, t_medias_1.is_public AS t_medias_1_is_public, t_medias_1.meta_create_date AS t_medias_1_meta_create_date, t_medias_1.meta_update_date AS t_medias_1_meta_update_date, t_roles_1.pass AS t_roles_1_pass, t_roles_1.pass_plus AS t_roles_1_pass_plus, t_roles_1.groupe AS t_roles_1_groupe, t_roles_1.id_role AS t_roles_1_id_role, t_roles_1.identifiant AS t_roles_1_identifiant, t_roles_1.nom_role AS t_roles_1_nom_role, t_roles_1.prenom_role AS t_roles_1_prenom_role, t_roles_1.desc_role AS t_roles_1_desc_role, t_roles_1.email AS t_roles_1_email, t_roles_1.id_organisme AS t_roles_1_id_organisme, t_roles_1.remarques AS t_roles_1_remarques, t_roles_1.date_insert AS t_roles_1_date_insert, t_roles_1.date_update AS t_roles_1_date_update, t_roles_1.active AS t_roles_1_active, t_roles_2.pass AS t_roles_2_pass, t_roles_2.pass_plus AS t_roles_2_pass_plus, t_roles_2.groupe AS t_roles_2_groupe, t_roles_2.id_role AS t_roles_2_id_role, t_roles_2.identifiant AS t_roles_2_identifiant, t_roles_2.nom_role AS t_roles_2_nom_role, t_roles_2.prenom_role AS t_roles_2_prenom_role, t_roles_2.desc_role AS t_roles_2_desc_role, t_roles_2.email AS t_roles_2_email, t_roles_2.id_organisme AS t_roles_2_id_organisme, t_roles_2.remarques AS t_roles_2_remarques, t_roles_2.date_insert AS t_roles_2_date_insert, t_roles_2.date_update AS t_roles_2_date_update, t_roles_2.active AS t_roles_2_active, bib_organismes_1.id_organisme AS bib_organismes_1_id_organisme, bib_organismes_1.uuid_organisme AS bib_organismes_1_uuid_organisme, bib_organismes_1.nom_organisme AS bib_organismes_1_nom_organisme, bib_organismes_1.adresse_organisme AS bib_organismes_1_adresse_organisme, bib_organismes_1.cp_organisme AS bib_organismes_1_cp_organisme, bib_organismes_1.ville_organisme AS bib_organismes_1_ville_organisme, bib_organismes_1.tel_organisme AS bib_organismes_1_tel_organisme, bib_organismes_1.fax_organisme AS bib_organismes_1_fax_organisme, bib_organismes_1.email_organisme AS bib_organismes_1_email_organisme, bib_organismes_1.url_organisme AS bib_organismes_1_url_organisme, bib_organismes_1.url_logo AS bib_organismes_1_url_logo, bib_organismes_1.id_parent AS bib_organismes_1_id_parent, bib_organismes_1.additional_data AS bib_organismes_1_additional_data, t_nomenclatures_1.id_nomenclature AS t_nomenclatures_1_id_nomenclature, t_nomenclatures_1.id_type AS t_nomenclatures_1_id_type, t_nomenclatures_1.cd_nomenclature AS t_nomenclatures_1_cd_nomenclature, t_nomenclatures_1.mnemonique AS t_nomenclatures_1_mnemonique, t_nomenclatures_1.label_default AS t_nomenclatures_1_label_default, t_nomenclatures_1.definition_default AS t_nomenclatures_1_definition_default, t_nomenclatures_1.label_fr AS t_nomenclatures_1_label_fr, t_nomenclatures_1.definition_fr AS t_nomenclatures_1_definition_fr, t_nomenclatures_1.label_en AS t_nomenclatures_1_label_en, t_nomenclatures_1.definition_en AS t_nomenclatures_1_definition_en, t_nomenclatures_1.label_es AS t_nomenclatures_1_label_es, t_nomenclatures_1.definition_es AS t_nomenclatures_1_definition_es, t_nomenclatures_1.label_de AS t_nomenclatures_1_label_de, t_nomenclatures_1.definition_de AS t_nomenclatures_1_definition_de, t_nomenclatures_1.label_it AS t_nomenclatures_1_label_it, t_nomenclatures_1.definition_it AS t_nomenclatures_1_definition_it, t_nomenclatures_1.source AS t_nomenclatures_1_source, t_nomenclatures_1.statut AS t_nomenclatures_1_statut, t_nomenclatures_1.id_broader AS t_nomenclatures_1_id_broader, t_nomenclatures_1.hierarchy AS t_nomenclatures_1_hierarchy, t_nomenclatures_1.active AS t_nomenclatures_1_active, t_nomenclatures_1.meta_create_date AS t_nomenclatures_1_meta_create_date, t_nomenclatures_1.meta_update_date AS t_nomenclatures_1_meta_update_date, cor_dataset_actor_1.id_cda AS cor_dataset_actor_1_id_cda, cor_dataset_actor_1.id_dataset AS cor_dataset_actor_1_id_dataset, cor_dataset_actor_1.id_role AS cor_dataset_actor_1_id_role, cor_dataset_actor_1.id_organism AS cor_dataset_actor_1_id_organism, cor_dataset_actor_1.id_nomenclature_actor_role AS cor_dataset_actor_1_id_nomenclature_actor_role, t_datasets_1.id_dataset AS t_datasets_1_id_dataset, t_datasets_1.unique_dataset_id AS t_datasets_1_unique_dataset_id, t_datasets_1.id_acquisition_framework AS t_datasets_1_id_acquisition_framework, t_datasets_1.dataset_name AS t_datasets_1_dataset_name, t_datasets_1.dataset_shortname AS t_datasets_1_dataset_shortname, t_datasets_1.dataset_desc AS t_datasets_1_dataset_desc, t_datasets_1.id_nomenclature_data_type AS t_datasets_1_id_nomenclature_data_type, t_datasets_1.keywords AS t_datasets_1_keywords, t_datasets_1.marine_domain AS t_datasets_1_marine_domain, t_datasets_1.terrestrial_domain AS t_datasets_1_terrestrial_domain, t_datasets_1.id_nomenclature_dataset_objectif AS t_datasets_1_id_nomenclature_dataset_objectif, t_datasets_1.bbox_west AS t_datasets_1_bbox_west, t_datasets_1.bbox_east AS t_datasets_1_bbox_east, t_datasets_1.bbox_south AS t_datasets_1_bbox_south, t_datasets_1.bbox_north AS t_datasets_1_bbox_north, t_datasets_1.id_nomenclature_collecting_method AS t_datasets_1_id_nomenclature_collecting_method, t_datasets_1.id_nomenclature_data_origin AS t_datasets_1_id_nomenclature_data_origin, t_datasets_1.id_nomenclature_source_status AS t_datasets_1_id_nomenclature_source_status, t_datasets_1.id_nomenclature_resource_type AS t_datasets_1_id_nomenclature_resource_type, t_datasets_1.meta_create_date AS t_datasets_1_meta_create_date, t_datasets_1.meta_update_date AS t_datasets_1_meta_update_date, t_datasets_1.active AS t_datasets_1_active, t_datasets_1.validable AS t_datasets_1_validable, t_datasets_1.id_digitizer AS t_datasets_1_id_digitizer, t_datasets_1.id_taxa_list AS t_datasets_1_id_taxa_list 
FROM gn_commons.t_modules JOIN gn_monitoring.t_module_complements ON gn_commons.t_modules.id_module = gn_monitoring.t_module_complements.id_module LEFT OUTER JOIN gn_commons.t_medias AS t_medias_1 ON t_medias_1.uuid_attached_row = gn_monitoring.t_module_complements.uuid_module_complement LEFT OUTER JOIN (gn_commons.cor_module_dataset AS cor_module_dataset_1 JOIN gn_meta.t_datasets AS t_datasets_1 ON t_datasets_1.id_dataset = cor_module_dataset_1.id_dataset) ON gn_commons.t_modules.id_module = cor_module_dataset_1.id_module LEFT OUTER JOIN utilisateurs.t_roles AS t_roles_1 ON t_roles_1.id_role = t_datasets_1.id_digitizer LEFT OUTER JOIN gn_meta.cor_dataset_actor AS cor_dataset_actor_1 ON t_datasets_1.id_dataset = cor_dataset_actor_1.id_dataset LEFT OUTER JOIN utilisateurs.t_roles AS t_roles_2 ON t_roles_2.id_role = cor_dataset_actor_1.id_role LEFT OUTER JOIN utilisateurs.bib_organismes AS bib_organismes_1 ON bib_organismes_1.id_organisme = cor_dataset_actor_1.id_organism LEFT OUTER JOIN ref_nomenclatures.t_nomenclatures AS t_nomenclatures_1 ON t_nomenclatures_1.id_nomenclature = cor_dataset_actor_1.id_nomenclature_actor_role]
(Background on this error at: http://sqlalche.me/e/13/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/decorators.py", line 106, in __check_cruved_scope_monitoring
    return fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/modules.py", line 52, in get_modules_api
    modules = get_modules()
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/modules/repositories.py", line 97, in get_modules
    raise GeoNatureError("MONITORINGS - get_modules : {}".format(str(e)))
geonature.utils.errors.GeoNatureError: MONITORINGS - get_modules : (psycopg2.errors.UndefinedColumn) ERREUR:  la colonne t_module_complements.meta_create_date n'existe pas
LINE 1: ...odule_order AS gn_commons_t_modules_module_order, gn_monitor...
                                                             ^

[SQL: SELECT gn_commons.t_modules.type AS gn_commons_t_modules_type, gn_monitoring.t_module_complements.id_module AS gn_monitoring_t_module_complements_id_module, gn_commons.t_modules.id_module AS gn_commons_t_modules_id_module, gn_commons.t_modules.module_code AS gn_commons_t_modules_module_code, gn_commons.t_modules.module_label AS gn_commons_t_modules_module_label, gn_commons.t_modules.module_picto AS gn_commons_t_modules_module_picto, gn_commons.t_modules.module_desc AS gn_commons_t_modules_module_desc, gn_commons.t_modules.module_group AS gn_commons_t_modules_module_group, gn_commons.t_modules.module_path AS gn_commons_t_modules_module_path, gn_commons.t_modules.module_external_url AS gn_commons_t_modules_module_external_url, gn_commons.t_modules.module_target AS gn_commons_t_modules_module_target, gn_commons.t_modules.module_comment AS gn_commons_t_modules_module_comment, gn_commons.t_modules.active_frontend AS gn_commons_t_modules_active_frontend, gn_commons.t_modules.active_backend AS gn_commons_t_modules_active_backend, gn_commons.t_modules.module_doc_url AS gn_commons_t_modules_module_doc_url, gn_commons.t_modules.module_order AS gn_commons_t_modules_module_order, gn_monitoring.t_module_complements.meta_create_date AS gn_monitoring_t_module_complements_meta_create_date, gn_commons.t_modules.meta_create_date AS gn_commons_t_modules_meta_create_date, gn_monitoring.t_module_complements.meta_update_date AS gn_monitoring_t_module_complements_meta_update_date, gn_commons.t_modules.meta_update_date AS gn_commons_t_modules_meta_update_date, gn_monitoring.t_module_complements.uuid_module_complement AS gn_monitoring_t_module_complements_uuid_module_complement, gn_monitoring.t_module_complements.id_list_observer AS gn_monitoring_t_module_complements_id_list_observer, gn_monitoring.t_module_complements.id_list_taxonomy AS gn_monitoring_t_module_complements_id_list_taxonomy, gn_monitoring.t_module_complements.taxonomy_display_field_name AS gn_monitoring_t_module_complements_taxonomy_display_field_1, gn_monitoring.t_module_complements.b_synthese AS gn_monitoring_t_module_complements_b_synthese, gn_monitoring.t_module_complements.data AS gn_monitoring_t_module_complements_data, t_medias_1.id_media AS t_medias_1_id_media, t_medias_1.id_nomenclature_media_type AS t_medias_1_id_nomenclature_media_type, t_medias_1.id_table_location AS t_medias_1_id_table_location, t_medias_1.unique_id_media AS t_medias_1_unique_id_media, t_medias_1.uuid_attached_row AS t_medias_1_uuid_attached_row, t_medias_1.title_fr AS t_medias_1_title_fr, t_medias_1.title_en AS t_medias_1_title_en, t_medias_1.title_it AS t_medias_1_title_it, t_medias_1.title_es AS t_medias_1_title_es, t_medias_1.title_de AS t_medias_1_title_de, t_medias_1.media_url AS t_medias_1_media_url, t_medias_1.media_path AS t_medias_1_media_path, t_medias_1.author AS t_medias_1_author, t_medias_1.description_fr AS t_medias_1_description_fr, t_medias_1.description_en AS t_medias_1_description_en, t_medias_1.description_it AS t_medias_1_description_it, t_medias_1.description_es AS t_medias_1_description_es, t_medias_1.description_de AS t_medias_1_description_de, t_medias_1.is_public AS t_medias_1_is_public, t_medias_1.meta_create_date AS t_medias_1_meta_create_date, t_medias_1.meta_update_date AS t_medias_1_meta_update_date, t_roles_1.pass AS t_roles_1_pass, t_roles_1.pass_plus AS t_roles_1_pass_plus, t_roles_1.groupe AS t_roles_1_groupe, t_roles_1.id_role AS t_roles_1_id_role, t_roles_1.identifiant AS t_roles_1_identifiant, t_roles_1.nom_role AS t_roles_1_nom_role, t_roles_1.prenom_role AS t_roles_1_prenom_role, t_roles_1.desc_role AS t_roles_1_desc_role, t_roles_1.email AS t_roles_1_email, t_roles_1.id_organisme AS t_roles_1_id_organisme, t_roles_1.remarques AS t_roles_1_remarques, t_roles_1.date_insert AS t_roles_1_date_insert, t_roles_1.date_update AS t_roles_1_date_update, t_roles_1.active AS t_roles_1_active, t_roles_2.pass AS t_roles_2_pass, t_roles_2.pass_plus AS t_roles_2_pass_plus, t_roles_2.groupe AS t_roles_2_groupe, t_roles_2.id_role AS t_roles_2_id_role, t_roles_2.identifiant AS t_roles_2_identifiant, t_roles_2.nom_role AS t_roles_2_nom_role, t_roles_2.prenom_role AS t_roles_2_prenom_role, t_roles_2.desc_role AS t_roles_2_desc_role, t_roles_2.email AS t_roles_2_email, t_roles_2.id_organisme AS t_roles_2_id_organisme, t_roles_2.remarques AS t_roles_2_remarques, t_roles_2.date_insert AS t_roles_2_date_insert, t_roles_2.date_update AS t_roles_2_date_update, t_roles_2.active AS t_roles_2_active, bib_organismes_1.id_organisme AS bib_organismes_1_id_organisme, bib_organismes_1.uuid_organisme AS bib_organismes_1_uuid_organisme, bib_organismes_1.nom_organisme AS bib_organismes_1_nom_organisme, bib_organismes_1.adresse_organisme AS bib_organismes_1_adresse_organisme, bib_organismes_1.cp_organisme AS bib_organismes_1_cp_organisme, bib_organismes_1.ville_organisme AS bib_organismes_1_ville_organisme, bib_organismes_1.tel_organisme AS bib_organismes_1_tel_organisme, bib_organismes_1.fax_organisme AS bib_organismes_1_fax_organisme, bib_organismes_1.email_organisme AS bib_organismes_1_email_organisme, bib_organismes_1.url_organisme AS bib_organismes_1_url_organisme, bib_organismes_1.url_logo AS bib_organismes_1_url_logo, bib_organismes_1.id_parent AS bib_organismes_1_id_parent, bib_organismes_1.additional_data AS bib_organismes_1_additional_data, t_nomenclatures_1.id_nomenclature AS t_nomenclatures_1_id_nomenclature, t_nomenclatures_1.id_type AS t_nomenclatures_1_id_type, t_nomenclatures_1.cd_nomenclature AS t_nomenclatures_1_cd_nomenclature, t_nomenclatures_1.mnemonique AS t_nomenclatures_1_mnemonique, t_nomenclatures_1.label_default AS t_nomenclatures_1_label_default, t_nomenclatures_1.definition_default AS t_nomenclatures_1_definition_default, t_nomenclatures_1.label_fr AS t_nomenclatures_1_label_fr, t_nomenclatures_1.definition_fr AS t_nomenclatures_1_definition_fr, t_nomenclatures_1.label_en AS t_nomenclatures_1_label_en, t_nomenclatures_1.definition_en AS t_nomenclatures_1_definition_en, t_nomenclatures_1.label_es AS t_nomenclatures_1_label_es, t_nomenclatures_1.definition_es AS t_nomenclatures_1_definition_es, t_nomenclatures_1.label_de AS t_nomenclatures_1_label_de, t_nomenclatures_1.definition_de AS t_nomenclatures_1_definition_de, t_nomenclatures_1.label_it AS t_nomenclatures_1_label_it, t_nomenclatures_1.definition_it AS t_nomenclatures_1_definition_it, t_nomenclatures_1.source AS t_nomenclatures_1_source, t_nomenclatures_1.statut AS t_nomenclatures_1_statut, t_nomenclatures_1.id_broader AS t_nomenclatures_1_id_broader, t_nomenclatures_1.hierarchy AS t_nomenclatures_1_hierarchy, t_nomenclatures_1.active AS t_nomenclatures_1_active, t_nomenclatures_1.meta_create_date AS t_nomenclatures_1_meta_create_date, t_nomenclatures_1.meta_update_date AS t_nomenclatures_1_meta_update_date, cor_dataset_actor_1.id_cda AS cor_dataset_actor_1_id_cda, cor_dataset_actor_1.id_dataset AS cor_dataset_actor_1_id_dataset, cor_dataset_actor_1.id_role AS cor_dataset_actor_1_id_role, cor_dataset_actor_1.id_organism AS cor_dataset_actor_1_id_organism, cor_dataset_actor_1.id_nomenclature_actor_role AS cor_dataset_actor_1_id_nomenclature_actor_role, t_datasets_1.id_dataset AS t_datasets_1_id_dataset, t_datasets_1.unique_dataset_id AS t_datasets_1_unique_dataset_id, t_datasets_1.id_acquisition_framework AS t_datasets_1_id_acquisition_framework, t_datasets_1.dataset_name AS t_datasets_1_dataset_name, t_datasets_1.dataset_shortname AS t_datasets_1_dataset_shortname, t_datasets_1.dataset_desc AS t_datasets_1_dataset_desc, t_datasets_1.id_nomenclature_data_type AS t_datasets_1_id_nomenclature_data_type, t_datasets_1.keywords AS t_datasets_1_keywords, t_datasets_1.marine_domain AS t_datasets_1_marine_domain, t_datasets_1.terrestrial_domain AS t_datasets_1_terrestrial_domain, t_datasets_1.id_nomenclature_dataset_objectif AS t_datasets_1_id_nomenclature_dataset_objectif, t_datasets_1.bbox_west AS t_datasets_1_bbox_west, t_datasets_1.bbox_east AS t_datasets_1_bbox_east, t_datasets_1.bbox_south AS t_datasets_1_bbox_south, t_datasets_1.bbox_north AS t_datasets_1_bbox_north, t_datasets_1.id_nomenclature_collecting_method AS t_datasets_1_id_nomenclature_collecting_method, t_datasets_1.id_nomenclature_data_origin AS t_datasets_1_id_nomenclature_data_origin, t_datasets_1.id_nomenclature_source_status AS t_datasets_1_id_nomenclature_source_status, t_datasets_1.id_nomenclature_resource_type AS t_datasets_1_id_nomenclature_resource_type, t_datasets_1.meta_create_date AS t_datasets_1_meta_create_date, t_datasets_1.meta_update_date AS t_datasets_1_meta_update_date, t_datasets_1.active AS t_datasets_1_active, t_datasets_1.validable AS t_datasets_1_validable, t_datasets_1.id_digitizer AS t_datasets_1_id_digitizer, t_datasets_1.id_taxa_list AS t_datasets_1_id_taxa_list 
FROM gn_commons.t_modules JOIN gn_monitoring.t_module_complements ON gn_commons.t_modules.id_module = gn_monitoring.t_module_complements.id_module LEFT OUTER JOIN gn_commons.t_medias AS t_medias_1 ON t_medias_1.uuid_attached_row = gn_monitoring.t_module_complements.uuid_module_complement LEFT OUTER JOIN (gn_commons.cor_module_dataset AS cor_module_dataset_1 JOIN gn_meta.t_datasets AS t_datasets_1 ON t_datasets_1.id_dataset = cor_module_dataset_1.id_dataset) ON gn_commons.t_modules.id_module = cor_module_dataset_1.id_module LEFT OUTER JOIN utilisateurs.t_roles AS t_roles_1 ON t_roles_1.id_role = t_datasets_1.id_digitizer LEFT OUTER JOIN gn_meta.cor_dataset_actor AS cor_dataset_actor_1 ON t_datasets_1.id_dataset = cor_dataset_actor_1.id_dataset LEFT OUTER JOIN utilisateurs.t_roles AS t_roles_2 ON t_roles_2.id_role = cor_dataset_actor_1.id_role LEFT OUTER JOIN utilisateurs.bib_organismes AS bib_organismes_1 ON bib_organismes_1.id_organisme = cor_dataset_actor_1.id_organism LEFT OUTER JOIN ref_nomenclatures.t_nomenclatures AS t_nomenclatures_1 ON t_nomenclatures_1.id_nomenclature = cor_dataset_actor_1.id_nomenclature_actor_role]
(Background on this error at: http://sqlalche.me/e/13/f405)

**Comment by camillemonchicourt** [comment]
Du coup les notes que vous avez ajouté dans le Changelog sont OK ?
https://github.com/PnX-SI/gn_module_monitoring/blob/master/docs/changelog.rst
On peut autant faire ``npm install`` que ``npm ci`` ?
Pourquoi ne pas en indiquer qu'une seule pour éviter les doutes ?

**Comment by maximetoma** [comment]
Effectivement ce n'est plus bon...
Je vais faire la modif sur le changelog

Ce qui a marché chez moi, c'est : 
    cd <modulemonitoring>/frontend
    rm -R node_modules
    npm install
    ls node_modules/html2canvas
