### ISSUE TITLE
Création site - Enchaîner les saisies

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#12]
Fonctionnalité intéressante, actuellement sous forme de case à cocher en bas du formulaire. 

Je ne sais pas si la solution est idéale, mais pour la cohérence de GeoNature, je privilégierai de faire comme dans Occtax, avec un bouton en haut à droite : 

![image](https://user-images.githubusercontent.com/4418840/78714410-1e24e100-791c-11ea-92d8-07467d365385.png)

**Comment by amandine-sahl** [comment]
Même si je ne suis pas très convaincu par l'ergonomie de occtax

**Comment by camillemonchicourt** [comment]
Oui c'est assez caché mais on a eu des bon retours sur le fonctionnement. Ça peut être mis ailleurs avec un message en plus de l'icône
