### ISSUE TITLE
[0.2.7] Impossible d'installer un sous-module

### ISSUE THREAD

**Issue by mvergez** [PnX-SI/gn_module_monitoring#121]
Bonjour,

## Contexte
En voulant installer le sous-module "test" livré avec gn_monitoring, sur GeoNature 2.8.1, je suis tombé sur l'erreur suivante (tronquée pour plus de lisibilité) :
```
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: ERREUR:  l'enregistrement « new » n'a pas de champs « meta_create_date »
CONTEXT:  fonction PL/pgSQL fct_trg_meta_dates_change(), ligne 4 à affectation
```
En cherchant un peu : 
- La fonction `fct_trg_meta_dates_change()` est appelée par le trigger sur `gn_monitoring.t_module_complements`
- Elle semble mettre à jour une colonne appelée `meta_create_date`
- Or en regardant l'historique dans "intégration PR geofit" : `meta_create_date` et `meta_update_date` ont disparu de la table `t_module_complements`. Voir classe : https://github.com/PnX-SI/gn_module_monitoring/blob/517535f71979db1535ed6e86406ad29248047a44/backend/monitoring/models.py#L288-L343

Savez-vous où ce trigger est créé ? Car j'ai l'impression qu'il est créé ici : https://github.com/PnX-SI/gn_module_monitoring/blob/517535f71979db1535ed6e86406ad29248047a44/data/schema_suivis_generique.sql#L28
Mais ce fichier sql ne semble pas appelé

## Potentielle solution

En exécutant la commande suivante : 
```sql
DROP TRIGGER IF EXISTS tri_meta_dates_change_t_module_complements ON gn_monitoring.t_module_complements;
```
L'installation fonctionne.

Merci d'avance pour vos retours

**Comment by camillemonchicourt** [comment]
Oui je crois que c'est la même chose que https://github.com/PnX-SI/gn_module_monitoring/issues/118

Ça vaudrait une release corrective.

**Comment by mvergez** [comment]
Effectivement je ne l'avais pas vu, désolé du doublon...
Je crois qu'un commit a été fait pour corriger ce problème.

Merci beaucoup @camillemonchicourt

**Comment by camillemonchicourt** [comment]
Oui, pas de soucis car c'était fermé et pas releasé.
J'ai préparé une release corrective (https://github.com/PnX-SI/gn_module_monitoring/pull/122), mais je laisse @joelclems vérifier, merger (car il y a un petit conflit du changelog) et faire la release.
Merci.

**Comment by amandine-sahl** [comment]
Résolue avec la 0.2.8
