### ISSUE TITLE
Standard de nomenclatures 

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_module_monitoring#127]
Salut, 

J'ouvre peut-être un ticket évident pour vous mais j'ai pas l'impression de l'avoir vu avant : les standards de nomenclatures dans gn_monitoring. 

Actuellement ces nomenclatures sont parfaitement gérées en base dans GeoNature, mais sont-elles reportées/reportables facilement dans gn_monitoring ? 
Par exemple, je dois pouvoir qualifier mon observation dans un protocole par un ou plusieurs champs standards. Je pourrai faire appel à une route liée à ma BDD GeoNature pour avoir les valeurs en front mais après comment je les stocke en back ? Dans le JSON ? Est-ce le mieux ? Devons-nous repartir du fait qu'un protocole est une observation élargie comme est entrain de faire le niveau national ? 

Merci pour vos lumières et pardon si c'est stupide.

**Comment by camillemonchicourt** [comment]
Quand tu définis un champs un protocoles, tu dois lui définir un type. Ce type peut être un champs texte, numérique, booléen, une liste...
Quand il s'agit d'une liste, tu peux définir directement les items de la liste, ou alors la baser sur une nomenclature (existante ou créée pour le protocole)

**Comment by joelclems** [comment]
on peut définir un champs de nomenclature par exemple

https://github.com/PnX-SI/gn_module_monitoring/blob/787b7c6d8ad8629299ed766f345f5518b4c955ea/config/monitoring/generic/site.json#L67-L78

l'id est traduite en label pour les composant de liste ou de propriete

**Comment by Adrien-Pajot** [comment]
Cool merci !

**Comment by camillemonchicourt** [comment]
OK mais du coup on stocke l'id de la nomenclature, son code, ou son label ?

**Comment by joelclems** [comment]
L'id est stockée, la ligne `"type_util": "nomenclature", ` permet d'identifier la variable comme une id de nomenclature et de la traiter en tant que telle

**Comment by joelclems** [comment]
`type_util` permet de gérer tout les cas ou l'on a un id et on veut retrouver un information (le nom, le label) sur l'objet
les valeurs possibiles sont
```
'habitat'
'nomenclature'
'user'
'taxonomy'
'dataset'
'observer_list'
'taxonomy_list'
'sites_group'
'site'
```
