### ISSUE TITLE
Media dans gn_monitoring - Medias transverses à tout GeoNature

### ISSUE THREAD

**Issue by Adrien-Pajot** [PnX-SI/gn_module_monitoring#128]
L'ajout de media lors d'un protocole à chaque étape pourrait être intéressant, est nécessaire pour l'observation au moins, parfois ? 
(Protocole de photoID par exemple) 
On retrouve qqch à implémenter dans le coeur du module?

**Comment by camillemonchicourt** [comment]
On peut ajouter des médias dans les protocoles de Monitoring.
Je ne sais plus si c'est à tous les niveaux (site, visite, observation) mais je crois que oui.

**Comment by Adrien-Pajot** [comment]
Je le voyais pas dans le schéma de la BDD, mais cool si possible ! Si c'est sûr on peut fermer le ticket :)
