### ISSUE TITLE
[0.2.7] 'TMonitoringModules' object has no attribute 'b_draw_sites_group'

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#129]
Bonjour,

J'ai un soucis lors de l'accès à mes sous-modules.
Quand je clique sur n'importe lequel de mes sous-modules, j'ai une erreur 500 sur la route `http://192.168.0.26/geonature/api/monitoring/object/<modulename>/module?depth=1&field_name=module_code` et rien ne s'affiche

Sur mon serveur TEST tout fonctionne, le problème est sur ma PROD....
Je suis sur GeoNature 2.8.1 pour les deux
La colonne est bien présente dans la table t_module_complements et le dossier generic présent bien la variable `b_draw_sites_group`

### Les logs m'affichent : 

[2021-11-17 13:54:04 +0100] [8135] [ERROR] Exception on /monitoring/object/popreptile_rnmo/module [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/decorators.py", line 106, in __check_cruved_scope_monitoring
    return fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/monitoring.py", line 62, in get_monitoring_object_api
    depth = to_int(request.args.get('depth', 1))
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/serializer.py", line 122, in serialize
    val = getattr(self._model, field_name)
AttributeError: 'TMonitoringModules' object has no attribute 'b_draw_sites_group'

**Comment by joelclems** [comment]
Le modèle sqlalchemy `TMonitoringModules` à normalement un attribut `b_draw_sites_group` qui est défini

https://github.com/PnX-SI/gn_module_monitoring/blob/787b7c6d8ad8629299ed766f345f5518b4c955ea/backend/monitoring/models.py#L309

est ce que c'est bien le cas dans les fichiers de la prod ?

**Comment by maximetoma** [comment]
Oui, il est bien présent

**Comment by joelclems** [comment]
c'est surement pas cela mais et ce que la prod à été redemarrée  en supervisor ou en systemclt (bien verifier lequel tourne)?

**Comment by maximetoma** [comment]
Merci ! J'ai réglé le soucis à 80% :-)
J'ai vérifié avec `systemctl status geonature` et le service était actif
J'ai restart quand même et... ça a réglé le soucis ! Sauf que je ne peux pas accéder au module POPReptile. Il m'indique une nouvelle erreur : 

[2021-11-17 14:49:57 +0100] [13287] [ERROR] Exception on /monitoring/util/init_data/popreptile_rnmo [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/data_utils.py", line 74, in get_init_data
    for nomenclature in nomenclature_list['values']:
TypeError: 'NoneType' object is not subscriptable

**Comment by joelclems** [comment]
Le rederrage à surement permis de prendre en compte les changement des fichiers .py

pour cette erreur c'est comme si on avait un type de nomenclature présent dans les fichier .json du modules, mais que ce type n'est pas présent en base, cela pourrait arriver si une nomenclature spécifique est définie dans le fichier `nomenclature.json` du module mais qu'elles n'ont pas été intégrée à l'installation du sous-module

peut être que la commande 
```
geonature monitorings add_module_nomenclature <module_code>
```

peut régler le soucis si un fichier `nomenclature.json` est présent pour le sous-module en question?

**Comment by maximetoma** [comment]
Effectivement c'est d'autant plus bizarre que ça a quand même installé les nomenclatures...
J'ai refait la commande au cas-où mais sans résultat... Les nomenclatures sont bien présentes en revanche

**Comment by joelclems** [comment]
est ce qu'il t'est possible de rajouter un print 
```
print(code_type)
```
dans le fichier `/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/data_utils.py` vers la ligne 74 pour savoir quelle type  de nomenclature declenche l'erreur

```
    # nomenclature
    if data.get('nomenclature'):
        out['nomenclature'] = []
        for code_type in data.get('nomenclature'):
            nomenclature_list = get_nomenclature_list(code_type=code_type)
            print(code_type)
            for nomenclature in nomenclature_list['values']:
                nomenclature['code_type']=code_type
                out['nomenclature'].append(nomenclature)
```

**Comment by joelclems** [comment]
et de relancer le service geonature pour qu'il prennent en compte les modifs

**Comment by maximetoma** [comment]
Ça n'accepte pas la modification, le service plante si je rajoute le print et ne veut pas redémarrer malheureusement...

**Comment by joelclems** [comment]
ça devrait mieux marcher avec les logs
en remplaçant le print(code_type) par ces trois lignes
```
import logging
log = logging.getLogger()
 log.info(code_type)
```

**Comment by maximetoma** [comment]
Voici les logs en entier : 
[popreptile_log.log](https://github.com/PnX-SI/gn_module_monitoring/files/7555530/popreptile_log.log)

**Comment by joelclems** [comment]
c'est le type PLUVIOSITE, qui est défini dans le fichier nomenclature.json de POPAmphibien mais non dans POPReptile (et pourtant bien utilisé dans pop reptile

**Comment by joelclems** [comment]
il va manquer aussi NOMBRE_ESTIME, VENT, ENSOLEILLEMENT
dans l'immédiat le plus simple serait d'installer les nomenclatures de POPAmphibien qui recoupe celles de POPReptile et ajoutent les manquantes

pour cela soit installer POPAmphibien

soit faire une petite manip

dans POPRepile

- renommer `POPReptile/nomenclature.json` en  `POPReptile/nomenclature.json_save`
- copier le fichier ` POPAmphibien/nomenclature.json` vers `POPReptile/nomenclature.json`
- rejouer la commande `geonature monitorings add_module_nomenclature <module_code_POPReptile>`
  - cela ne pose pas de soucis pour les nomenclature existantes et ça va rajouter les manquantes

**Comment by maximetoma** [comment]
Tu veux dire ici : https://github.com/PnCevennes/protocoles_suivi ? A cause des petites coquilles à corriger comme celle-là ? :-)

**Comment by camillemonchicourt** [comment]
Oui, on n'aurait pas du intégrer ces récents exemples de module dans le dépôt ``gn_module_monitoring``, car du coup on mélange ici des soucis du module Monitoring et des soucis d'un exemple de sous-module.
A sortir dès que possible dans le dépôt https://github.com/PnCevennes/protocoles_suivi
