### ISSUE TITLE
Create site / Ajout GPS et FileLayer

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#13]
Si on reprend le fonctionnement d'Occtax au niveau du marker de localisation (https://github.com/PnX-SI/gn_module_monitoring/issues/6) on peut aussi envisager ajouter la localisation en saisissant des coordonnées GPS ou en chargeant un fichier GPX ou GeoJSON avec Leaflet.Filelayer comme dans Occtax.

**Comment by joelclems** [comment]
Pour bien comprendre, on charge le fichier gpx ou geojson, les géométries sont affichées sur le carte et on peut choisir la géométrie d'un site en cliquant sur un point (ou autre type de géométrie)?
Est ce qu'on peut récupérer et se servir d'autres données (pour avoir le nom du site etc...) ,
ou même la date pour aider à la création de la visite?

**Comment by camillemonchicourt** [comment]
Oui c'est ça, d'ailleurs @TheoLechemia vient de remettre en place la fonctionnalité quand on enchaine les relevés sur la refonte d'Occtax : https://github.com/PnX-SI/GeoNature/issues/813

Clic gauche sur un objet du fichier permet de sélectionner sa géométrie, clic droit d'en afficher les attributs (https://github.com/PnX-SI/GeoNature/issues/256#issuecomment-458497198).

Et donc en mode enchainer les relevés (enchainer les sites dans notre cas), il serait idéal d'avoir le même fonctionnement que pour Occtax. Je garde le fichier GPX chargé et les points déjà utilisés ont une opacité plus faible.
A voir si la fonctionnalité peut être factorisé entre Occtax et Monitoring (et autre du coup) ?

Pour commencer, j'en resterai là. Utiliser des infos attributaires du fichier source pour la titre, la date ou autre peut être sympa. Mais pas essentiel à ce niveau il me semble et risque de rentrer dans un fonctionnement complexe et spécifique, selon le type et le format du fichier source (gpx, geojson, kml...).

A noter enfin qu'il y a une petite correction du plugin Leaflet.FileLayer, en attente de publication de la prochaine version (https://github.com/makinacorpus/Leaflet.FileLayer/compare/1.2.0...master).
