### ISSUE TITLE
Géométrie des sites : plusieurs types possibles au choix ?

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/gn_module_monitoring#136]
Bonjour,

J'ai une question bête : pour la saisie des sites, est-ce qu'il est possible de permettre la saisie de plusieurs type de géométries au choix, comme dans Occtax ? Si oui, comment est-ce vous déclarez le `"geometry_type"` dans la config du protocole ?

Merci !

**Comment by joelclems** [comment]
En l'état non
on peut choisir un type  parmis `"Point","Polygon", "LineString"`

par défaut il est à `"Point"`, 
pour le changer et pourvoir dessiner des lignes par exemple, il suffit d'ajouter dans le fichier `site.json` du module

```
...
"geometry_type": "LineString"
```

**Comment by camillemonchicourt** [comment]
Ce paramètre est défini, au niveau de la configuration du site.
Exemple : https://github.com/PnCevennes/protocoles_suivi/blob/master/oedic/site.json#L2

Mais en effet, ça serait intéressant que ce paramètre puisse prendre plusieurs types, et pas un seul.

**Comment by camillemonchicourt** [comment]
Possible à partir de la 1.0.0 avec  la syntaxe `"geometry_type": "Polygon, Point"` dans le fichier `site.json`.
