### ISSUE TITLE
Condition sur la valeur d'un cd_nom ?

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/gn_module_monitoring#138]
Bonjour, 

Petite question technique : comment est-ce qu'on peut écrire une condition sur la valeur d'un cd_nom ?

Comme indiqué dans la doc du module, les conditions sur des valeurs de nomenclatures fonctionnent très bien :
```
"specific": {
    ...
    "profondeur_grotte": {
    "type_widget": "number",
    "attribut_label": "Profondeur de la grotte",
    "hidden": "({value, meta}) => meta.nomenclatures[value.id_nomenclature_type_site] || {}).cd_nomenclature !== '1'",
    "required": "({value, meta}) => (meta.nomenclatures[value.id_nomenclature_type_site] || {}).cd_nomenclature === '1'"
    }
    ...
}
```

J'aimerai faire la même chose mais avec le cd_nom sélectionné dans les observations (pas trouvé comment faire dans la doc). Quelqu'un aurait une idée ? 

Pour récupérer les cd_nom, j'utilise la config de la doc  : 

```
    "cd_nom": {
        "type_widget": "taxonomy",
        "attribut_label": "Taxon",
        "type_util": "taxonomy",
        "required": true,
        "id_list": "__MODULE.ID_LIST_TAXONOMY"
    },
```

**Comment by joelclems** [comment]
Bonjour Marie

peux tu préciser sur quel champs de quel objet porte la condition ?

**Comment by Splendens** [comment]
Dans le fichier objservation.json, j'ai ça :

```
{
(...)
  "specific": {
    "cd_nom": {
        "type_widget": "taxonomy",
        "attribut_label": "Taxon",
        "type_util": "taxonomy",
        "required": true,
        "id_list": "__MODULE.ID_LIST_TAXONOMY"
    },

    "nombre_de_truc_de_mon_taxon": {
      "type_widget": "number",
      "attribut_label": "Nombre total de truc sur le taxon"
    }
(...)
}
```

Je cherche à rendre obligatoire et/ou cacher le champ "nombre_de_truc_de_mon_taxon" en fonction du cd_nom sélectionné (une condition du style : "required": "({value}) => value.cd_nom == 000000", "hidden": "({value}) => value.cd_nom != 000000" )

**Comment by joelclems** [comment]
si c'est juste un test sur la valeur de cd_nom cela devrait marcher

**Comment by Splendens** [comment]
ça ne fonctionne pas quand le champ du taxon est défini comme ça : 

```
    "cd_nom": {
        "type_widget": "taxonomy",
        "attribut_label": "Taxon",
        "type_util": "taxonomy",
        "required": true,
        "id_list": "__MODULE.ID_LIST_TAXONOMY"
    },
```

Par contre, ça fonctionne quand il est défini comme ça : 

```
    "cd_nom": {
      "type_widget": "datalist",
      "attribut_label": "Taxon",
      "keyValue": "cd_nom",
      "keyLabel": "__MODULE.TAXONOMY_DISPLAY_FIELD_NAME",
      "multiple": false,
      "api": "taxref/allnamebylist/__MODULE.ID_LIST_TAXONOMY",
      "application": "TaxHub",
      "required": true,
      "type_util": "taxonomy"
    } ,
```

Sauf que la définition de ce champ en "datalist" ne récupère pas la liste de taxon en entier :(

**Comment by joelclems** [comment]
est ce que tu cherches à faire des test sur le cd_nom en tant qu'entier ?
ou bien est ce que tu cherche à faire des test sur des valeurs de la ligne de taxref associée à ce cd nom comme par exemple cacher le champs selon le groupe du taxon ? (un peu comme ce qui est fait plus haut avec la nomenclature ou on fait des test sur le champs cd_nomenclature) ?

**Comment by Splendens** [comment]
Dans ce cas, je cherche à tester le cd_nom en tant qu'entier (pour une condition qui s'appliquerait à un seul taxon).

**Comment by joelclems** [comment]
il faudrai que je fasse des test, j'essaye de donner une réponse d'ici ce soir ou demain

**Comment by joelclems** [comment]
J'ai pu tester

dans le cas ou  on utilise le composant datalist, le pb est que la route nous renvoie un maximum de 10 ou 20 taxons
et on a pas la liste complète (sauf si elle est reduite)

il faut donc utiliser composant par defaut

mais celui ci renvoie un dictionnaire avec les info de la ligne concernant le cd_nom

cela donne par exemple si on souhaite ajouter un champs obligatoire seulement dans le cas où on saisit un lynx, pour le fichier `observation.json` du module

```
{
  "specific": {
    "test": {
      "type_widget": "text",
      "attribut_label": "test lynx",
      "hidden": "({value}) => !(value.cd_nom && value.cd_nom.cd_nom == 60612) ",
      "required": "({value}) => value.cd_nom && value.cd_nom.cd_nom == 60612 "
    }
  }
}
```

j'espère que cela répond à ton besoin

**Comment by Splendens** [comment]
Super, c'est exactement ce qu'il me fallait ! Merci beaucoup !
