### ISSUE TITLE
Trigger Monitoring > Synthèse

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#14]
Quand on saisit une observation d'une espèce dans une visite d'un site dans le module de suivi, celle-ci devrait se répercuter dans la Synthèse de GeoNature.
A voir comment cela pourrait être mis en place de manière globale. 
On avait évoqué l'idée de créer un trigger basé sur une vue pour cela.

Cela nécessite aussi peut-être d'ajouter quelques champs en dur dans les tables de ``gn_monitoring`` et/ou quelques paramètres pour pouvoir remplir en dur certaines nomenclatures de la Synthèse.

La question des données d'absence est plus complexe, et peut être mise de côté dans un premier temps. Car une visite sans observation devrait pousser une absence dans la synthèse... Mais la question de l'absence dans la Synthèse étant encore peu investiguée, je mettrai de côté pour commencer.

**Comment by camillemonchicourt** [comment]
Un test a été réalisé de faire une vue par suivi, avec un trigger se basant dessus. Mais un trigger ``after insert`` ne contient pas encore les données dans la table, donc la vue ne remonte pas encore les nouvelles données quand le trigger est exécuté. 

3 possibilités identifiées :

* Import automatique et instantané via trigger
* Import automatique et instantané via API post (Python)
* Import automatique différé via cron (SQL)

Fonction PostgreSQL prenant en entrée un json de données (recordset), qui fera un insert ou un update. Il se base sur l'UUID pour savoir si il doit faire un INSERT ou un UPDATE.
Le json est créé à partir d'une vue par suivi. On propose une vue par défaut à ajuster, enrichir.
Cette fonction PostgreSQL est une base de l'API de post dans la Synthèse (https://github.com/PnX-SI/GeoNature/issues/736).

Cette fonction peut être exécutée en Python (applicatif) à la fin de chaque saisie où on connait l'objet créé ou modifié. Soit en commande ou en CRON et alors on compare le date_update des objets, pas rapport à la date de dernière exécution de la fonction (basée sur un log des crons).

**Comment by camillemonchicourt** [comment]
Bien avancé avec les commits suivants : https://github.com/PnX-SI/gn_module_monitoring/compare/c1a6183a05...b93cfb529f

**Comment by joelclems** [comment]
Les fonctionalité pour la synthese ont été déplacées dans géonature
https://github.com/PnX-SI/GeoNature/issues/736

**Comment by joelclems** [comment]
Il faut retester l'installation c'est un peu chamboulé

**Comment by camillemonchicourt** [comment]
Ajouter https://github.com/PnX-SI/gn_module_monitoring/blob/develop/data/delete_synthese.sql dans l'installation du module ? 
Et/ou passer une partie de ce script dans le SQL de GeoNature ?

**Comment by joelclems** [comment]
bien vu,
je pense qu'on peut le laisser dans le module
