### ISSUE TITLE
[0.2.9] Lenteur sur le chargement des occurrences

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#142]
Version GeoNature: 2.9.1
Version Monitoring : 0.2.9

Bonjour, j'observe depuis quelques temps des lenteurs d'affichage des données sur mes sous-modules monitoring.
Par exemple, pour charger 19 visites d'un site, la requête met 33 secondes à finir de s'exécuter

![image](https://user-images.githubusercontent.com/66769358/152142026-6907be8f-62c9-46de-977d-da16ae7a2c53.png)

Sur quoi s'appuie cette requête ? Qu'est-ce qui pourrait à ce point prendre du temps à charger ? Je trouver que 19 visites c'est quand meme peu :-)

**Comment by maximetoma** [comment]
Pour alimenter, voici la fenêtre Délai via Firefox
![image](https://user-images.githubusercontent.com/66769358/153583945-6f808be9-d711-417e-ad04-f46f47b85d19.png)

**Comment by joelclems** [comment]
bonjour maxime,

je n'arrive pas à reproduire le bug, 
c'est bien la route `object/test/site/1?depth=1`
est ce que tu aurai beaucoup de jdd ?

**Comment by maximetoma** [comment]
Oui c'est bien le type de route: http://192.168.0.26/geonature/api//monitoring/object/comptage_rnmo/site/1199?depth=1

Alors, sur le sous-module en question, je n'ai qu'un seul jeu de données attaché.
Par contre en tout dans mon GeoNature, j'en ai plus de 150

**Comment by joelclems** [comment]
la donnée renvoyée parait normale (de quelques kilos seulement) ?

**Comment by maximetoma** [comment]
oui je pense, 24,4 kB

**Comment by joelclems** [comment]
il n' y a pas de changement majeur dans le backend de monitoring
cela doit venir de geonature mais il reste à trouver comment et comment résoudre le problème
j'essaierai de refaire des test en début de semaine prochaine

**Comment by maximetoma** [comment]
okay pas de soucis, merci beaucoup !
Je ne sais d'où peut venir cette difficulté... Dans ce dit-module, il n'y a "que" 5000 données

**Comment by maximetoma** [comment]
Bonjour, je me permet de relancer la problématique :)
Pour le moment, je n'ai pas réussi à trouver de pistes...

**Comment by camillemonchicourt** [comment]
Si le soucis n'est que dans ce sous-module, il faut que tu analyses ce qu'il a de différent, au niveau de sa structure, de ses données, de ses volumes de données, des droits qui y sont configurés, etc... ?

**Comment by joelclems** [comment]
Bonjour maxime, peux tu nous envoyer la configuration du module ?

**Comment by maximetoma** [comment]
@camillemonchicourt Un comparatif du délai et du nombre de données pour le module entre mon serveur TEST et PROD (qui ont chacun une version différente du module et du nombre de données)


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:\Users\MAXIME~1.TOM\AppData\Local\Temp\msohtmlclip1\01\clip.htm">
<link rel=File-List
href="file:///C:\Users\MAXIME~1.TOM\AppData\Local\Temp\msohtmlclip1\01\clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Module | Données totales du module | Id site | Id visite | Nb visites du site chargé | Nb d'obs du site chargé | Nb d'obs de la visite chargée | Délai d'affichage des visites du   site chargé (s) | Délai d'affichage des   observations de la visite chargée (s)
-- | -- | -- | -- | -- | -- | -- | -- | --
Comptages décadaires [TEST] | 47380 | 1193 | 161543 | 27 | 42 | 7 | 18,49 | 1,11
Comptages décadaires [PROD] | 6100 | 1193 | 212661 | 13 | 16 | 4 | 23,59 | 2,22



</body>

</html>



@joelclems je t’envoie le module par mail, tu as une adresse pour te joindre ? :)

**Comment by joelclems** [comment]
joel.clement

cevennes-parcnational.net

**Comment by joelclems** [comment]
j'ai fait une coquille, c'est
cevennes-parcnational.fr

**Comment by maximetoma** [comment]
C'est prévu mais vu qu'il n'est pas tout à fait prêt, je n'osais pas forcement le mettre tout de suite, et je dois avoir l'aval de mes chefs je pense 🙂

**Comment by joelclems** [comment]
je tombe sur cette erreur à l'installation du module

**Comment by joelclems** [comment]
avec 1 site et 6000 visites ça rame bonne nouvelle j'ai pu reproduire, reste  à creuser pourquoi

**Comment by joelclems** [comment]
[SELECT.txt](https://github.com/PnX-SI/gn_module_monitoring/files/8288139/SELECT.txt)

la requete des visite va chercher les realtions beaucoup trop loin il faut voir comment limiter cela  pour gagner du temps

**Comment by maximetoma** [comment]
> Execution du script synthese.sql (psycopg2.errors.UndefinedTable) relation "gn_monitoring.cor_observation_observer" does not exist LINE 75: FROM gn_monitoring.cor_observation_observer cvo

Ah oui j'ai oublié, j'ai créé une table perso sur le même fonctionnement que cor_visit_observer mais pour les observations. Et la vue de synthèse s'appuie dessus

> la requete des visite va chercher les realtions beaucoup trop loin il faut voir comment limiter cela pour gagner du temps

Il s'agit de la requête principale de Monitoring qui va chercher toute les informations ?

**Comment by joelclems** [comment]
Bonjour maxime, des changements dans les modèles des métadonnées font que l'on va chercher pas mal de chose dont on a pas besoin.

Peux tu essayer d'ajouter la ligne

```
TBaseVisits.dataset = DB.relationship(TDatasets)

```

Juste avant

https://github.com/PnX-SI/gn_module_monitoring/blob/93258408a36d98e11ac98bd223d275bdfcf35e5a/backend/monitoring/models.py#L85-L92

**Comment by maximetoma** [comment]
Okay d'accord !

J'ai rajouté la ligne puis ai rechargé la config mais je n'ai pas d'amélioration du délai 😕

**Comment by joelclems** [comment]
est ce que tu as relancé l'application geonature ?

**Comment by maximetoma** [comment]
Ah oui c'est vrai qu'il faut relancer maintenant !

Ah oui effectivement c'est beaucoup mieux !!!!! :) Merci beaucoup !

**Comment by joelclems** [comment]
quand on change un fichier python il faut relancer l'application

c'est cool si ça marche tu as quel ordre de delai désormais ?

**Comment by joelclems** [comment]
ça reste un peu limte en temps et ça vaudrait le coup d'avoir du serveur side
je garde le ticket ouvert en attendant la release

**Comment by maximetoma** [comment]
Ah d'accord !

Oui encore un petit délai mais cela reste beaucoup plus acceptable que 45secondes ou encore 1 ou 2 minutes

Qu'est ce que tu appelle le "serveur-side" ? C'est plus de côté de notre serveur ou du côté du code de GeoNature ?

**Comment by joelclems** [comment]
C'est par exemple le fat que pour le tableau on aurait pas besoin de charger les 200 visite mais seulement celles des 10 lignes que l'on affiche.

Cela impliquerai vraiment beaucoup de changements, mais on s'affranchirai du nombre de données présentes en base

**Comment by maximetoma** [comment]
Ah oui effectivement, ça vaudrait peut être le coup... mais si c'est pas trop contraignant, ou alors pour un grosse MAJ de Monitoring....

Ce fonctionnement existe actuellement sur Occtax ?

**Comment by joelclems** [comment]
oui je dirai que c'est déjà le cas pour occtax

**Comment by camillemonchicourt** [comment]
Oui c'est comme ça que fonctionne Occtax

**Comment by maximetoma** [comment]
Okay merci :)
Du coup à voir dans quelles mesures on peut l'adapter à Monitoring effectivement....

**Comment by camillemonchicourt** [comment]
A priori amélioré suite aux évolutions dans la 0.4.1.
