### ISSUE TITLE
[0.2.9] Bug d'affichage des observateurs [object] [Object]

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#143]
**Version**
0.2.9

**Description du bug**
Affichage "[object] [Object]" au lieu des observateurs. Apparue depuis la dernière MAJ 0.2.9 / GeoNature 2.9

**Comportement attendue**
![image](https://user-images.githubusercontent.com/66769358/153554854-7208f946-afea-45ed-a434-87f9f98ce789.png)
Les observateurs sont bien enregistrés en base et s'affichent correctement lors de l'édition. Mais l'affichage en dehors de l'éditeur retourne "[object] [Object]"

**Comment by joelclems** [comment]
pour patcher en attendant un correctif

dans config/monitoring/generic/visit.json
changer `observers` en 

```
    "observers": {
      "type_widget": "datalist",
      "attribut_label": "Observateurs",
      "api": "users/menu/__MODULE.ID_LIST_OBSERVER",
      "application": "GeoNature",
      "keyValue": "id_role",
      "keyLabel": "nom_complet",
      "type_util": "user",
      "multiple": true,
      "required": true
    },

```

**Comment by maximetoma** [comment]
Okay merci beaucoup, ça marche :)

**Comment by camillemonchicourt** [comment]
Corrigé dans la 0.2.10.
