### ISSUE TITLE
[0.2.9] Dataset par défaut non-sélectionné

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#145]
**Version**
0.2.9

**Description du bug**
S'il y a qu'un seul jeu de données renseigné sur un sous-module, celui-ci **n'est plus** sélectionné par défaut lors d'une nouvelle saisie. Ce fut le cas sur la version 0.2.7 que j'avais jusqu'à présent

**Comportement attendue**
![image](https://user-images.githubusercontent.com/66769358/153566673-25eee325-8943-431c-a6a6-1d0f2c7f24c9.png)

**Comment by joelclems** [comment]
pour patcher en attendant un prochaine release (qui attend GN2.9.2 avec angular.12)

attention de bien être en GN>2.9

dans 
`config/monitoring/generic/visit.json` changer id_dataset en 

```
"id_dataset": {
      "type_widget": "datalist",
      "attribut_label": "Jeu de données",
      "type_util": "dataset",
      "api": "meta/datasets",
      "application": "GeoNature",
      "keyValue": "id_dataset",
      "keyLabel": "dataset_shortname",
      "params": {
        "orderby": "dataset_name",
        "module_code": "__MODULE.MODULE_CODE"
      },
      "required": true
    },
```

**Comment by maximetoma** [comment]
C'est niquel ! Merci beaucoup :)

**Comment by joelclems** [comment]
je laisse ouvert jusqu'à la prochaine release

**Comment by camillemonchicourt** [comment]
Corrigé dans 0.2.10
