### ISSUE TITLE
Liste / Champs et filtres

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#15]
Pour l'ergonomie et la lisibilité, dans les listes, je mettrai les titres des colonnes au-dessus des champs de filtre.

**Comment by joelclems** [comment]
Je galère vraiment avec les ngx-datatable, je me demande si il ne faudrait pas essayer autre chose (par ex https://www.primefaces.org/primeng/showcase/#/table/filter)

**Comment by camillemonchicourt** [comment]
Oui en effet ça semble intéressant.
Mais si c'est un chantier, on peut garder pour une prochaine version
