### ISSUE TITLE
Saisie observation : retour à la visite

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_monitoring#152]
Lors de la saisie d'une observation, si on est pas en mode "enchainer les saisie", on es redirigé vers la page détail de l'observation.
Je trouve qu'il serait intéressant de pouvoir être redirigé vers la fiche de la visite
Je propose un paramètre au niveau de `observation.json` : `redirect_to_visit: true/false`
Est-ce que ça vous semble cohérent ?

**Comment by camillemonchicourt** [comment]
Fait dans la version 0.3.0, compatible avec GeoNature 2.10 (ou plus).
