### ISSUE TITLE
Affichage des images des sous-modules si recompilation

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#16]
Quand on installe un sous-module dans le module MONITORING, son image n’apparaît pas sur l'accueil du module. 
Elle n’apparaît qu'après avoir recompilé GeoNature, par exemple en lançant ``geonature update_module_configuration monitorings``.

Si on modifie l'image d'un sous-module, il faut aussi relancer la compilation pour que le changement soit pris en compte.

**Comment by joelclems** [comment]
on peut rajouter l'execution de la commande `geonature update_module_configuration monitorings` à l'installation d'un sous-module

et documenter de lancer la commande `geonature update_module_configuration monitorings` en cas de changement d'image.
