### ISSUE TITLE
Sélection multiple de nomenclature ou widget multiselect

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#163]
Bonjour, 

Je vois que sur les observateurs notamment, on peut définir le booléen "multiple" pour permettre les sélections multiples. 

Coté nomenclatures, ou widgets "liste/select", est-ce qu'il est possible et/ou prévu d'avoir un multiselect ? J'ai teste pour le moment sur un select en passant le widget en multiselect, ca semble presque fonctionner

**Comment by joelclems** [comment]
Bonjour donovan
je ne sais ce qu'il en est du composant nomenclature, mais tu peux essayer avec les datalist

```
"nomenclatures_determination_method": {
    "type_widget": "datalist",
    "attribut_label": "Méthodes de détermination",
    "api": "nomenclatures/nomenclature/METH_DETERMIN",
    "application": "GeoNature",
    "keyValue": "id_nomenclature",
    "keyLabel": "label_fr",
    "multiple": true,
    "data_path": "values",
    "type_util": "nomenclature",
    "required": true,
    "default": {
        "cd_nomenclature": "1"
    }
},

} 
```

**Comment by DonovanMaillard** [comment]
Merci beaucoup joel, ça marche parfaitement !

**Comment by TheoLechemia** [comment]
```
      "id_nomenclature_behaviour": {
        "type_widget": "nomenclature",
        "attribut_label": "Comportement",
        "code_nomenclature_type": "OCC_COMPORTEMENT",
        "type_util": "nomenclature",
        "required": true,
        "value": 545,
       "multi_select": true
}
```
devrait marcher aussi si tu veux garder un composant de type nomenclature

**Comment by DonovanMaillard** [comment]
Super merci, je vais tester en effet.Bizarre d'avoir une variable multiple et une variable multi_select, je ferai un petit + dans la doc quand j'aurai testé. Idem pour les valeurs "default" et "value" par exemple selon le widget utilisé :)
