### ISSUE TITLE
Valeur par défaut pour le champs Taxon de l'onglet Observation

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/gn_module_monitoring#165]
Bonjour à tous,

Je suis en train de développer un sous module pour le suivi des marmottes du programme Sentinelle du Climat.
La partie Observation permet de saisir le nombre de marmottes observées toutes les 10 minutes.

Dans ce cas, le champs taxon est inutile car on n'observe qu'une seule espèce. Je ne l'ai donc pas mis dans ma configuration, mais il apparait quand même car je pense qu'il est obligatoire. J'ai donc rajouter cela en suivant le fichier d'aide : 

    "cd_nom": {
      "type_widget": "taxonomy",
      "attribut_label": "Taxon",
      "type_util": "taxonomy",
      "hidden": false,
      "required": true,
      "id_list": "__MODULE.ID_LIST_TAXONOMY"   
    }

Cela permet de configurer ce champs obligatoire.

L'idée serait d'initialiser ce champs à "Marmotte" et de le cacher pour qu'il ne soit pas visible pour l'utilisateur. Pas de soucis pour le cacher, c'est fonctionnel. Mais par contre, impossible de configurer une valeur par défault. J'ai essayé plusieurs syntaxes mais sans succès. Et pas d'infos dans la doc concernant cette initialisation (j'ai aussi essayé de créer une liste taxhub avec une seule espèce, mais cela ne fonctionne pas non plus). 

Merci d'avance pour vos idées !

**Comment by cen-cgeier** [comment]
Tu le sais sûrement mais le champ `"cd_nom": { ...  }` est défini par défaut dans `gn_module_monitoring/config/monitoring/generic` comme beaucoup d'autres variables. C'est pour ça qu'il apparaît dans le formulaire sans qu'il est été définit dans ta configuration. Si son format ne te convient pas, tu peux partiellement ou totalement redéfinir cette variable pour l'adapter à tes besoin (même si je crois que ce n'est pas toujours très conseillé).

Dans ton cas, si j'ai bien compris ce que tu essaie de faire, ça à déjà été fais dans le module `oedic` et ceci devrait convenir à tes besoins :
```    
"cd_nom": {
      "type_widget": "text",
      "attribut_label": "cd nom",
      "type_util": "taxonomy",
      "value": 61143,
      "hidden": true
    }
```

**Comment by JeromeMaruejouls** [comment]
Merci beaucoup @cen-cgeier ! En fait, je ne voulais pas modifier la conf par défault car je ne voulais pas toucher aux autres sous modules.
Mais ta solution fonctionne : j'avais testé en écrivant le nom latin dans "value" sans vraiment réfléchir ! Merci !

**Comment by cen-cgeier** [comment]
En effet, ce n'est pas une bonne idée de modifier les configurations par défaut. Mais si tu redéfinis la variable `"cd_nom" : { ... }` dans le fichier `observation.json` de ton sous-module en cours de création, cette redéfinition sera valable uniquement pour le sous module concerné. Ça s'apparente à une surcouche.

>j'avais testé en écrivant le nom latin dans "value"

En effet, ne pas confondre la valeur stocké en bdd (le cd nom) et le label renvoyé par l'interface graphique (le nom latin)

**Comment by JeromeMaruejouls** [comment]
Exactement. Tout fonctionne parfaitement avec le paramètre "value". Merci !
