### ISSUE TITLE
[0.2.10] Comment faire refonctionner les modules déjà alimentés en données ? 

### ISSUE THREAD

**Issue by Splendens** [PnX-SI/gn_module_monitoring#166]
Bonjour,

J'ai fait une migration de GN 2.7.5 + Monitoring 0.2.7 vers GN 2.9.2 + Monitoring 0.2.10

Je n'ai pas eu de soucis particuliers lors de la mise à jour, qui a eu l'air de s'être bien passer, sauf pour ce qui est du fonctionnement des protocoles déjà existant dans monitoring.

Les protocoles déjà installés et contenant des données ne sont pas récupérés par GN  : pas d'images dans la listes des protocoles de suivis (la commande process_img n'y change rien), et après ouverture d'un protocole, la carte s'affiche mais le formulaire n'est pas chargé.

Voilà les logs de GN :

```
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 19, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/config.py", line 22, in get_config_api
    return get_config_frontend(module_code, force=True)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/config/repositories.py", line 241, in get_config_frontend
    config = dict(get_config(module_code, force))
TypeError: 'NoneType' object is not iterable

```

Pour le test, j'ai réinstallé un de mes protocoles, et l'installation passe sans problème, puis le protocole de suivi fonctionne bien. 
Une idée pour refaire fonctionner les autres protocoles ? Je ne peux évidemment pas tout désinstaller puis tout réinstaller vu qu'il y a déjà des données saisies. 
Merci d'avance si quelqu'un a une piste !

**Comment by Splendens** [comment]
Je vais me répondre à moi-même : c'est la commande pour recréer les liens symboliques qui a sauté dans cette histoire :

``` rsync -av /home/`whoami`/gn_module_monitoring_old/config/monitoring/ /home/`whoami`/gn_module_monitoring/config/monitoring/ --exclude=generic```

Une fois les liens récréés, tout fonctionne beaucoup mieux !

**Comment by camillemonchicourt** [comment]
Merci pour ce retour.
C'est à ajouter dans la doc ou dans un script ?

**Comment by Splendens** [comment]
La commande est bien dans la doc, le problème était que rsync n'était pas installé sur le serveur.
A la rigueur, il faudrait peut-être ajouter l'installation de rsync lors de l'install de monitoring ?

**Comment by camillemonchicourt** [comment]
Je vois pas pourquoi on imposerait l'usage de ``rsync``, alors qu'un ``cp`` suffit.
Je serai plutôt pour harmoniser la doc avec les pratiques de copie que l'on utilise habituellement sur GeoNature.

**Comment by joelclems** [comment]
c'était pour copier tous les liens sauf generic qui lui est un dossier versionné (avec l'option exclude) je n'ai pas trouvé l'équivalent avec cp
