### ISSUE TITLE
Transmettre :module_code vers export_csv.sql

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/gn_module_monitoring#168]
Bonjour,
en créant un nouveau petit module de suivi, je me suis dis qu'on transmettait l'argument "module_code" au fichier `synthese.sql` mais pas au fichier `export_csv.sql` lorsqu'il existe. Ça m'a posé question ... ^^'
Est-ce voulu ? Est-il envisagé de transmettre cet argument à ces 2 fichiers lorsqu'il est présent ?

J'ai tenté l'adaptation sur mon instance mais je ne parviens pas encore à transmettre l'argument lorsque celui-ci compose le nom de la `view` par le biais de SQLAlchemy.

**Comment by camillemonchicourt** [comment]
Intégré dans la version 0.3.0, compatible avec GeoNature 2.10 (ou plus).
