### ISSUE TITLE
Questions paramétrage .json

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_module_monitoring#170]
Bonjour, 

J'ai plusieurs questions par rapport aux paramétrage des .json pour le sous-module STOM:
- le paramètre description_field_name: il retranscrit une variable au sein de la BDD type texte (base_site_name) en date quand le champ est rempli par un numéro, ce qui est notre cas pour les numéros des points d'écoute, est-ce qu'il est possible de contourner cette retranscription pour y faire afficher le numéro ? 
-Est-ce qu'il est possible d'enlever le calcul en ha pour les groupes de sites avec la fonction b_draw_sites_group ? 
- Je souhaite faire afficher la variable altitude_min au sein de display_list, cependant la variable ne semple pas être définis comment et ou est-ce qu'il est possible de la définir pour faire l'affichage des altitudes pour mes points d'écoute ? 

Merci d'avance pour le retour, 

Cléa

**Comment by camillemonchicourt** [comment]
Salut, tu utilises la version partagée du sous-module STOM (https://github.com/PnCevennes/protocoles_suivi/tree/master/stom) ?

**Comment by Chrispnv** [comment]
Oui c'est celle-là avec quelques modifications sans toucher à la structure, juste affichage de certaines variables en plus ou en moins.

**Comment by TheoLechemia** [comment]
Bonjour Cléa,

Je viens de tester de remplir le champs `description_field_name` et j'ai bien un nombre en BDD. Tu regardes ta base avec quoi ? 
Je n'ai pas compris l'affichage du "calcul en hectare". Tu as ça ou, à quelle étape ? (Pour info je suis sur la branche develop de GeoNature et monitoring ou j'ai fait une évolution pour calculer la géometrie des "groupe de sites" côté backend)

**Comment by Chrispnv** [comment]
![Capture](https://user-images.githubusercontent.com/10419547/169235355-9bc34adf-9697-4574-9198-3bffffc3e91d.PNG)

Bonjour, je vous remercie pour vos retours, 

pour répondre aux différentes questions ci-dessus une capture. Du fait du "b_draw_sites_group": true sous le site_group.json, il y a l'affichage des hectares sur chaque groupe de site, je ne trouve pas dans la doc comment les enlever ou avec les différentes exemples de sous-module. 

Et comme vous pouvez le voir le nom de mon point d'écoute est 1, ce qui rend à l'affichage 01/01/2001.

**Comment by TheoLechemia** [comment]
Hum bizarre, je n'ai pas ça pour les "hectare"... Tu peux regarder sur demo.geonature.fr/geonature. Je l'ai déployer hier 
Ok pour les dates, j'avais pas compris ou tu avais cette affichage. J'ai bien le même bug, je regarde

**Comment by TheoLechemia** [comment]
Est-ce que tu peux m'envoyer ton dossier "stom" par mail pour que je regarde ?

**Comment by Chrispnv** [comment]
Oui bien sur, je fais ça tout de suite.
