### ISSUE TITLE
Import de données

### ISSUE THREAD

**Issue by Chrispnv** [PnX-SI/gn_module_monitoring#174]
Bonjour, 

Je souhaite réaliser un import de données dans le sous-module STOM des années 2020 et 2021 avant l'utilisation directement par les agents. Dans un premier temps j'ai réalisé un import sous la table t_base_sites de tous mes points (étape réussite), puis j'ai voulu compléter en remplissant la t_base_visit. Via l'interface web, il est bien marqué le nombre de visites du champs nb_visit mais quand je clique sur le site je n'ai aucune des visites que j'ai rentrée en BDD. Je n'ai pas eu de message d'erreurs, comment est-ce que c'est possible ? Est-ce que c'est parce que je n'ai pas rempli encore les champs complémentaire en json propre à ce sous-module et juste la table t_base_visit du module monitoring ? 
![image](https://user-images.githubusercontent.com/10419547/171816506-fa85fe10-07da-4af9-b928-a3ad82bf924b.png)
![image](https://user-images.githubusercontent.com/10419547/171816551-1e9d11b0-1d51-48c6-833d-cb87bc28d70c.png)

Cléa

**Comment by joelclems** [comment]
Bonjour, il faut aussi renseigner la table t_visit_complement pour que les visites soient prise en compte (quitte à laisser le champs data  vide mais il faut au moisn l'id_base_site renseigné)

**Comment by joelclems** [comment]
pour info le nombre de visit est ubn champs calculé (column_property, un peu comme une vue qui va compter les visites) avec la table t_base_visit, mais les visites sont chargées avec leur complément

**Comment by Chrispnv** [comment]
Ok parfait, merci beaucoup des informations!
