### ISSUE TITLE
reset form sur liste

### ISSUE THREAD

**Issue by MoulinZ** [PnX-SI/gn_module_monitoring#177]
Je cherche à faire un formulaire d'observations dont les infos à saisir dépendent d'un choix en liste déroulante. 
Tout fonctionne avec les `hidden` et `required`, mais le risque c'est que si l'utilisateur commence à saisir des infos et finalement change de choix de base, ses infos précédemment sélectionnées sont enregistrées sans qu'il ne le voit. Je voulais donc réinitialiser le form au changement de choix de base. 
Problème : le paramètre `"change"` du json s'active à n'importe quel changement, et je n'arrive pas à cibler la modification d'un champs spécifiquement. J'ai fait plusieurs essais de ce style :
```
"change": [
      "({objForm, meta}) => {",
      "let zero = {",
      "cd_nom: null,",
      "activite: null,",
      "effectif_alim: null,",
      "effectif_repos: null,",
      "nombre: null",
      "};",
      "if (objForm.get('choix').valueChanges) {",
      "objForm.patchValue(zero)",
      "});",
      "}",
      ""
      ]
```

sans succès... dès qu'on saisie quelque chose dans un des champs concerné il est réinitialisé. Y a t'il une solution ?

**Comment by joelclems** [comment]
idealement il faudrait que l'on puisse accéder à old_value, new _value dans la fonction change mais en l'état ce n'est pas le cas
peut être une piste ci dessous  on l'on garde en memoire la valeur de choix dans old_choix pour pouvoir détecter un changement du champs `choix`
```
...
if((!!objForm.old_choix) && (objForm.value.choix != objForm.old_choix)) {
 objForm.patchValue(zero)
}
objForm.old_choix = objForm.value.choix;
...
```

**Comment by joelclems** [comment]
Pourras tu ajouter un commentaire à l'issue avec la fonction change qui fonctionne ?

**Comment by MoulinZ** [comment]
oui bien sûr, la voici, j'ai simplement ajouté tes lignes :
```
"change": [
      "({objForm, meta}) => {",
      "let zero = {",
      "cd_nom: null,",
      "activite: null,",
      "effectif_alim: null,",
      "effectif_repos: null,",
      "nombre: null",
      "};",
      "if((!!objForm.old_choix) && (objForm.value.choix != objForm.old_choix)) {",
      "objForm.patchValue(zero)",
      "}",
      "objForm.old_choix = objForm.value.choix;",
      "}",
      ""
      ]
```

Me reste un problème de violation de contrainte NOT NULL de cd_nom comme exprimé dans l'issue #93 mais je vais rouvrir une issue sur le sujet si je ne trouve pas la solution.
