### ISSUE TITLE
Affichage partiel des espèces observées

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#18]
J'ai créé une observation d'espèce dans une visite d'un sous-module. L'espèce est bien renseignée :
 
![image](https://user-images.githubusercontent.com/4418840/84001952-ebbd5180-a967-11ea-95c7-c277c3d9a727.png)

Cependant elle n'est ensuite pas affichée dans la liste des observations de la visite : 

![image](https://user-images.githubusercontent.com/4418840/84001884-d21c0a00-a967-11ea-99e4-6253d0dfc0e0.png)

Ni dans la fiche de l'observation : 

![image](https://user-images.githubusercontent.com/4418840/84002100-2b843900-a968-11ea-9638-6d6ff6ef8608.png)

**Comment by joelclems** [comment]
Salut camille, comment est ton fichier observation.json ?

**Comment by joelclems** [comment]
Pour l'affichage de l'espece, je récupère le champs `nom_vern` à partir du `cd_nom` avec une requête à `TaxHub` : `geonature/api/monitorings/util/taxonomy/60612`

Sur votre serveur le champs `nom_vern` est `null`.
C'est la nouvelle version de taxref qui fait ça?

On peut prendre aussi `nom_complet`

**Comment by camillemonchicourt** [comment]
En effet, le ``nom_vern`` n'est pas renseigné pour tous les taxons. Mais il n'y a pas de différence de structure avec la nouvelle version de Taxref normalement.
Peut-être faut-il utiliser un autre champs, tout le temps renseigné, ou sinon je crois qu'on concatène 2 champs dans Occtax ans co.

Mon fichier ``observation.json`` : 

```json
{
  "display_properties": [
    "cd_nom",
    "nb_0_5",
    "nb_5_10",
    "nb_sup_100m",
    "comments"
  ],
  "specific": {
    "cd_nom": {
      "type_widget": "taxonomy",
      "attribut_label": "Espèce",
      "type_util": "taxonomy",
      "required": true,
      "idComponent": "100"
    },
    "nb_0_5": {
      "type_widget": "number",
      "attribut_label": "Effectif 0'-5'"
    },
    "nb_5_10": {
      "type_widget": "number",
      "attribut_label": "Effectif 5'-10'"
    },
    "nb_sup_100m": {
      "type_widget": "number",
      "attribut_label": "Effectif au delà de 100m"
    },
    "comments": {
      "attribute_label": "Commentaire"
    }
  }
}
```

**Comment by joelclems** [comment]
Si nom_vern n'est pas présent, on prend lb_nom.

**Comment by camillemonchicourt** [comment]
Merci
