### ISSUE TITLE
Problèmes de performance de chargement du module

### ISSUE THREAD

**Issue by ca-rock** [PnX-SI/gn_module_monitoring#181]
Bonjour,

Je vous fait part d'un retour d'expérience au cas où l'un.e d'entre vous rencontrerait le même problème que moi. 
J'ai une installation de GeoNature + module monitoring sur une VM. Le temps d'affichage de la liste des modules ainsi que la liste des sites des sous modules étaient très longs (~30s).  
Il s'avère que c'était au moins ces deux requêtes API qui étaient longues :
- /geonature/api/monitorings/object/mon_module/module
- /geonature/api/occtax/releves
Car leur coût apparent calculé par postgresql était élevé (beaucoup de jointures), et que par défaut le jit était actif sur cette machine (https://docs.postgresql.fr/11/jit-configuration.html).
Il faut désactiver le jit :
```
alter database geonature2db set jit=off;
```
Il faut ensuite redémarrer postgresql et l'API.
```
systemctl restart postgresql
systemctl restart geonature
```
Et le temps de chargement redevient normal.

**Comment by camillemonchicourt** [comment]
Intéressant merci.
Serait-ce quelque chose à faire par défaut lors des installations de GeoNature ?

**Comment by gildeluermoz** [comment]
J'ai testé cette solution et la différence est flagrante pour la route` ../api/monitorings/modules`
Avec `alter database geonature2db set jit=on;` temps de réponse de la requête 3951ms
Avec `alter database geonature2db set jit=off;` temps de réponse de la requête 88ms
Pas de différence significative par contre sur les autres routes du module ; lors du chargement de la liste des groupes de sites par exemple (113 groupes de sites)
