### ISSUE TITLE
Icone du marker leaflet non trouvé

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_monitoring#187]
En prod, l'icone du marker est cherché à la racine du serveur et renvoie une 404. Du coup cela affiche l'image d''une "404" sur la carte et le site est difficilement pointable.
Personne n'a ce soucis ?

**Comment by joelclems** [comment]
à ce sujet j'ai proposé un commit dans geonature pour récupérer le marker à la racine (aussi pour que les markers marchent bien dans geoman)

https://github.com/PnX-SI/GeoNature/pull/2099/files

**Comment by TheoLechemia** [comment]
Ok merci.
Par contre l'intégration de Geoman n'est pas encore planifié dans GeoNature (il faudrait reprendre toute la partie leaflet -draw).
Est ce que tu peux faire 2 PR séparées du coup ?

**Comment by joelclems** [comment]
Oui bien sur, je peux faire 2 PR séparées
J'utilise geoman dans un module et j'avais fait cette modifcation pour faire marcher les markers dans geoman aussi.
Je n'ai pas réussi à installer geoman depuis le module comme on fait classiquement (https://github.com/PnX-SI/GeoNature/pull/2099#issuecomment-1300424364) d'où cette PR pour mettre geoman dans les dépendances js de geonature.

**Comment by joelclems** [comment]
- marker https://github.com/PnX-SI/GeoNature/pull/2114
