### ISSUE TITLE
[0.3.0] installation avec Geonature 2.9.2 - Class UserList introuvable

### ISSUE THREAD

**Issue by metourneau** [PnX-SI/gn_module_monitoring#189]
Bonjour,

J'essaie d'installer la version 0.3.0 sur un Géonature 2.9.2, mais lors de l'installation il ne trouve pas la class UserList dans pypnusershub.db.models
 `cannot import name 'UserList' from 'pypnusershub.db.models' (/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pypnusershub/db/models.py)
cannot import name 'UserList' from 'pypnusershub.db.models' (/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/pypnusershub/db/models.py)

Error while installing GN module .The process returned:
        Error during module MONITORINGS installation`

Apparemment geonature installe la version 1.5.9 de pypnusershub qui ne contient pas cette class.
Cette version est donc a installer avec un Géonature 10+?

**Comment by camillemonchicourt** [comment]
La 0.3.0 n'est disponible qu'avec GeoNature 2.10 ou plus.
C'est spécifiée avec la première phrase des notes de cette version 0.3.0 : 

> Nécessite la version 2.10.0 (ou plus) de GeoNature.
