### ISSUE TITLE
[Sous modules] Permettre de sélectionner plusieurs listes de taxons de Taxhub

### ISSUE THREAD

**Issue by JeromeMaruejouls** [PnX-SI/gn_module_monitoring#209]
Bonjour à tous.

Y a t il un moyen pour permettre de sélectionner des taxons dans plusieurs listes Taxhub ? J'ai l'impression que l'on ne peut pointer que sur une seule liste actuellement.

Sinon comment procéderiez vous ? Je pensais créer une liste regroupant tous les taxons de mes deux listes, mais ce n'est clairement pas la meilleure méthode !

Merci :)

**Comment by camillemonchicourt** [comment]
Non ce n'est pas prévu car il faudrait une route TaxHub permettant d'agréger les taxons de plusieurs listes, ce qui n'est pas prévu actuellement.

Donc il faudrait d'abord faire cette évolution au niveau de TaxHub pour commencer, puis le répercuter dans Monitoring.

**Comment by JeromeMaruejouls** [comment]
Ok merci, je vais me créer une liste personnalisé pour répondre au besoin alors. Merci :)
