### ISSUE TITLE
Ergonomie - Renvoyer sur la page détail après la création d'un objet

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/gn_module_monitoring#22]
Le comportement actuel est le retour à la liste

**Comment by camillemonchicourt** [comment]
Oui ça serait beaucoup plus fluide pour la saisie

**Comment by camillemonchicourt** [comment]
C'est surtout pertinent sur les visites car on enchaîne ensuite sur une observation.

Pour les sites et les observations c'est pas si mal d'aller sur la liste après création ? 
Mais pas idéal d'avoir des comportements variables.

**Comment by joelclems** [comment]
On peut rajouter un bouton valider et ajouter suite cf #28 et aller au détail quand on valide
