### ISSUE TITLE
Champs - Ajouter définition affichable en tooltip

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#23]
Ajouter la possibilité d'indiquer dans les json de configuration des sous-modules, une définition d'un champs qui est affichée en tooltip, en tant qu'aide à la saisie, au niveau du champs, au survol d'un bouton "?"

**Comment by joelclems** [comment]
J'ai fait ça pour pouvoir afficher le nom entier quand il est tronqué. On peut rajouter une définition.

**Comment by camillemonchicourt** [comment]
Oui c'est nickel, l'idée est d'ajouter la définition au survol du champs ou d'une petite icône "?" à côté des champs qui ont une définition.

**Comment by joelclems** [comment]
L'icone apparait s'il y a une définition, pour les tableau et pour les détails.

S'il n'y a pas de définitions, on garde e tooltip pour les tableau en cas de nom coupé.

**Comment by camillemonchicourt** [comment]
C'est surtout au niveau du formulaire de saisie que l'affichage de la définition est utile, en aide à la saisie.

**Comment by joelclems** [comment]
il faudra changer le composant dynamic form dans GN.

**Comment by joelclems** [comment]
Fait pour à peu près tous les composant du dynamic form, à compléter au besoin mais la fonctionalité est bien là.
