### ISSUE TITLE
Pouvoir grouper des sites

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#24]
Plusieurs protocoles de suivi semblent nécessiter de pouvoir grouper des sites (des sites de types points dans un circuit, des sites dans des sous-ensembles territoriaux...).

On propose avec @amandine-sahl d'ajouter une table des groupes de sites (``gn_monitoring.t_sites_groups``).

2 modélisations possibles : 

- Table des groupes de sites spécifique au module Monitoring : 
![monitoring_groups](https://user-images.githubusercontent.com/4418840/84284292-4909fc00-ab3c-11ea-8e26-fad187c8e609.png)

- Table des groupes de sites au niveau de la partie gn_monitoring du cœur de GeoNature : 
![monitoring_groups2](https://user-images.githubusercontent.com/4418840/84284544-a0a86780-ab3c-11ea-95d1-efe3e551f928.png)

La deuxième solution nous semble plus pertinente et pérenne. 

Au niveau de la table ``gn_monitoring.t_sites_groups``, on aurait un nom, une geom, une description, un id_module.

**Comment by RomainBaghi** [comment]
Les sites et groupes de sites seraient reliés à quel niveau ? 
Chaque site aurait un "groupe de site" parent facultatif ?
Même pas sûr qu'un champ geom soit nécessaire, par contre pour nous c'est très pertinent que chaque groupe de site ait son jdd. à voir comment cela peut être implémenté.

**Comment by camillemonchicourt** [comment]
Oui c'est ça, chaque site pourrait facultativement être rattaché à un groupe de sites pour un sous-module donné. Une géométrie peut être utile je me dis, facultatif. 
Pour les JDD c'est un autre sujet. Si on force le JDD au niveau du groupe alors ça devient très spécifique. A creuser par ailleurs que d'avoir des JDD différents pour un même sous-module.

**Comment by RomainBaghi** [comment]
J' ouvre un autre ticket pour la question des jdd ?

**Comment by RomainBaghi** [comment]
Dans l'idée, il faudrait qu'un jdd soit créé que si l'on utilise un groupement de sites (facultatif), sinon c'est le jdd par défaut du sous-module qui est utilisé.

**Comment by camillemonchicourt** [comment]
Oui sujet des JDD à traiter par ailleurs car pas forcément lié au sujet des groupes de sites. 
A traiter plus globalement et de manière plus générique. 
Car le fonctionnement que tu proposes ici t'est spécifique. Donc à voir comment permettre cela de manière générique.

**Comment by camillemonchicourt** [comment]
OK pour les groupes de site, sur la base de la deuxième proposition de modélisation.

On ajoute un paramètre au niveau du sous-module, pour définir si il est concerné par les groupes de site ou non. 

Pour le moment on se limite au nom du groupe de sites, un UUID. 
A voir plus tard pour un geom, ou le rendre optionnel, car la géométrie d'un groupe de sites peut être l'agglomération des géométries des sites qui le composent.

Les groupes de sites sont un filtre de la liste des sites.
A voir où et comment on gère et créé les groupes de sites.

**Comment by RomainBaghi** [comment]
Au niveau ergonomique, après discussion avec joel et amandine, on voit ça comme un niveau hiérarchique optionnel en plus de celui des sites. Il sera activé ou non pour le sous-module et s'il est activé, la page d'accueil ne présentera pas directement les sites mais les groupements de sites avec la même organisation : dans le tableau la liste des groupements de sites et par contre sur la carte, l'ensemble des sites.
Lorsqu'on clique sur un site sur la carte cela souligne dans le tableau le groupement de sites auquel il appartient et inversement lorsqu'on clique sur une ligne du tableau cela met en évidence sur la carte l'ensemble des sites.

Lorsqu'on sélectionne un groupement de sites on arrive sur l’interface avec la liste des sites concernés et ici ce serait intéressant d'avoir un raccourci pour saisir une visite sur un site directement depuis cette interface (peut être un bouton sur chaque ligne du tableau).

Pour la question des jdd j'ouvrirai un nouveau ticket.

**Comment by camillemonchicourt** [comment]
A creuser car je pense que ce n'est pas très intuitif ni compréhensible pour l'utilisateur d'avoir des modules qui ont une logique de fonctionnement différente tout en ayant une interface très similaire.
Parfois la première page listerait des sites et leur carte; et parfois on listerait des groupes de sites avec une carte des sites

**Comment by joelclems** [comment]
On avait déjà réfléchi à grouper les sites pour le module chevêche où les points sont réalisés par circuits, et on en a tiré quelques idées.

# Les besoins

Tout d'abord, il faut voir les besoins auxquels répondent les groupes de sites:

* Si le seul champs des groupes de sites est le nom du groupe,
la solution la plus simple serait de rajouter un champs `nom_groupe` aux sites et de filtrer les sites selon ce champs (et de proposer une liste déroulante  pour les filtres de `nom_groupe`).

* Mais ça serait bien aussi d'avoir une uuid avec le groupe de site pour pouvoir proposer des médias associés, par exemple un pdf contenant la description et la carte du circuit associé au groupe de sites (besoin pour le module chevêches).

* Il peut aussi y avoir des cas ou des sites appartiennent à des groupes et d'autres sont isolés (cas aussi du module chevêche).

# Hiérarchie

Je proposerai une hiérarchie transverse plutôt que directe entre les groupe de site et les sites
avec la possibilité d'associer ou non des sites à un groupe de site
(cf variable `tree` dans `config.json`): 

```
tree: {
    module: {
        site: {
            visit: {
                observation: {}
            },
        },
        goupe_site: {} // cette ligne seule permettrai d'ajouter la notion de groupe de site au module
    }
}
```

où les groupes de sites sont au même niveau que les sites.

# Association groupes de sites / modules

Est ce qu'un groupe de sites est associé à un seul module, ou est ce qu'il peuvent être commun à plusieurs modules.

Il y a en effet la possibilité d'associer un site à plusieurs modules (tout en lui assignat des informations propres à chaque module avec la table `t_site_complement`) (cette possibilité n'a pas été éprouvée pour l'instant).

Fait-on de même avec les groupes de site?

# Frontend

## Général
Quelques propositions du côté front:

* La page d'accueil du module présenterai le tableau des sites et celui des groupes de sites dans un onglet à côté.

* Un click sur une ligne du tableau du groupe de site permet de filtrer les sites associés à ce groupe et de visualiser l'ensemble de points du groupe (possibilité de zoom sur ces points)

* ?? On pourrait assigner une couleur par groupe de site pour visualiser les groupe (comment faire en cas de grand nombre de groupes)

* Depuis le tableau des groupes de sites, il y a un boutton ajouter groupe de site pour en créer des nouveaux *(comme pour tous les objets)*

* Quand on crée un site, on peut lui assigner un groupe existant.

## Ergonomie des saisies

Pour gagner du temps dans la saisie ecnchaînée de sites ou de visites (quand il y a une logique de circuit associée au groupe), on peut donner la possibilité de garder des valeurs de champs pour ne pas avoir à les re-choisir à chaque saisie: 

* Quand on enchaîne les saisies de **sites** : possibilité de garder le groupe de site.

* Quand on enchaîne les saisies de **visites** : 
  * possibilité de garder les observateurs, la date, la meteo, JDD, etc.., c'est à dire **les variable qui ne vont pas changer pour la réalisation du circuit**,
  * et de choisir le site parmis la liste du groupe de site (dans un circuit on enchaîne plusieurs sites avec les même observateurs, date, condition...).

Cette partie mériterai une issue

**Comment by joelclems** [comment]
La liste des tâche (évolitive)  pour intégrer les groupes de site au module

- [ ] SQL 

  - [ ] créer une table `gn_monitoring.t_group_sites` avec les champs:
    - `id_group_site`
    - `id_module`
    - `group_site_name`
    - `group_site_code`
    - `uuid_group_site`
    - `commentaires` (unifier le nom des champs pour les commentaires dans toutes les tables?)
    - `data` `JSONB`

  - [ ] dans `t_site_complements`
    - ajout du champs en dur `id_group_site` `NULLABLE`

- [ ] BACKEND

  - [ ] modele `TGroupSites`
    - [ ] relation `medias`
    - [ ] relation `sites`

  - [ ] MonitoringObject `GroupSites`

  - [ ] api qui donne une liste de module pour un 
  - [ ] ajout de group-site dans data_utils

- [ ] FRONTEND
  - [ ] créer et renseigner `generic/group_site.json` et `test/group_site.json`
  - [ ] ajouter le champs `id_group_site` de type `datalist` (qui se sert de l'api défini ci-dessus)
  - [ ] faire simple (group_site à cote de sites) puis complexifier au fur et à mesure (groupe-site -> site -> etc...)
    - [ ] saisie des groupes à partir de la liste de groupes (comme les autres objets)
    - [ ] dans la saisie de site, choix du groupe possible
  
  - [ ] en plus pouvoir faire de la saisie par circuit : pour les visites on peut garder des champs d'une saisie à l'autre et choisir le site depuis la visite (créer un issue dédiée à ce sujet)

**Comment by joelclems** [comment]
J'ai pu un peu avancer un au niveau des groupes de sites, du moins en base et en backend

pour le frontend j'ai pu mettre en place la solution ou les groupes sont à côtés des sites, 
 -on peut définir des groupes
- et ensuite les associés aux site lors de la création ou la modification de sites
un exemple dans le dossier contrib (sites_group_aside)

la solution ou les groupes sont au dessus des site demande un peu plus de travail en frontend mais n'est pas impossible.
On peut faire les saisie mais l'affichage des sites plante pour l'instant
un exemple dans le dossier contrib (sites_group_top)

à l'heure de ce post ces exemples marchent avec la branche monitoring de GN et groupsites de monitoring

**Comment by Mounir-jelassi** [comment]
Nous avons réalisé les actions suivants :
1.	La création du module POPAmphibien
2.	Ajouter un fond de plan Corine Land Cover (type d'occupation du sol) via un flux WMS 
Le flux suivant (LANDCOVER.CLC18_FR): http://wxs.ign.fr/corinelandcover/geoportail/r/wms?service=WMS&request=GetCapabilities
![image](https://user-images.githubusercontent.com/68019751/94145328-abc89e80-fe72-11ea-8ba8-905189a5ef0a.png)

**Comment by camillemonchicourt** [comment]
OK, il faudrait bien dissocier les développements pour les contribuer dans des PR distinctes.
Car pour la partie Groupes de sites, il y a un développement bien avancé sur le sujet dans la branche dédiée : https://github.com/PnX-SI/gn_module_monitoring/tree/groupsites

Toute la partie consistant à nommer le groupe de site en fonction de la commune etc... n'est pas générique donc ne pourra certainement pas être intégrée au dépôt si développée de manière spécifique.

**Comment by joelclems** [comment]
C'est super, il faut voir comment regrouper les codes.

Est ce que les codes sont visible quelque part?

- pour le formulaire commune il y a un composant pnx-municipalities dans les dynamic forms je sais pas si ça peux faire l'affaire,
sinon on doit pouvoir s'en sortir avec le composant datalist avec la bonne api qui pioche dans les données du schéma `ref_geo`.

- pour les JDD
  - on peut créer une issue et une branche sur les problématiques de JDD par groupe de site et plus généralement pouvoir assouplir l'utilisation des JDD à différent niveaux.
  - cela recoupe fortement les discussions sur le module cmr https://github.com/PnX-SI/gn_module_cmr/issues/3
  - Il faut voir aussi comment filtrer les données par rapport au JDD auquels à accès l'utilisateur

- pour la partie import de données gpx il y a déjà une issue https://github.com/PnX-SI/gn_module_monitoring/issues/13, on peux échanger la-bas sur les problèmes rencontrés et les solutions à mettre en oeuvre.

**Comment by camillemonchicourt** [comment]
Quand on demande à l'utilisateur de localiser un objet sur la carte, on ne lui demande pas par ailleurs de renseigner des informations géographiques, comme la commune. Car cela est source d'erreur, est redondant dans la saisie, et donc calculable.
