### ISSUE TITLE
[0.6.0] : erreur nvm à la mise à jour du module

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/gn_module_monitoring#240]
Bonjour à tous,

**Version :** 
GN : 2.12.3
Monitorings : 0.5.0 --> 0.6.0

**Context :** 
Lorsque je met à jour le module, j'obtiens une erreur à l'installation du frontend que je ne parviens pas à fixer.
Auriez-vous une idée, une piste pour résoudre ce problème ?

**Comportement attendu :** 
Une installation sans encombre du module 

**Commandes réalisées pour la mise à jour :**
``` sh
cp -R ~/gn_module_monitoring/config/monitoring/* ~/geonature/backend/media/monitorings
rm -R ~/geonature/backend/media/monitorings/generic

VERSION=0.6.0
wget https://github.com/PnX-SI/gn_module_monitoring/archive/$VERSION.zip
unzip $VERSION.zip
rm $VERSION.zip
rm -R /home/`whoami`/gn_module_monitoring_old
mv /home/`whoami`/gn_module_monitoring /home/`whoami`/gn_module_monitoring_old
mv /home/`whoami`/gn_module_monitoring-$VERSION /home/`whoami`/gn_module_monitoring

source ~/geonature/backend/venv/bin/activate
geonature install-gn-module ~/gn_module_monitoring MONITORINGS
``` 

**erreur :** 
``` py
Installing collected packages: gn-module-monitoring
  Attempting uninstall: gn-module-monitoring
    Found existing installation: gn-module-monitoring 0.6.0
    Uninstalling gn-module-monitoring-0.6.0:
      Successfully uninstalled gn-module-monitoring-0.6.0
Successfully installed gn-module-monitoring-0.6.0

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Correction du lien symbolique /home/geonatureadmin/geonature/frontend/external_modules/monitorings → /home/geonatureadmin/gn_module_monitoring/frontend
Installation des dépendances frontend…
No .nvmrc file found
Running node v16.13.1 (npm v8.1.2)
/home/geonatureadmin/.nvm/nvm-exec: line 15: /home/geonatureadmin/gn_module_monitoring/frontend/lts/gallium: No such file or directory
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/geonature/core/command/create_gn_module.py", line 74, in install_gn_module
    install_frontend_dependencies(module_frontend_path)
  File "/home/geonatureadmin/geonature/backend/geonature/utils/command.py", line 69, in install_frontend_dependencies
    run(cmd, check=True, cwd=module_frontend_path)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/bin/bash', '-i', '-c', 'nvm exec lts/gallium npm ci --omit=dev --omit=peer']' returned non-zero exit status 127.
```

**Comment by camillemonchicourt** [comment]
La procédure de mise à jour vers la 0.6.0 me semble OK.
Il y a un soucis avec NVM, je ne connais pas bien ni ne comprend le soucis.
Il ne trouve pas la version à utiliser ou installer, il me semble.
Si je comprends bien, le message d'erreur indique qu'il ne trouve pas dossier `/home/geonatureadmin/gn_module_monitoring/frontend/lts/gallium`, ce qui me semble normal, car je ne crois pas qu'il doive exister un tel répertoire.

J'ai trouvé ailleurs ce retour : 

> nvm only exits with 127 explicitly on install or uninstall, when nvm install without a version being specified and without an .nvmrc file present somewhere.

**Comment by joelclems** [comment]
il faut peut être faire la commande suivante avant d'installer le module ??

``
cd ~/geonature/frontend
nvm install
nvm use
``

**Comment by cen-cgeier** [comment]
J'ai exécuté la commande suivante : 
``` py
(venv) geonatureadmin@cen38:~$ nvm install lts/gallium
Downloading and installing node v16.20.2...
Downloading https://nodejs.org/dist/v16.20.2/node-v16.20.2-linux-x64.tar.xz...
################################################################################################################################################################# 100,0%
Computing checksum with sha256sum
Checksums matched!
Now using node v16.20.2 (npm v8.19.4)
```
Puis j'ai reproduis la procédure évoquée dans le premier message.
Tout fonctionne comme sur des roulettes ! Merci ! :rocket: 

Serait-ce utile d'ajouter un check `nvm installés` VS `nvm utilisé` dans la procédure d'installation et d'installer la version a utiliser si elle n'est pas présente ?

**Comment by camillemonchicourt** [comment]
Il faut qu'on creuse et reproduise, car c'est pas normal de devoir faire ça au niveau du module, à ma (faible) connaissance. 🤔

**Comment by camillemonchicourt** [comment]
Je viens d'installer un GeoNature en 2.12.3, puis le module Monitorings en version 0.5.0 que j'ai mis à jour en 0.6.0 dans la foulée, sans rencontrer de soucis.
Peut-être car je venait d'installer GeoNature et donc que ma version de Node.js était OK et à jour, mais je continue à ne pas vraiment comprendre le soucis que tu as rencontré.

**Comment by camillemonchicourt** [comment]
Ça je sais pas, c'est ce dont je doute.
Je pense que c'est mis à jour quand on met à jour GeoNature, mais je maîtrise pas du tout ce sujet. 
C'est pour ça qu'on va garder ce ticket ouvert pour voir si ça se reproduit et si on trouve un moment pour investiguer ce sujet.

**Comment by andriacap** [comment]
Bonjour , 

Dans le cadre d'une prestation pour la DREAL Corse , je viens de réaliser la même démarche . Installation du module monitoring en version 0.6.0 avec un GN en 2.12.3 et j'ai eu la même erreur avec NVM qui n'avait pas la version LTS Gallium .
Problème résolu en réalisant la commande donnée par @joelclems  `nvm install && nvm use` sur le frontend de GN.
