### ISSUE TITLE
Permissions au niveau des objets des modules monitoring

### ISSUE THREAD

**Issue by amandine-sahl** [PnX-SI/gn_module_monitoring#249]
Pour éviter toute confusion (et ne pas réimplémenter un pseudo héritage entre les permissions), nous souhaiterions que les droits des utilisateurs pour un type d'objet correspondent aux permissions définis pour ce type et non pour l'objet ALL.

Par exemple un module qui a des sites, des visites et des observations aurait les permissions disponibles suivantes :

 * ALL - R : accès au module
 * ALL - U : modification des paramètres du module
 * ALL - E : exporter les données du module
 * GNM_SITES - CRUD
 * GNM_VISITS - CRUD
 * GNM_OBSERVATIONS - CRUD

**Comment by TheoLechemia** [comment]
`MONITORING_` plutôt que `GNM_` ?

**Comment by camillemonchicourt** [comment]
Oui bien vu.
Je crois que c'est ce qui est fait dans Occtax etc, donc privilégier l'homogénéité.

**Comment by amandine-sahl** [comment]
Après discussion les permissions seraient :

 * MONITORINGS_MODULES - R : accès au module
 * MONITORINGS_MODULES - U : modification des paramètres du module
 * MONITORINGS_MODULES - E : exporter les données du module
 * MONITORINGS_SITES - CRUD
 * MONITORINGS_GRP_SITES - CRUD
 * MONITORINGS_VISITS - CRUD (qui inclus les permissions des objets visites, observations et observations détails)

**Comment by MathRdt** [comment]
Hello !
Merci pour cette amélioration des permissions sur le module monitoring !
Je voulais savoir si vous aviez une idée de la date de release de cette amélioration ?
C'est une feature qui nous intéresse beacuoup côté CREA avec @ColinVanReeth et on a hâte de pouvoir la tester !
Y a t'il des points bloquants ou des actions que je peux prendre pour valider cette feature ?

Bonne journée,
Mathieu

**Comment by amandine-sahl** [comment]
Nous sommes en train de tester s'il n'y a pas des effets de bord non anticipés. Si vous voulez faire avancer la PR, n'hésitez pas à la tester tous les retours sont bon.

**Comment by MathRdt** [comment]
Ok super, merci pour les informations.
Je vais tenter de l'implémenter sur notre environnement de dev, je vous fait des retours si j'ai des soucis ou comportements bizarre.

**Comment by MathRdt** [comment]
Hello,
désolé pour le retard, j'ai été mobilisé sur d'autres sujets. 
J'ai pu déployer cette version de dev et enfin la tester ! Pour la partie CRUD sur les différents modules tout semble bien se passer de mon côté, donc super !

Par contre le filtre sur l'appartenance des données ne semble pas fonctionner. Si je rajoute le filtre "Mes données", j'ai quand même le droit de voir tous les sites, visites, etc... Même ceux créés par une autre personne

**Comment by amandine-sahl** [comment]
merci pour les tests. 

Effectivement la portée n'est pas encore fonctionnelle, elle viendra dans un second temps.
