### ISSUE TITLE
Observation : choix de la liste de taxon

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/gn_module_monitoring#253]
Version :
Taxhub 1.11.1
Geonature 2.12.3
Monitorings 0.6.0

Bonjour à tous, 
je fais suite au problème décrit ici /issues/68
J'ai le même souci, beaucoup d'explication dans l'issue... mais je ne comprends pas bien comment résoudre mon pb : je n'arrive pas à limiter les taxons saisissables dans le module à la liste de taxons que j'ai créé dans Taxhub.
Dans Taxhub, j'ai une liste de coléoptères aquatiques : id_liste = 101
Dans mon module, j'ai défini la liste de taxons à utiliser : 
![image](https://github.com/PnX-SI/gn_module_monitoring/assets/15034095/e2e7160f-6ecd-423f-bcec-12fb2469236b)
Dans mon `observation.json` j'ai ça : 
```
"specific": {
    "cd_nom": {
      "type_widget": "taxonomy",
      "attribut_label": "Taxon",
      "keyValue": "cd_nom",
      "keyLabel": "__MODULE.TAXONOMY_DISPLAY_FIELD_NAME",
      "multiple": false,
      "api": "taxref/allnamebylist/__MODULE.ID_LIST_TAXONOMY",
      "application": "TaxHub",
      "required": true,
      "type_util": "taxonomy"
```

Dans mon `config.json` j'ai mis : 
```
 "data": {
    "taxonomy": {
      "id_list": "__ID_COMPONENT_TAXONOMY"
```
Mais dans la saisie, je peux saisir un accenteur mouchet...
![image](https://github.com/PnX-SI/gn_module_monitoring/assets/15034095/ef7ba61b-f17c-4024-b2fb-dca3339dd2c3)

Autre question également, à force de modifier les .json, j'ai fait disparaitre les `+ ` qui sont dans le tableau récapitulatif des visites et qui permettent de rajouter une observation. Je ne vois pas quel est le paramètre qui affiche/désaffichent ces raccourcis d'ajout de sites ou d'observations. 
![image](https://github.com/PnX-SI/gn_module_monitoring/assets/15034095/046f6d0a-0600-4eb5-9173-6b5f457f13e2)

Donc 2 questions : 
Où est mon erreur dans la gestion de la liste de taxons ?
Comment faire réapparaître ces `+` ? Pas grave en soit car il y a l'autre bouton `Ajouter une obs`, mais je ne comprends pas comment j'ai fait pour les supprimer.

Merci d'avance pour votre aide,
Bonne journée,
Vottana

**Comment by pierre56** [comment]
Bonjour @Vottana ,
Pour ta question 1

Je te conseille de modifier le widget et de tenter avec ce snippet :

```
  "specific": {
    "cd_nom": {
      "type_widget": "taxonomy",
      "attribut_label": "Taxon observé",
      "type_util": "taxonomy",
      "required": true,
      "id_list": "__MODULE.ID_LIST_TAXONOMY"
  },
```

j'avais un module avec le même code que le tien et ce n'était pas fonctionnel pour la recherche des taxons.

> ⚠️ Actuellement j'ai un soucis, où la liste ne remonte pas les noms vern avec des accents ex:"crapaud épineux"
Je viens de détecter et je bosse sur la correction en ce moment.
en 2.13.0
 -----
 Pas de réponse pour la question 2 :/

**Comment by camillemonchicourt** [comment]
En effet, déjà la définition de ton champs n'était pas bonne car elle mélangeait des propriétés du type de widget "datalist" et du type de widget "taxonomy".
Si tu veux un widget "taxonomy", ses propriétés sont en effet plus simples, comme indiqué par @pierre56, ainsi que dans la doc des champs : https://github.com/PnX-SI/gn_module_monitoring/blob/main/docs/sous_module.md#d%C3%A9finir-une-nouvelle-variable.

Pour le fait que la liste des taxons n'est pas limitée à ce qui est défini dans la liste TaxHub, il faudrait voir si tu as des erreurs ou plus d'infos dans les logs.

Je viens de tester sur le serveur de démo de créer une liste de taxons avec un seul taxon et de l'associer à un sous-module de Monitoring, et cela fonctionne bien, je n'ai bien qu'un taxon proposé dans la liste des espèces quand j'ajoute une observation.

D'ailleurs, pour le module sur lequel j'ai testé, il n'y a même pas à mentionner le champs ESPECE dans la configuration des observations, puisque c'est un champs par défaut, donc je comprends même pas pourquoi vous tentez de l'ajouter dans `observations.json`.
Sur le sous-module que j'ai testé avec succès, ce champs n'est pas déclaré, seulement ceux à ajouter : https://github.com/PnX-SI/protocoles_suivi/blob/master/chronocapture/observation.json

**Comment by pierre56** [comment]
Salut @camillemonchicourt 
Merci pour les précisions, je savais pas qu'on pouvait l'enlever.

Pour la raison, c'est un module national et j'essaye de coller au maximum à l'original, 
tout en répondant aux demandes de mes collègues 

le code du dessus est la solution que j'ai trouvé pour avoir la liste fonctionnelle.
Exemple : https://github.com/PnX-SI/protocoles_suivi/blob/master/POPReptile/observation.json

**Comment by camillemonchicourt** [comment]
OK, je ne comprends pas pourquoi le champs ESPECES est re-déclaré dans cet exemple (https://github.com/PnX-SI/protocoles_suivi/blob/master/POPReptile/observation.json#L24-L34), en plus je ne comprends pas pourquoi il utilise un widget de type "taxonomy" mais avec des propriétés de widget "datalist".
C'est peut-être ça qui a posé exemple dans vos 2 cas.

**Comment by Vottana** [comment]
Bonjour à tous, merci pour vos réponses.
J'ai suivi les exemples de modules proposés, en essayant de modifier par çi par là quand ça ne fonctionnait pas... c'est vrai qu'à la fin je dois me retrouver avec un truc pas très propre non fonctionel.
En mettant juste : 
```
"specific": {
    "cd_nom": {
    "type_widget": "taxonomy",
    "attribut_label": "Taxon",
    "type_util": "taxonomy",
    "required": true,
    "id_list": "__MODULE.ID_LIST_TAXONOMY"
    },
```
Tout est rentré dans l'ordre. Et j'ai bien une liste limitée à ma liste de taxon. 
Et, oh miracle, les + qui avaient disparus, pour ajouter une nouvelle obs sont réapparu. Pourquoi, comment ?...
Je ferme l'issue. Merci encore pour votre aide.
