### ISSUE TITLE
[datalist] `filters` not work

### ISSUE THREAD

**Issue by cen-cgeier** [PnX-SI/gn_module_monitoring#257]
Version :
- GN : 2.13.3
- Monitoings : 0.7.0

Bonjour à tous,
J'ai constaté aujourd'hui que la variable `filters` ne semble plus fonctionner pour le `"type_widget" : "datalist"`.
Je fais notamment ce constat avec le protocole RHOMEOOdonate.

voici un extrait du code du fichier `observation.json` :
``` JSON    
     ... },
    "id_nomenclature_behaviour": {
      "type_widget": "datalist",
      "attribut_label": "Type de comportement reproducteur",
      "api": "nomenclatures/nomenclature/OCC_COMPORTEMENT",
      "application": "GeoNature",
      "keyValue": "id_nomenclature",
      "keyLabel": "label_fr",
      "data_path": "values",
      "type_util": "nomenclature",
      "params": {
          "regne": "Animalia",
          "group2_inpn": "Insectes"
      },
      "filters": {
        "label_fr": ["Non renseigné","Tandem", "Territorial", "Pond", "Accouplement"]
      },
      "multiple": true,
      "required": "({value}) => !value.id_nomenclature_life_stage"
    },
    "id_nomenclature_life_stage": {
      "type_widget": "datalist",
      "attribut_label": "Stade de vie",
      "api": "nomenclatures/nomenclature/STADE_VIE",
      "application": "GeoNature",
      "keyValue": "id_nomenclature",
      "keyLabel": "label_fr",
      "keyTitle": "definition_fr",
      "data_path": "values",
      "type_util": "nomenclature",
      "filters": {"label_fr": ["Emergent", "Immature"]},
      "multiple": true,
      "required": "({value}) => !value.id_nomenclature_behaviour"
    },
    ...
```
et voici une capture du rendu : 
![image](https://github.com/PnX-SI/gn_module_monitoring/assets/96542451/09176e91-2088-451a-8499-712c70d3d5a2)
![image](https://github.com/PnX-SI/gn_module_monitoring/assets/96542451/cc3a2948-ab7e-4bed-86b6-1976a4dc8c75)

Il me semble que l'option `filters` du composant `datalist` est expliqué comme cela dans la doc et cette configuration fonctionnait lorsque le module est `RHOMEOOdonate` est sortie.

Il y aurait-il une évolution que j'ai manqué ? Une config qui a sauté suite à une mise à jour ?

**Comment by joelclems** [comment]
Il y a bien eu un changement pour passer le composant en style bootstrap et qui ne tient plus compte des filtres

**Comment by camillemonchicourt** [comment]
Corrigé dans la version 2.13.4 de GeoNature.
