### ISSUE TITLE
Pourvoir paramétrer le centrage de la carte pour chaque sous-module/protocole

### ISSUE THREAD

**Issue by RomainBaghi** [PnX-SI/gn_module_monitoring#26]
Nous allons sans doute décliner certains de nos protocole à l'outre mer, or notre instance geonature est actuellement centrée sur la métropole.
Pour ces protocoles spécifiques (sous-module monitoring), il faudrait pouvoir surcoucher ce paramètres à ce niveau là.

**Comment by joelclems** [comment]
Les cartes se placent automatiquement sur l'emprise des sites (et par défault en métropole si il n'existe pas encore de site).
Il suffit donc de rajouter un site pour que la carte se place comme on le souhaite.
