### ISSUE TITLE
Création de sites impossible

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#27]
Bonjour, 

Actuellement en train de tester la branche develop , je constate un soucis sur mon instance (pas présent sur la démo) quand je tente de créer un site. Le spinner tourne indéfiniment, et les log (gn_errors) renvoient : 
geonature.utils.errors.GeoNatureError: MONITORING: create_or_update monitoringobject chronocapture, site, None : (psycopg2.DataError) ERREUR:  les valeurs NULL ne peuvent pas être formatés comme un identifiant SQL
CONTEXT:  fonction PL/pgsql gn_commons.fct_trg_log_changes(), ligne 22 à EXECUTE

Ma configuration ne semble pas très différente des autres (stom, test, oedic, chevette) : 
`{
  "geometry_type": "Point",
  "display_properties": [
    "base_site_name",
    "id_inventor",
    "first_use_date",
    "last_visit",
    "nb_visits", 
    "desc_habitat",
    "prospect_surf", 
    "comment_site"
  ],

Je suis sur debian10, postgresql11, une install all neuve de Geonature 2.4, sur laquelle j'ai restauré ma bdd depuis pg9.6/debian10). Mais le module monitorings n'a été installé que sur mon instance à jour sous debian10 donc j'imagine que la migration n'est pas un soucis. 
La fonction log_changes ne renvoie pas de soucis particulier avec mon module occtax qui fonctionne bien. A voir si d'autres ont le souci :)

**Comment by DonovanMaillard** [comment]
Après réflexion de camille et quelques recherches, j'ai pu trouver l'origine du soucis. 

Le trigger log_changes se lance, et appelle les informations de gn_commons.bib_tables_location pour cibler la table qui fait l'objet des changements logués. 

Or pour le moment, le fichier data/schema_suivis_generique.sql n'intègre dans cette table que : 
`INSERT INTO gn_commons.bib_tables_location(table_desc, schema_name, table_name, pk_field, uuid_field_name)
VALUES
('Table centralisant les modules faisant l''objet de protocole de suivis', 'gn_monitoring', 't_module_complements', 'id_module', 'uuid_module_complement'),
('Table centralisant les observations réalisées lors d''une visite sur un site', 'gn_monitoring', 't_observations', 'id_observation', 'uuid_observation');`

En rajoutant la table sites, j'ai pu créer un site sans soucis. Reste à savoir pourquoi ça  fonctionne dans vos instances, j'imagine que ces données ont été ajoutées au cours d'une précédente version, ou que j'ai raté quelque chose lors d'une mise à jour (je fais des updates depuis la 2.0.0rc3).

**Comment by joelclems** [comment]
Pour les sites et les visites, pour renseigner la table ``gn_commons.bib_tables_location``
cela vient de GEONATURE, du fichier [monitoring.sql](https://github.com/PnX-SI/GeoNature/blob/develop/data/core/monitoring.sql)

pour le module monitoring on rajoute les lignes pour les modules et les observations

il faudrai trouver pourquoi tu n'avais pas les lignes pour les sites et visites? peut être avec la restauration de la base??

**Comment by DonovanMaillard** [comment]
Bonjour Joel, merci pour ta réponse. 

C'est un mystère en effet, les données étaient intégrées par monitoring.sql dès le 18 avril 2018, avant notre première installation. Je vais vérifier que les index, contraintes etc soient bien passées. 

La restauration de la base étant faite avec un pg_restore pour l'ensemble de ma base, ça me surprend que seules ces données là n'aient pas été restaurées (tout le reste a bien fonctionné). Je pense qu'il y a un soucis qui date de bien avant : soit soucis à l'installation soit, plus probablement, mauvaise manipulation de ma part à un moment donné...  

L'essentiel est que l'insertion de ces données ne soit pas oublié dans les scripts d'installation :)

**Comment by camillemonchicourt** [comment]
Même soucis chez nous.

OK une fois ajouté les tables dans la table ``gn_commons.bib_tables_location`` : 
```SQL
INSERT INTO gn_commons.bib_tables_location(table_desc, schema_name, table_name, pk_field, uuid_field_name)
VALUES
('Table centralisant les sites faisant l''objet de protocole de suivis', 'gn_monitoring', 't_base_sites', 'id_base_site', 'uuid_base_site'),
('Table centralisant les visites réalisées sur un site', 'gn_monitoring', 't_base_visits', 'id_base_visit', 'uuid_base_visit');
```

Le schéma ``gn_monitoring`` a été intégré dans la version 2.0.0.rc1 de GeoNature (https://github.com/PnX-SI/GeoNature/releases/tag/2.0.0-rc.1) mais il y a peut-être eu un manque ensuite. A creuser.

**Comment by joelclems** [comment]
Normalement régler avec les commandes d'insertion en base de toutes les lignes (ne met pas les lignes qui existent déjà)

**Comment by camillemonchicourt** [comment]
Les lignes éventuellements manquantes ont été ajoutées si elles manquaient ? Au niveau du module Monitoring ? Ou de GeoNature ?

**Comment by joelclems** [comment]
Elles sont dans l'installaton et dans le migration de monitoring et de sorte que s'il une ligne existe déjà on la change pas mais on ajoute toujours celle qui manques

https://github.com/PnX-SI/gn_module_monitoring/blob/d9e1ba1be8c54fb39014c862fd59b28467b2732a/data/schema_suivis_generique.sql#L112-L122

**Comment by camillemonchicourt** [comment]
OK mais vu que c'est une partie de la BDD créée par GeoNature, on devrait plutôt vérifier que c'est maintenant bien réglé dans les scripts d'installation de GeoNature. Et les repasser au cas où dans les scripts de migration SQL vers la 2.5.0, qui sera de toute façon nécessaire pour installer la future version du module Monitoring.
