### ISSUE TITLE
Ergonomie - faciliter le passage d'un niveau à l'autre

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#28]
Un grand merci pour ce module vraiment très bien pensé et ultra permissif (une fois qu'on s'est mis les configurations en tête surtout!)

Une idée d'amélioration de l'ergonomie lors de la saisie, 

Il semblerait intéressant qu'on ait sur chaque formulaire de saisie un bouton pour "Valider et saisir [la suite]" . 
Ainsi sur le formulaire de création d'un site, l'utilisateur peut "Valider et saisir une visite", et sur un formulaire de saisie de visite, il peut "Valider et saisir une observation". Qu'en pensez-vous ?

**Comment by camillemonchicourt** [comment]
En lien avec https://github.com/PnX-SI/gn_module_monitoring/issues/22

**Comment by joelclems** [comment]
J'ai rajouter un boutton valider et saisir des ... (plus simple pour ne pas tenir compte du genre) et qui renvoient sur la creation d'objets enfants.
Ce bouton n'apparait que dans le cas d'une création
