### ISSUE TITLE
Suppression des observations dans un module, message d'erreur dans la synthèse

### ISSUE THREAD

**Issue by Vottana** [PnX-SI/gn_module_monitoring#286]
Geonature 2.12.3
Monitorings 0.6.0

Bonjour à tous, 

Lors de la saisie d'observations dans un module monitoring, la synthèse se met bien à jours. Mais si je supprime l'observation dans le module, l'observation est toujours présente dans la synthèse. En cliquant sur le bouton "Voir l'observation dans le module de saisie", j'ai une erreur de serveur. Ce qui est normal vu que j'ai supprimé l'observation, mais je me demandais s'il y avait une manip à faire, que je n'ai pas faite, pour que la suppression soit prise en compte dans la synthèse (le bouton mise à jour de la synthèse dans le module ne résout pas le problème).

En soit, ce n'est pas grave, car je peux supprimer les obs directement dans la base de données mais je voulais savoir si c'était "normal", dans le sens où la synthèse récupère les données mais pour la suppression il faut le faire manuellement dans la base.
Merci d'avance pour vos retours,
Vottana

**Comment by camillemonchicourt** [comment]
Je pense que la suppression automatique des observations dans la Synthèse n'a pas été mise en place car plus complexe que l'ajout et la mise à jour (fonctionnel je pense ?).
Pour pouvoir supprimer les observations dans la Synthèse, il faut savoir quelles observations ont été supprimées dans Monitoring, mais comme elles ont été supprimées, on n'en a plus de trace quand on relance la synchro Monitoring > Synthèse.

Selon moi, c'est un problème gênant que de garder dans la synthèse des observations qui ont été supprimées dans Monitoring.

Je vois plusieurs solutions : 
- Passer d'un mécanisme de synchro différée à des triggers qui pourraient être lancés directement lors de l'ajout, modification ou suppression d'une observation dans Monitoring
- Comparer les observations du sous-module Monitoring présentes dans la Synthèse avec celles dans Monitoring pour identifier celles qui sont dans la Synthèse mais plus dans le sous-module de Monitoring et ainsi les supprimer (lourd quand un sous-module a beaucoup de données)
- Tracer les suppression des sous-modules Monitoring dans une table pour pouvoir les supprimer dans la Synthèse.

**Comment by joelclems** [comment]
il y a le fichier [delete_synthese.sql](./data/delete_synthese.sql) contient des triggers pour synchroniser les suppression dans la synthèse avec les suppression des visites ou des observation dans monitoring, mais il n'a pas été intégré aux migration alembic

**Comment by Vottana** [comment]
Merci pour vos retours (oui la mise à jour est fonctionnelle). 
Okay, c'est bon à savoir. Pour l'instant, c'est gérable manuellement, nous débutons les saisies. Je vais informer les collègues de faire attention à la suppression et de m'en informer pour que je supprime les données dans la base au besoin.

**Comment by TheoLechemia** [comment]
Salut,
@joelclems : il y a un raison pour ne pas avoir appliquer ces triggers à tous le monde ?
De ce que je lis, la fonction de trigger des visites s'appuie sur `unique_id_sinp` de la synthese pour supprimer les observations. A mon sens ça devrait plutôt être `unique_id_sinp_grp` non. 
Mais en fait ça dépend beaucoup du mapping que les gens ont mis dans le vue `synthese.sql` (qui en plus est propre à chaque module)

**Comment by amandine-sahl** [comment]
> en fait il y a déjà un trigger qui supprime les observations quand on supprime les visite. Donc seul le trigger sur les observations devrait suffir

Il est possible d'avoir des modules qui s'arretent au niveau de la visite et qui générent en entrée dans la synthèse. Pour ces cas là il est interressant d'avoir un trigger au niveau de la visite. Par contre je ne pense pas qu'il soit possible de générer une entrée dans la table synthèse uniquement à partir des sites.

Par exemple : le module cheveche n'implémente pas le niveau observation, c'est au niveau de la visite qu'on indique si oui ou non il y a eu un contact.

**Comment by camillemonchicourt** [comment]
Triggers de suppression des données dans la Synthèse, intégré dans la 1.0.0.
Voir les notes de versions de cette release pour vérifier si vous avez des données historiques qui ont été supprimées auparavant dans Monitoring mais pas dans la Synthèse (car il n'y avait pas encore de trigger en place), pour les supprimer ensuite de la Synthèse si vous le souhaitez.
