### ISSUE TITLE
Tables de complements séparées ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#3]
Pour les champs additionnels spécifiques à chaque protocole, les données sont stockées dans un champs ``jsonb``. Pour cela des tables ``complements`` étendant les tables de base des sites, visites et observations ont été créées, avec une liaison 1-1. 
N'aurait-il pas été aussi efficace et plus simple, d'ajouter ces champs ``complements`` en ``jsonb`` directement dans les tables de base (``t_base_sites``, ``t_base_visits`` et ``t_observations``) ?

**Comment by joelclems** [comment]
Ta remarque est très pertinente, effectivement cela aurait plus simple d'ajouter les champs dans les tables de base,  et c'est quelque chose que j'avais implémenté au début mais que j'ai choisi de changer ensuite.

J'ai procédé de cette manière dans la perspective ce pouvoir créer des tables spécifiques à partir de la configuration du sous-module et  avec des vrais champs et non des champs stockés dans une variable de type `jsonb` et que l'on pourrait nommé d'apres le code du module (par exemple `t_site_test_complement` ou` t_site_test` pour le module de test un peu comme ce qui est fait pour le module chiro). En backend je gère ça avec des modèles SQLAlchemy qui vont prendre en compte les deux tables.

Une deuxième raison concerne la table `t_site_complement` qui contient les informations complémentaires d'un site pour un module donné. On peut imaginer le cas ou un site est partagé entre plusieurs modules, et dont les informations spécifiques à chaque module peuvent être différentes. Dans ce cas on est plus dans le cas de liaisons 1-1.

**Comment by camillemonchicourt** [comment]
OK je vois, merci pour les précisions.

**Comment by camillemonchicourt** [comment]
Pour info, le modèle actuel : 

![diagramme_monitoring](https://user-images.githubusercontent.com/4418840/73931724-11aee880-48d9-11ea-939b-547bf903b650.png)

**Comment by joelclems** [comment]
Merci beaucoup Camille. Tu utilises quoi pour faire le schéma?

Pour précision la table `cor_site_area` peut faire doublon avec la table t_site_complements` (pour la relation sites-modules) mais elle est utilisée par les d'autres modules de suivi (chiro, ...)

**Comment by camillemonchicourt** [comment]
C'est @TheoLechemia qui l'a fait, DBeaver le génère automatiquement dans l'outil ER Diagram. 

La table ``cor_site_area`` sert à stocker les zonages des sites, donc c'est plutôt ``cor_site_module`` dont tu parles je pense.

On utilise aussi cette relation ``cor_site_module`` pour les autres modules de suivi : 
- gn_suivi_flore_territoire
- gn_suivi_habitat_territoire
- gn_suivi_habitat_station

**Comment by joelclems** [comment]
Oui c'est bien cor_site_module

**Comment by jbdesbas** [comment]
Pour alimenter un petit peu, le fait d'avoir les compléments d'observation dans une autre table complique un peu la mise en place des trigger UPDATE, étant donnée que la modification peut avoir lieu dans _t_observations_, dans _t_observation_complements_, ou dans _t_base_visit_ (voir même dans _t_base_visit_complement_)
