### ISSUE TITLE
Pouvoir définir le JDD à chaque visite

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#30]
Par défaut le formulaire des visites poste un ``id_dataset`` caché (https://github.com/PnX-SI/gn_module_monitoring/blob/master/config/monitoring/generic/visit.json#L62) et récupéré de la valeur globale définie dans la configuration du module (https://github.com/PnX-SI/gn_module_monitoring/blob/master/config/monitoring/generic/custom.json.sample#L5).

Il est possible de surcoucher cela dans la définition des visites du sous-module :
```
"id_dataset": {
      "type_widget": "text",
      "attribut_label": "JDD",
      "value": "__ID_DATASET_VISIT"
}
```

Idéalement, il serait parfait de pouvoir utiliser le composant ``dataset`` plutôt qu'un champs ``text`` où l'on doit saisir l'``id_dataset``.

**Comment by joelclems** [comment]
Salut camille, il y aurait une reflexion à mener sur l'utilisation des JDD aussi pour #24 .

Dans le cas présent,  il y a une valeur par défault et la personne qui saisie ne se soucie pas de choisir le JDD.
On pourrait aussi utiliser le composant data set, cela pourrait etre intéressant de proposer une sous-liste de JDD associée à un sous-module.

**Comment by camillemonchicourt** [comment]
Oui actuellement le JDD est bien associé au niveau des visites, définie globalement pour tous les protocoles de suivi ou spécifié pour chaque sous-module.

Une première étape sera de pouvoir la saisir au niveau de chaque visite comme évoqué ici, avec une liste des JDD du module.

Enfin un troisième niveau, évoqué dans #24, serait de pouvoir définir le JDD globalement, sans qu'il soit saisi par l'utilisateur mais en le définissant au niveau des groupes de site ou des sites. 

Un quatrième niveau serait de pouvoir le définir en fonction de l'observateur et/ou de son organisme.

**Comment by joelclems** [comment]
Pour la première étape

Au niveau module:
* on devrait pouvoir choisir les JDD associés à ce module (composant dataset ?) depuis la page du module
( on pourra utiliser la table `gn_commons.cor_module_dataset`)
(en mode administrateur seulement (à voir comment gérer le cruved pour ça)).

au niveau de la visite, 
* si plusieurs JDD sont assoicés au module,on propose de choisir
* si un seul JDD est associé au module, on ne propose pas  le choix (composant caché)

**Comment by camillemonchicourt** [comment]
Je ne suis pas certain qu'il faille associer les sous-modules à des JDD en plus de ce qu'il y a déjà dans cor_module_dataset

**Comment by joelclems** [comment]
oui je pensais utiliser la table cor_module_dataset.
j'ai vu que le composant dataset permet de secifier le code du module, c'est parfait pour les visites

**Comment by joelclems** [comment]
J'ai du faire un petit changement dans le composant dynamic form de GN 
(pour les dataset, super composant en passant il y avait tout ce dont j'avais besoin: choix multiple et filtre selon le module),
du coup la branche develop du module monitoring est compatible avec la branche monitoring de GN.

la branche monitoring de GN correspond a la branche develop de GN + les tout derniers PR concernant les modifs faites pour le module monitoring et qui ne sont pas encore pris en compte

**Comment by joelclems** [comment]
Avec ce dernier commit on peut:

* éditer un sous-module:
  * seulement pour les jdd
  * choisir plusieurs jdd pour ce sous-module parmis la liste proposé (tout les jdd disponibles)
  * c'est stocké dans `gn_commons.cor_module_dataset`

* création / édition d'une visite:
  * on peut choisir un jdd parmi la liste des JDD du sous-module

**Comment by camillemonchicourt** [comment]
Je me demande pourquoi faire l'association des JDD au sous-module, alors qu'on peut déjà associer des modules à un JDD sur le formulaire des JDD ?
C'est en plus pour pouvoir gérer cela aux deux endroits ?

**Comment by joelclems** [comment]
Dans le module méta données, on peut associer plusieurs module à un JDD. mais si on veux associer plusieurs JDD au module test, il faudrait aller sur la page d'édition de chaque JDD et y préciser le module  test.

Avec ces changements on peut aussi choisir des JDD existants depuis la page du module test.
Un autre avantage c'est que ça permet de voir quels JDD sont associés au module directement dans les propriétés du module test.

Au final on travaille toujours sur la même table cor_module_dataset et on peut renseigner les association de module et de JDD d'une manière ou d'une autre.

L'association des JDD au module à pour but de créer une sous-liste de JDD pour le formulaire des visites

Cela ne concerne que l'administrateur (ou les personne avec un cruved E égal à 3), les utilisateurs, n'auront pas à modifier cette liste de JDD.
