### ISSUE TITLE
Ambiguité comment_context / comment_description

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#31]
Dans la synthèse, comment context est le commentaire du relevé, tandis que comment_description est le commentaire de l'occurrence. 

Par défaut dans la vue vs_visit, utilisée ensuite pour le renvoi des données vers la synthèse dans l'exemple donné, c'est le commentaire de la visite qui est (t_base_visits) qui est utilisé "AS comment_description". 

On a donc un relevé (la visite) qui contient le commentaire de l'occurence et pas du relevé. Est-ce volontaire ?

**Comment by amandine-sahl** [comment]
En fait notre exemple de test: le protocole chêveche s'arrête au niveau de la visite. Ce qui n'est pas un cas "classique" d'où certaines incohérences pour les protocoles plus "standards". 
Le commentaire de t_base_visits devrait correspondre par défaut au comment_context et non pas au comment_description.

**Comment by DonovanMaillard** [comment]
D'accord merci pour ton retour. Explication semblable au #33 du coup.

**Comment by amandine-sahl** [comment]
Par contre attention lors de la mise à jour du module il faut gérer les vues dépendantes à gn_monitoring.vs_visits.

C'est pourquoi je ne recommande pas l'utilisation de cette vue. Je pense que d'une façon général il faut éviter d'avoir des vues dépendantes de vues.

**Comment by camillemonchicourt** [comment]
Oui ça a des avantages et des inconvénients.
En l'état, il faudrait fournir la correction de la vue dans un SQL update 0.1.0to0.1.1.sql et ceux qui ont des vues dépendantes se débrouillent pour les supprimer, corriger, recréer.

**Comment by joelclems** [comment]
Pour les vues, ça pourrait être géré différemment que avec le fichier d'update.
j'ai fait un script update_views.sh qui recrée toutes les vues pour la synthèse,
* d'abord la vue générale,
* puis les vues de tous les sous-modules (tous les fichiers synthese.sql présent dans le dossier des sous-modules)

il faut juste l'executer quand on met à jour le module (ou trouver une manière de la faire de façon automatique)

**Comment by camillemonchicourt** [comment]
OK super, encore mieux. 
Il suffit d'indiquer de l'exécuter dans la procédure de mise à jour du module.
