### ISSUE TITLE
Choix du groupe de site dans une liste issue de l_areas

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/gn_module_monitoring#321]
Je suis en train de développer un module de suivi où j'ai besoin de la configuration suivante :

-  1 seul dataset,
-  Des groupes de sites dont le nom et le code sont récupérés dans la table ref_geo.l_areas en fonction d'un id_type spécifique,
-  Des sites correspondant à des parties des groupes de sites

_Petite précision : ce module ne comporte pas de données naturalistes. Il s'arrête au niveau de la visite. Les données ne sont pas vouées à remonter dans la synthèse ni vers l'INPN._

A priori, il n'est pas possible de restreindre la saisie des données au niveau site à une potentielle géométrie du groupe de site (puisqu'a priori, ça fonctionne dans l'autre sens si on demande à ce que les sites dessinent la géométrie des groupes de sites) => fonctionnalité en attente

pour le lien avec les groupes de sites, a priori ce n'est pas incrémenté dans le module de suivi pour l'instant (seulement utilisateurs, nomenclatures, ...). Cependant le code suivant permet d'afficher la liste des éléments de ref_geo.l_areas :

``` 
"sites_group_name": {
      "type_widget": "datalist",
        "hidden": false,
        "required": true,
        "keyValue": "area_name",
        "keyLabel": "area_name",
        "api": "/geo/areas",
        "filter": {"id_type": ["12"]},
        "application": "GeoNature",
        "definition": "Nom du site CEN dans lequelle sont localisées les parcelles" 
    },
```

Mais le filtre ne fonctionne pas et à l'enregistrement ça fait crasher le module. Est ce qu'il y a une façon de le modifier pour que ça fonctionne ? (et que ça filtre sur le bon id_type?)

A priori si on veut ensuite récupérer le area_code, il faut utiliser un paramètre dynamique "change", c'est cela?

Merci :)

**Comment by amandine-sahl** [comment]
Est-ce que vous auriez le détail des logs? De mon coté j'ai testé la surcharge et je n'ai pas de soucis

**Comment by marie-laure-cen** [comment]
Je n'ai rien trouvé de particulier sur les logs pour cette erreur. Le code suivant fonctionne sans erreur (à part le filtre qui ne fonctionne pas :
```
    "sites_group_name": {
      "type_widget": "datalist",
      "attribut_label": "Site CEN rattaché aux travaux",
      "hidden": false,
      "required": true,
      "keyValue": "area_name",
      "keyLabel": "area_name",
      "type_util": "areas",
      "api": "/geo/areas",
      "filters": {
        "id_type": ["12"]
      },
      "application": "GeoNature",
      "definition": "Nom du site CEN dans lequelle sont localisées les parcelles" 
    }
```

**Comment by marie-laure-cen** [comment]
Du coup pour le filtre, c'est une question de version de GeoNature (que j'avais oublié de mettre dans mon 1er message) => corrigé dans la version 2.13.4] cf #257

**Comment by marie-laure-cen** [comment]
Pour information, j'ai résolu mon problème en ne passant pas par filters mais en récupérant la requête de chargement des éléments de la carte :
```
"sites_group_name": {
  "type_widget": "datalist",
  "attribut_label": "Site CEN rattaché aux travaux",
  "hidden": false,
  "required": true,
  "keyValue": "area_code",
  "keyLabel": "area_name",
  "type_util": "areas",
  "api": "/geo/areas?type_code=SCEN",
  "application": "GeoNature",
  "definition": "Nom du site CEN dans lequel sont localisés les transects"
}
```
