### ISSUE TITLE
Coquille dans la t_sources

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#33]
Depuis la modale d'info de la synthèse, le lien "voir l'observation dans le module de saisie" renvoie sur une page inexistante (404). 

Un /visit est en trop dans l'url renseigné dans la t_sources.

**Comment by joelclems** [comment]
Merci donovan pour la correction de cette coquille.
il faudrait pouvoir parametrer si on renvoie sur l'observation (ce qui vaut pour la plupart des cas) ou sur la visite.
Par exemple, pour le module cheveche, on s'arrete à la visite (car il n'y a qu'une observation par visite observé ou non)

On peut rajouter un parametre dans le fichier generic/module.json (qui vaudra 'observation' pour la plupart des module sauf si on le redefini dans un module particulier ( on lui donne la valeur 'visit' pour cheveches)

**Comment by joelclems** [comment]
J'ai rajouté un paramètre `synthese_object` qui permet de specifier sur quel objet porte la synthese et qui est par défaut à     `'observation'` dans [generic/config.json](https://github.com/PnX-SI/gn_module_monitoring/blob/develop/config/monitoring/generic/config.json)

pour le module cheveche je le redefini à `'visit'`

**Comment by joelclems** [comment]
A tester

**Comment by camillemonchicourt** [comment]
Il n'y a rien à mettre à jour dans la table ``t_sources`` si on met à jour le module ?

**Comment by joelclems** [comment]
normalement non.
