### ISSUE TITLE
Problème affichage module monitorings suite à migration

### ISSUE THREAD

**Issue by CynthiaBorotPNV** [PnX-SI/gn_module_monitoring#337]
**Version**
2.14.0

**Description du bug**
Suite à la migration du module monitoring de v0.7.0 vers v0.7.2 et de Geonature de v2.13.2 vers la 2.14.0, le frontend ne charge plus rien. Une popup "Chargement en cours" s'affiche puis disparaît rapidement.
![capture-pb-module-monitoring](https://github.com/PnX-SI/GeoNature/assets/31919455/41120bbe-1aa1-4354-b125-6d19e0845251)

**Comment reproduire**
Suite à un click dans le menu de gauche sur le module monitorings

**Logs**
Nous ne retrouvons pour le moment pas de logs d'erreur liés à ce problème ni côté postgresql, ni côté apache, ni côté géonature, ni côté console du navigateur.

**Comment by camillemonchicourt** [comment]
OK, j'ai déplacé ce ticket dans le module Monitoring car cela semble plus lui qui est concerné, et pas GeoNature.
On a migré il y a quelques temps le serveur de démo GeoNature en 2.14, et le module Monitoring en version 0.7 qui fonctionne : https://demo.geonature.fr/geonature/#/monitorings

Tu as peut-être des logs dans la console du navigateur ?

**Comment by gildeluermoz** [comment]
Après échanges avec Amandine suite a une migration en GN 2.14 et monitoring en 0.7.2, la 0.7.2 comporte un bug, il faut attendre la 0.7.3.
J'ai installé la 0.7.1 avec un petit hack repris dans la 0.7.2 pour contourner un bug sur les sous modules popreptile et popamphibien.

Sinon as tu bien migré les medias. Voir notes de version de la 0.6.0 je crois

**Comment by camillemonchicourt** [comment]
Ah bon ?
C'est pas top ça. Si c'est le cas, il faut le mentionner au plus vite sur Github pour que tout le monde soit au courant.
A minima dans un ticket, éventuellement dans les notes de version de la 0.7.2 si elle a un soucis et qu'il ne faut pas l'installer.

Pouvez-vous en dire plus sur le soucis ?
@CynthiaBorotPNV, si c'est le cas je pense que tu peux rebasculer sur la 0.7.1 ou 0.7.0?

Je vais vérifier quelle version est déployée sur le serveur de DEMO.

**Comment by amandine-sahl** [comment]
A mon avis c'est un problème de permissions

**Comment by gildeluermoz** [comment]
La 0.7.2 a un soucis lors de la création d'un nouveau site. Le nx site n'est pas associé au groupe de sites.
La 0.7.1 a un soucis de compatibilité avec sql alchemy 1.4 qui est corrigé dans la 0.7.2
En attendant la 0.7.3, il faut installer la 0.7.1 et porter la partie compatibilité avec SQL alchemy 1.4 de la 0.7.2.
Je ne suis pas sur un pc pour regarder et t'indiquer la partie à reprendre mais amandine peut le faire si elle a le temps.
Et je comfirme qu'en faisant ça la 0.7.1 fonctionne avec GN 2.14

**Comment by camillemonchicourt** [comment]
De ce que j'ai compris : 
- GN 2.14 fonctionne aussi avec la 0.7.0
- La 0.7.1 a uniquement un soucis pour les nouvelles installations, pas pour les mises à jour
- Sur le serveur DEMO on est en 0.7.2 et le module fonctionne (https://demo.geonature.fr/geonature/)

**Comment by amandine-sahl** [comment]
Est ce que vous avez bien appliqué la commande :  `geonature monitorings update_module_available_permissions`

**Comment by gildeluermoz** [comment]
> GN 2.14 fonctionne aussi avec la 0.7.0

cette version n'est pas compatible avec SQL Alquemy 1.4 donc incompatible avec GN 2.14. 
Ca pose soucis normalement avec les sous-moduels POP

> La 0.7.1 a uniquement un soucis pour les nouvelles installations, pas pour les mises à jour

idem la 0.7.0 cette version n'est pas compatible avec SQL Alquemy 1.4 donc incompatible avec GN 2.14. 

> Sur le serveur DEMO on est en 0.7.2 et le module fonctionne

Tu peux faire le test qu'Amandine m'a fait faire sur le serveur de demo, sous-module apollon : tu crées un site puis tu rafrachis par un ctrl + F5, le site n'est plus rattaché au groupe de sites.

**Comment by camillemonchicourt** [comment]
> cette version n'est pas compatible avec SQL Alquemy 1.4 donc incompatible avec GN 2.14.
> Ca pose soucis normalement avec les sous-moduels POP

Non, je ne pense pas. GN 2.14 inclut le passage avec SQLA 1.4, qui reste compatible avec SQLA 1.3, donc Monitoring 0.7.0 est censé fonctionné avec GN 2.13 et 2.14.

Et en effet, @amandine-sahl a bien identifié un soucis sur les groupes de sites avec la version 0.7.2, corrigé par https://github.com/PnX-SI/gn_module_monitoring/pull/336. On prépare une 0.7.3 intégrant cette correction.

Mais le soucis de @CynthiaBorotPNV semble autre chose, car son module ne se charge pas, certainement un soucis de permissions non mises à jour comme pense @amandine-sahl.

**Comment by CynthiaBorotPNV** [comment]
> Est ce que vous avez bien appliqué la commande : `geonature monitorings update_module_available_permissions`

Bonjour Amandine, nous n'avons pas appliqué cette commande. Je teste cela dès lundi prochain. Merci à toi

**Comment by CynthiaBorotPNV** [comment]
> Est ce que vous avez bien appliqué la commande : `geonature monitorings update_module_available_permissions`

Je viens de lancer la commande et pas de changements sur l'interface web :

```
[nombreux SAWarning]
Création des permissions pour ipa_bouq : module
Création des permissions pour ipa_bouq : site
Création des permissions pour ipa_bouq : visit
Création des permissions pour ipa_bouq : observation
Création des permissions pour stom2 : module
Création des permissions pour stom2 : sites_group
Création des permissions pour stom2 : site
Création des permissions pour stom2 : visit
Création des permissions pour stom2 : site
Création des permissions pour stom2 : visit
Création des permissions pour stom2 : observation
```

**Comment by amandine-sahl** [comment]
le soucis venait bien d'un soucis de configuration des permissions des utilisateurs

**Comment by CynthiaBorotPNV** [comment]
Merci @amandine-sahl  pour le diagnostique et le soutien technique !
Les autorisations, lors de la migration du coeur et du module avait été retirées.
Nous avons réalisé cela rapidement en ligne de commande : (group id = 9)
`geonature permissions supergrant --id 9 --yes --group`
