### ISSUE TITLE
compatibilité Monitoring --> TaxHub --> GeoNature

### ISSUE THREAD

**Issue by gildeluermoz** [PnX-SI/gn_module_monitoring#340]
**Version GN 2.13.4 taxhub 1.12.1 monitoring 0.7.1**
Si `code_liste` n'est pas = à `id_liste` lors de la création d'une liste dans taxhub le module monitoring renvoie une erreur `400 BAD REQUEST`

La route consultée lors de la recherche d'un taxon dans la liste des taxons observés par le module est la suivante :

- https://mondomaine.fr/taxhub/api/taxref/allnamebylist/102?search_name=coule&limit=20

retour json :
`{"success": false, "message": "Code liste '102' inexistant"}`

Ce soucis semble corrigé dans la 1.13.1 de taxhub qui nécessite GN 2.14. Il faut donc migrer vers GN2.14 + TH 1.14 + monitoring 0.7.2 ou corriger ses `code_liste` si on reste en GN 2.13

**Comment by camillemonchicourt** [comment]
OK, on a un peu fait des allers et retours sur le sujet.
- Au départ cette route interrogeait des id_liste
- Puis on a ajouté des code_liste dans TaxHub en proposant de les privilégier
- Pour la rétrocompatibilité on a alors renseigné tous les code_liste avec les id_liste existant
- Mais cela a posé plusieurs soucis et on est revenu en arrière dans la 1.13.1 de TaxHub en effet. C'est détaillé ici : https://github.com/PnX-SI/TaxHub/issues/346

Mais il est possible qu'il faille répercuter cela dans Monitoring qui était peut-être passé sur des code_liste, mais je ne vois pas où, à vérifier.
Je vois des histoires d'id_liste ici par contre, mais je n'ai pas tout en tête : https://github.com/PnX-SI/gn_module_monitoring/blob/main/backend/gn_module_monitoring/config/generic/module.json#L78

**Comment by gildeluermoz** [comment]
non je pense que monitoring est ok et qu'il interroge bien sur `id_liste` comme tu peux le voir dans l'url utilisée.
https://mondomaine.fr/taxhub/api/taxref/allnamebylist/102?search_name=coule&limit=20 
C'est taxhub 1.12.1 qui considère que `102` est un `code_liste`. Et comme ma liste avait un `code_liste` = `REP`, taxhub ne trouve pas la liste 102 puisqu'il cherche une liste avec le `code_lite=102`
J'ai remis `102` dans `code_liste` et ça fonctionne.

**Comment by camillemonchicourt** [comment]
Ahhh oui OK j'avais pas bien lu.

OK oui, c'est justement pour ça qu'on est revenu à des id_liste pour cette route. 👍

**Comment by camillemonchicourt** [comment]
Corrigé avec TaxHub 1.13.1 en effet.
