### ISSUE TITLE
Renseigner plusieurs utilisateurs avec le composant 'users'

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#35]
Plus une question qu'un bug sans doute : quand je saisie plusieurs observateurs/descripteurs, ça ne fonctionne pas, le composant ne convient que pour saisir un seul observateur. 

Est-ce configurable quelque part, une erreur de ma part ?

**Comment by joelclems** [comment]
Je n'ai pas cette erreur. Est ce que tu redefini le composant pour ton module?

**Comment by joelclems** [comment]
Pour les sites,  le composant pour le descripteur de marche que pour une personne
