### ISSUE TITLE
Filtrer les habitats

### ISSUE THREAD

**Issue by marie-laure-cen** [PnX-SI/gn_module_monitoring#359]
Bonjour,

Je souhaiterais filtrer les habitats comme on peut le faire dans Occtax pour rester au niveau 2 d'EUNIS par exemple

J'ai repris le code dans le sous-module Lichen Bio-indicateurs :

```
"habitat_associe": {
  "type_widget": "datalist",
  "attribut_label": "Habitat naturel associé",
  "description": "Code EUNIS habitat naturel",
  "api": "habref/habitats/autocomplete",
  "application": "GeoNature",
  "keyValue": "cd_hab",
  "keyLabel": "search_name",
  "type_util": "habitat",
  "params": {
    "cd_typo": 7,
    "limit": 5000,
    "search_name": ""
  },
  "hidden": false,
  "required": false
},
```

Pour le filtre, je suppose qu'il créer une variable comme celles décrites dans la documentation :

```
__MONITORINGS_PATH
__MODULE.ID_LIST_TAXONOMY
__MODULE.MODULE_CODE
__MODULE.ID_MODULE
__MODULE.ID_LIST_OBSERVER
__MODULE.TAXONOMY_DISPLAY_FIELD_NAME
```

Qui vont dans le fichier config.json ? Il y a un autre endroit à modifier une fois la variable créée?

Dans Occtax on a :
```
[othersGetParams]="{
  cd_typo: this.config.OCCTAX?.CD_TYPO_HABITAT,
  id_list: this.config.OCCTAX?.ID_LIST_HABITAT
}"
```

=> `__MODULE.ID_LIST_HABITAT` ?

**Comment by TheoLechemia** [comment]
Bonjour,
les variables dont tu parles sont des variables lié à configuration du module qu'on peut réutiliser dans sa config json
```

__MONITORINGS_PATH
__MODULE.ID_LIST_TAXONOMY
__MODULE.MODULE_CODE
__MODULE.ID_MODULE
__MODULE.ID_LIST_OBSERVER
__MODULE.TAXONOMY_DISPLAY_FIELD_NAME
```
Il n'est pas possible d'en créer de nouvelles.
La syntaxe que tu as utilisé est la bonne. 
Est-ce qu'elle fonctionne bien ?

**Comment by marie-laure-cen** [comment]
Bonjour, merci pour ta réponse. En effet le code fonctionne bien sans essayer de rajouter le filtre mais ça en fait trop. Personne n'utilise ce champ quand il n'est pas filtré 😅. 

Du coup si j'ai tout compris les variables qu'on a ci-dessus sont liées à celles:

- qui sont définies dans le fichier `models.py` 
- et générées ensuite via `repository.py`
