### ISSUE TITLE
Affichage des noms latins dans les "display_list"

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#36]
Dans la configuration des "Display list", si on définit l'objet "cd_nom", c'est les noms vernaculaires sont ressortent. 
Est-il possible/configurable d'afficher le nom latin plutôt ? C'est du détail, mais on alimente la boite à idées :)

![Capture d’écran 2020-07-01 à 17 22 47](https://user-images.githubusercontent.com/23358384/86262024-a0d9d700-bbbf-11ea-9f48-ff64a73d4612.png)

**Comment by joelclems** [comment]
cf #18. On prend le `nom_vern` ou le `lb_nom` si `nom_vern` n'est pas présent.
ça serait possible d'ajouter un paramètre pour afficher le lb_nom en priorité

**Comment by joelclems** [comment]
J'ai rajouté une variable dans le fichier custom.json (utilisée dans config.json)
``"__TAXONOMY_FIELD_NAME": "nom_vern,lb_nom"``

on peut la redéfinir à 
 ``"__TAXONOMY_FIELD_NAME": "lb_nom"``

pour avoir toujours les noms latin.

on peut faire le changement dans `generic/custom.json` pour tous les module ou dans `<module_path>/custom.json` pour un module en particulier.

attention custom.json n'est pas commité (copier ou mettre à jour depuis generic.sample)

**Comment by joelclems** [comment]
a mieux regarder avec les derniers changements
