### ISSUE TITLE
Définition de sous-module : problème avec la valeur par défaut du cd_nom

### ISSUE THREAD

**Issue by ahurabielle** [PnX-SI/gn_module_monitoring#372]
Bonjour,

Dans les sous-modules POP développé pour la SHF, on demande à l'utilisateur s'il a observé des amphibiens (champ `presence`).
S'il indique `Oui`, l'utilisateur cherchera son taxon. S'il indique `Non`, on veut que le cd_nom soit mis à 914450 (cela correspond aux amphibiens) par défaut, automatiquement.

La configuration du fichier observation.json est la suivante :
```json
  "specific": {
    "presence": {
       "type_widget": "radio",
       "required": true,
       "attribut_label": "Avez-vous observé des amphibiens lors de la prospection",
       "values": ["Oui", "Non"],
       "value": "Oui"
    },
    "cd_nom": {
      "type_widget": "taxonomy",
      "attribut_label": "Espèce observée",
      "keyValue": "cd_nom",
      "keyLabel": "__MODULE.TAXONOMY_DISPLAY_FIELD_NAME",
      "multiple": false,
      "api": "taxref/allnamebylist/__MODULE.ID_LIST_TAXONOMY",
      "application": "TaxHub",
      "required": "({value}) => value.presence === 'Oui'",
      "type_util": "taxonomy",
      "value": 914450,
      "id_list": "__MODULE.ID_LIST_TAXONOMY",
      "hidden":"({value}) => value.presence === 'Non'"
    } ,
```

Le comportement fonctionne bien la plupart du temps : lorsque l'utilisateur choisit de saisir une observation, il arrive sur une interface, et par défaut, l'espèce est mise à "Amphibia".
![image](https://github.com/user-attachments/assets/b97b9ed8-63cb-46a1-bef6-3990fec4e3db)

Mais parfois (lors de la "première" saisie d'observation sur le module, ou après un refresh (CTRL+MAJ+R), le champ `cd_nom` ne s'initialise pas correctement.
On a alors une erreur dans la console et le champ "Espèce observée" n'est pas pré-rempli : 
`ERROR TypeError: Qt[this.displayedLabel] is undefined`
![image](https://github.com/user-attachments/assets/3098610c-ceb5-4366-9de6-740ee830df7f)

Le problème n'est malheureusement pas uniquement visuel. Si cette erreur se produit, quelque soit ce que saisit l'observateur dans le formulaire au niveau de l'espèce, la valeur ne sera pas repercutée dans la variable cd_nom.
Dans l'exemple ci-dessous, j'ai saisi "bufo bufo", j'ai validé... mais dans ma saisie, je récupère quand même la valeur "Amphibia".
![image](https://github.com/user-attachments/assets/d9e69797-25be-4622-8cd2-5a698e4b970d)
![image](https://github.com/user-attachments/assets/5ac04855-7014-4e83-8019-6692af2dd326)

En imprimant la valeur du cd_nom (grâce à la fonction change) avec le code suivant :
```json
"change": [
  "({objForm, meta}) => {",
    "console.log(objForm.value.cd_nom)",
  "}",
  ""
  ]
```
je constate que la valeur, dans le cas d'erreur, est bien mise à 914450 puis à l'objet taxonomique correspondant à 914450
![image](https://github.com/user-attachments/assets/b0d4c271-aefa-41a0-868d-4be4b29466e0)
Par la suite, même quand je modifie le formulaire, l'objet reste identique !
![image](https://github.com/user-attachments/assets/2579ddc3-dba5-4eb3-ba17-2e0c7af83e6e)

Je ne comprends pas le problème.

J'avais envisagé également de ne pas passer par le champ `value` et de fonctionner uniquement avec la fonction "change" comme dans l'issue #93 pour mettre la valeur par défaut.
Mais là aussi, j'ai un souci : dès lors que je manipule la variable cd_nom, j'ai la même erreur : 
`ERROR TypeError: Qt[this.displayedLabel] is undefined`, le cd_nom = 914450, puis les saisies de l'utilisateur ne fonctionnent plus.

Comment puis-je résoudre ce souci embarrassant ?

**Comment by amandine-sahl** [comment]
Effectivement, on ne peut pas passer de valeur par défaut au composant taxonomy. 
Pour contourner le soucis je supprimerais la clé `value` du champ cd_nom et mettrait le code suivant dans on change: 

```json
"change": [
    "({objForm, meta}) => {",
    "if ((objForm.value.cd_nom == undefined) || (objForm.value.presence == 'Non')) {",
    "objForm.patchValue({cd_nom : {'cd_nom': 914450, 'lb_nom': 'Amphibia', 'nom_valide': 'Amphibia', 'nom_vern': 'Amphibiens, batraciens'}})",
    "}",
    "}",
    ""
  ]
```

**Comment by ahurabielle** [comment]
Bonjour Amandine,

Merci pour ta réponse. Je vais procéder de la manière que tu recommandes.
Effectivement, en inscrivant les différents champs que tu mentionnes, je ne parviens pas à reproduire le problème !
Je te remercie !
