### ISSUE TITLE
Intégration massif de données - Affichage Synthèse

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#38]
Bonjour,

Je suis en train de faire des imports massifs de données à travers un script python utilisant QtSQL.
L'affichage de ces données se fait très bien sur le sous-module de destination. En revanche, toutes ces données n'apparaissent pas à la fin dans la synthèse alors qu'ils sont bien présents dans la vue... Auriez-vous une idée sur mon soucis ? Il existe peut-être un déclencheur que je n'utilise pas...

Ci-dessous les étapes de mon script :
- Insertion des sites dans la table `t_base_sites` à partir de ceux existant dans la table `l_areas`
- Insertion dans `cor_site_module` et `t_site_complements`
- Insertion dans `t_base_visits`, `t_visit_complements` et `cor_visit_observer`
- Insertion dans `t_observations` et `t_observation_complements`

**Comment by camillemonchicourt** [comment]
OK super intéressant.
En effet il y a une vue à mettre en place pour chaque protocole de suivi pour alimenter la Synthèse depuis les données d'un protocole. Documenté ici : https://github.com/PnX-SI/gn_module_monitoring#synchronisation-avec-la-synthese
Discuté sur https://github.com/PnX-SI/gn_module_monitoring/issues/14

Au final je ne sais plus si les fonctions sont exécutés par un trigger (auquel cas ça devrait fonctionner dans ton cas où tu alimentes directement la BDD), ou si c'est lancé au niveau applicatif (auquel cas ça sera lancé que si on passe par l'application).

@joelclems, tu peux préciser comment l'alimentation Monitoring > Synthèse est lancée ?

**Comment by amandine-sahl** [comment]
La fonction d'import dans la synthèse est lancée de façon programatique en python mais c'est une fonction sql.

Pour executer la fonction d'import des données dans la synthèse il faut utiliser la commande sql suivante : 
```
gn_synthese.import_row_from_table(
    select_col_name character varying, -- nom de la colonne identifiant la donnée
    select_col_val character varying, -- valeur de l'identifiant de la donnée
    tbl_name character varying -- nom de la vue de synthese du module monitoring
)
```

Pour forcer la mise à jour de l'ensemble des données il faut mettre '%' comme valeur de select_col_val. Par contre attention cela peut être long et la fonction n'est pas optimisée pour de gros volume de données.
exemple : `SELECT gn_synthese.import_row_from_table('unique_id_sinp', '%', 'gn_monitoring.ma_vue_synthese')`

**Comment by LPOMaximeToma** [comment]
@camillemonchicourt @amandine-sahl 

Merci beaucoup pour vos retours !
J'ai essayé la fonction `SELECT gn_synthese.import_row_from_table('unique_id_sinp', '%', 'gn_monitoring.vs_comptage_rnmo')` sur mes 10000 données. Elle me retourne `True` mais les données ne sont quand même pas présentes dans la synthèse. Après l’exécution de la requête n'a pris que 68 ms. Je vous joins un extrait imagé de ma vue et du code de celle-ci (au cas où le problème pourrait venir d'ici?):

![image](https://user-images.githubusercontent.com/66769358/91154648-09c26480-e6c2-11ea-86ff-d0a57c9318dc.png)

![image](https://user-images.githubusercontent.com/66769358/91154996-85241600-e6c2-11ea-9aea-9930488fba75.png)
![image](https://user-images.githubusercontent.com/66769358/91155041-9705b900-e6c2-11ea-8c2f-489dc33adfd2.png)

`nombre_individu` est un champ perso du sous-module.

**Comment by amandine-sahl** [comment]
Effectivement ça ne pouvait pas marcher désolée. La fonction selectionne les données à importer en faisant la requete suivante : `WHERE select_col_name::text =  select_col_val` et non pas avec une fonction de type like

La commande suivante devrait fonctionner (au vu de l'apperçu des données) : 
`SELECT gn_synthese.import_row_from_table('id_souce', '7', 'gn_monitoring.vs_comptage_rnmo')`

**Comment by maximetoma** [comment]
Merci beaucoup, ça marche ! Mais moins sur 10000 données effectivement:

![image](https://user-images.githubusercontent.com/66769358/91159548-80626080-e6c8-11ea-80b7-c062035aa41f.png)

J'ai testé sur 1000 données et c'est bon :
![image](https://user-images.githubusercontent.com/66769358/91159392-50b35880-e6c8-11ea-9575-04ff36a5ce35.png)

**Comment by camillemonchicourt** [comment]
A indiquer dans la documentation que la fonction est lancée au niveau applicatif mais qu'on peut la lancer directement en BDD si besoin et comment ?
Merci.

**Comment by Mounir-jelassi** [comment]
Bonjour,
J'ai voulu charger les observations du module popAmphibien dans le synthèse. le chargement directement sur la base fonctionne bien mais à partir de l'application ne se lance pas automatique. Sachant que je suis toujours sur la version 2.4.1 de Geonature ,  j'ai ajouté la vue au module et j'ai affecté le __SYNTHESE à true. Est ce que je peux savoir dans quel morceau de code python se lance le chargement automatique?

**Comment by joelclems** [comment]
Bonjour Mounir,

après un import manuel la mise des données dans la synthèse n'est pas automatique
tu peux lancer la commande SQL
SELECT gn_synthese.import_row_from_table('id_module', '<id_du module popAmphibien>', 'gn_monitoring.<nom de ta vue>')

cela met les données de ton module dans la synthèse

Pour le changement automatique cela se passe dans le fichier backend/monitoring/repositories.py
dans la fonction process_synthese (appellée lors d'une création ou d'une modification)

Je vais bientôt sortir la version 2.0 (je regarde ta PR pour la mettre dedans) (qui marchera avec la 2.5) la configuration est un peu différente.

**Comment by camillemonchicourt** [comment]
La méthode pour lancer manuellement l'intégration dans la Synthèse des données historiques d'un module Synthèse a été ajoutée dans la doc ?

**Comment by joelclems** [comment]
Il y a un enorme boutton mettre a jour la synthese sur la page du module en mode administrateur

**Comment by camillemonchicourt** [comment]
Ah OK, du coup plus besoin de lancer en SQL

**Comment by joelclems** [comment]
J'ai documenté les deux
