### ISSUE TITLE
Bastien & Scapin NS - Monitoring : Chemin d'une partie

### ISSUE THREAD

**Issue by Angelique-NS** [PnX-SI/gn_module_monitoring#39]
Lorsqu'on se trouve sur dans une des partie de monitoring (ex : STOM), le site indique ce chemin: "Home / Module / STOM" 

Afin d'améliorer la compréhension, il serait cohérent de remplacer "Module" par "Monitoring".

**Comment by joelclems** [comment]
Le comportement normal est  <icon home> / Module : <module_name> / Site : <base_site_name> / Visite : <date> / Observation
