### ISSUE TITLE
No module named 'geonature.core.gn_synthese.utils.process'

### ISSUE THREAD

**Issue by ksamuel** [PnX-SI/gn_module_monitoring#45]
En essayant d'installer gn_module_monitoring, j'obtiens:

```bash
geonature install_gn_module /tmp/gn_module_monitoring-0.1.0/ monitorings
/home/geonatureadmin/geonature/backend/venv/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
checking file
...ok


checking manifest
...ok


Checking file conformity
      install_gn_module  OK
No module named 'geonature.core.gn_synthese.utils.process'


Error while installing GN module .The process returned:
	Module MONITORINGS
                    File /tmp/gn_module_monitoring-0.1.0/backend/blueprint.py must have a variable call :
                        blueprint instance of Blueprint
```

Version n_module_monitoring: 0.1.0 ou master.
Version geonature : 2.3.1 .

**Comment by camillemonchicourt** [comment]
De mémoire la version 0.1.0 du module nécessite GeoNature 2.4.1 et le manifest semble le confirmer : https://github.com/PnX-SI/gn_module_monitoring/blob/0.1.0/manifest.toml

**Comment by joelclems** [comment]
C'est bien le cas, le  fichier geonature.core.gn_synthese.utils.process est présent à partir de la version 2.4.1 https://github.com/PnX-SI/GeoNature/blob/2.4.1/backend/geonature/core/gn_synthese/utils/process.py

**Comment by ksamuel** [comment]
Parfait, je fais mon update. Merci.

**Comment by camillemonchicourt** [comment]
Ce qui est étonnant c'est que le manifest n'ait pas bloqué l'installation du module.

Je l'ai indiqué dans les notes de version (https://github.com/PnX-SI/gn_module_monitoring/commit/594abcf38c945bd20d0a7b7744973f9100e765a0) et dans la release (https://github.com/PnX-SI/gn_module_monitoring/releases/tag/0.1.0)
