### ISSUE TITLE
Améliorer le temps de chargement des données

### ISSUE THREAD

**Issue by joelclems** [PnX-SI/gn_module_monitoring#46]
Le temps de chargement peut être long pour un nombre relativement réduit de données.
Voir quelle sont les possibilités d'amélioration:
- [x] : travail sur le chargement des géométries
  - [x] : récupérer la géométrie au format json directement depuis le sql ou depuis la requête sqlachemy

**Comment by jbdesbas** [comment]
Pour une vingtaine de sites, le geojson met près de 3 secondes à être généré par le serveur. Je n'ai pas de requêtes de plus de 1 sec loguée, donc c'est bien côté python que ça bouchonne.
J'ai environ 2000 sites ponctuels à intégrer, mais à partir de 100 je commence à avoir des timeout.

**Comment by joelclems** [comment]
ça reste un des gros points noirs du module, je pense qu'il y a quelque chose à jouer dans la serialisation ou dans le module utils_flask_sqla_geo
je regarde ça demain en détail
c'est des points ou des polygones?

**Comment by jbdesbas** [comment]
Salut,
Il s'agit bien de points. Après quelques tests, ca semble bien être la sérialisation qui coince. Je suis toujours intrigué par la différence entre mon serveur et le serveur de demo. Le matériel n'est peut-être pas le même, mais ça fait une sacrée différence.

Si ca peut t'aider, voici ce que j'ai relevé de mon côté : 
sérialisation d'un site : 0,08 sec (temps entre le début et la fin de fonction serialize() )
Dont environ 50% (0.04 sec) du temps sur la récupération des valeurs d'attributs. (pas encore de notion de géometrie il me semble)
https://github.com/PnX-SI/gn_module_monitoring/blob/a5546226792b06f65cf32e71de7531a3929c9f2a/backend/monitoring/serializer.py#L108-L112

**Comment by joelclems** [comment]
En mettant le nez dans les requêtes, j'ai pu décéler pas mal de problèmes

- le fait de passer une partie le config en base dans `t_module_complements` et de verifier la date de modification de cette table engendrait une requete à chaque appel de la config du module en backend
  - c'est résolu verifiant la config seulement une fois par api, au début de l'appel

- il restait pas mal de sous-requetes, cela à pu être résolu en: 
  - mettant au maximum de `lazy='joined'` (pour les realtions comme observers, datasets, medias, ...) (sauf pour les relation *enfants* comme sites visites observations, ...
  - les colonnes hybride générait aussi des sous requetes (last_visit, nb_visits, nb_observation)
    - elles sont remplacées par des `column_property` https://docs.sqlalchemy.org/en/13/orm/mapped_sql_expr.html

https://github.com/PnX-SI/gn_module_monitoring/blob/17910b3ba989ced63caa2e0b53c9555b800b1bfb/backend/monitoring/models.py#L209-L217

   - Les `column_property` sont accessible avec `as_dict` de la classe `serializable`, les propriétés hybrides non.

- avec `column_property` on peut directement récupérer la geométrie au format geojson depuis la base ce qui pourrait accélérer les requetes

https://github.com/PnX-SI/gn_module_monitoring/blob/17910b3ba989ced63caa2e0b53c9555b800b1bfb/backend/monitoring/models.py#L219-L223

@jbdesbas est ce que ces modifications te permettent de faire les requetes sur ton serveur?

je n'ai pas changé `getattr` en `self._model.__dict__.get` parce que j'ai des `relationships` dans la liste (`medias` `observers` `datasets`, ...) mais normalement cette partie du code ne génère plus de sous-requetes

de mon coté ça me fait des reponse de 1Mo pour 2000 sites, il y a peut être des pistes pour gagner au niveau de la taille des données

**Comment by camillemonchicourt** [comment]
Super bravo pour ces optimisations !

**Comment by jbdesbas** [comment]
Salut @joelclems 
Ca fait une sacré différence avec le dernier commit https://github.com/PnX-SI/gn_module_monitoring/commit/17910b3ba989ced63caa2e0b53c9555b800b1bfb : pour les 20 sites, la requête abouti en 300ms :rocket:  (contre 2~3 sec :turtle:  avant), bien joué ! 
(Pour appliquer le commit, j'ai dû rajouter une colonne _id_sites_group_ dans la base)

La taille des réponses peuvent être considérablement réduites (80~90%) en ajoutant une compression des fichiers json dans apache (cf https://github.com/PnX-SI/GeoNature/issues/560#issuecomment-639445124 )

Je test avec les 2000 sites et je te fais un retour.

Petite curiosité, la route permettant de charger la liste des sites est appelé 2 fois par le frontend : 
![image](https://user-images.githubusercontent.com/6163107/96102973-6b8b9780-0ed7-11eb-97d3-35922f79cd52.png)

**Comment by joelclems** [comment]
C'est qu'on appelle le module en tant qu'objet pour les detail et les listes
et on l'appelle pour les sites (si par exemple on arrive directement sur une page d'un site d'une visite etc..)
il y a clairement des amélioration à faire de ce côté là

**Comment by joelclems** [comment]
il y a aussi une modification du front à prendre en compte dans le dernier commit

**Comment by jbdesbas** [comment]
800 ms pour les 2000 sites :ok_hand: 
Merci encore pour ton travail et ta réactivité !
