### ISSUE TITLE
Ergonomie - Ne scroller que la partie formulaire

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#5]
Ça serait idéal que la carte fasse tout le 100% de hauteur de la page et que l'on scrolle que dans le formulaire pour éviter ce genre d'affichage : 

![image](https://user-images.githubusercontent.com/4418840/78585293-e2b1e600-7839-11ea-8081-78769bb63a40.png)

Idem pour les listes. Ne scroller que dans la liste. 

En passant, il y a un <> qui traine en bas à gauche de la page.

**Comment by joelclems** [comment]
Merci Camille pour les remarques, 
fait dans 5cdc0b32e97b5be476e1fdf274ef283f7d508531
