### ISSUE TITLE
Widget Taxonomy et URL taxhub

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/gn_module_monitoring#50]
Bonjour,

Je n'arrive pas à utiliser l'objet Taxonomie. L'url utilisé pour avoir les taxons depuis Taxhub est https://mon_url_taxhub/api/taxref/allnamebylist/**undefined**?search_name=myo&limit=20
L'identifiant de la liste de taxon est _undefined_
Il me semble pourtant l'avoir correctement indiqué dans le schema : 
https://gist.github.com/jbdesbas/c440300c301d73a24314e4a6c41a9ac1#file-observation-json-L3-L8

Une idée ?

**Comment by joelclems** [comment]
tu es sur quelles versions(GN et monitoring)?

**Comment by joelclems** [comment]
tu peux essayer 
`"id_list": "100"`

ou mieux si tu es dans la dernière version (develop bientot 0.2..0)
`"id_list": "__MODULE.ID_LIST_TAXONOMY"`
et choisir cette liste depuis l'edition du module

**Comment by jbdesbas** [comment]
GN 2.5 et monitoring 0.1.1dev
Nickel avec "id_list" à la place de idComponent !
