### ISSUE TITLE
Valeur par défaut nomenclature

### ISSUE THREAD

**Issue by jbdesbas** [PnX-SI/gn_module_monitoring#53]
Salut,
Il serait intéressant de pouvoir définir une valeur par défaut dans le schéma pour les widgets nomenclatures. (ou si c'est déjà possible, je n'ai pas trouver comment faire ?)

**Comment by joelclems** [comment]
j'ai bossé sur un composant plus global qui s'appelle datalist et qui peut faire ce genre de choses (aussi filtrer les nomenclatures par code et donc avoir une sous liste) il faut que je documente mais ça donnerai ça en configuration
```
    "id_nomenclature_type_site": {
      "type_widget": "datalist",
      "attribut_label": "Type site",
      "api": "nomenclatures/nomenclature/TYPE_SITE",
      "application": "GeoNature",
      "keyValue": "id_nomenclature",
      "keyLabel": "label_fr",
      "data_path": "values",
      "type_util": "nomenclature",
      "required": true
    },

```

**Comment by jbdesbas** [comment]
Ok, c'est tout simplement génial et très riche de possibilités ! :1st_place_medal: 
Merci pour ce travail :+1:

**Comment by camillemonchicourt** [comment]
Monitoring c'est 🚀 !
