### ISSUE TITLE
Cannot find module '../module.config' lors de l'installation de sous modules

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#56]
Lors de l'installation de sous-modules, (test, chronocapture, stom, cheveche) lors du build du frontend, l'erreur "Cannot find module '../module.config' est retournée.  

dans app/services/config.services.ts la config est bien importée depuis ../module.config.ts mais effectivement, aucun fichier module.config.ts visible.

**Comment by DonovanMaillard** [comment]
Hm, sans doute un soucis sur mon installation (vm en local), je n'ai pas eu ce soucis sur une autre installation... désolé !

**Comment by JeromeMaruejouls** [comment]
SERVEUR EN 2.7.5 et module en 0.2.7

Bonjour à tous. Je réouvre ce ticket : Je viens d'avoir le même message sur mon serveur de prod. Les modules monitoring (test, popreptiles et popamphibiens) fonctionnaient correctement. J'ai recompilé le front end pour un autre besoin. Et je me retrouve avec l'erreur de ce module introuvable.

Le serveur devant rester accessible, j'ai désactiver le module monitoring en supprimant les liens symboliques (external_modules et frontend/assets).

Une idée de la cause de cette erreur et de comment la résoudre ?

En vous remerciant.
