### ISSUE TITLE
base_site_description fonctionnel ? 

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#58]
Je vois dans la table t_base_site un champs "base_site_description". 

J'ai paramétré une variable non spécifique "base_site_description" dans mon site.json, mais je n'ai rien trouvé dans le champs. Et aucun widget base_site_description n'est mentionné dans la doc pour le moment.

**Comment by joelclems** [comment]
Effectivement ce champs est passé à la trappe et n'est pas defini dans generic/site.json 

Je fait un commit pour le rajouter dans le ficher generic/site.json

(dans ton cas il est considéré comme une variable spécifique au module et stocké dans la variable data jsonb)
