### ISSUE TITLE
Edit site - Marker ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#6]
Le marqueur utilisé sur l'outil carto pour localiser un site est différent des autres modules de GeoNature. Son icône m'a d'ailleurs fait penser à "Dessiner un cercle". Utiliser plutôt le marqueur de Occtax ? Qui ne nécessite pas de bouton d'édition en plus.

L'édition actuelle a des bugs : 

![image](https://user-images.githubusercontent.com/4418840/78585666-88655500-783a-11ea-908a-11281efc04c2.png)

**Comment by joelclems** [comment]
fait dans 948faa9

**Comment by camillemonchicourt** [comment]
OK vu sur votre serveur de démo. Je pense que c'est mieux, mais idéalement j'utiliserai exactement le même fonctionnement et le même marker que dans Occtax, sans bouton modifier, pour une meilleure cohérence entre les modules. 
Le bouton EDIT / SAVE / CANCEL ajoute de la complexité et j'ai encore des bugs : 

![image](https://user-images.githubusercontent.com/4418840/78713837-2892ab00-791b-11ea-890d-49903a7feac0.png)

Dans Occtax, il suffit de déplacer le marker ou de recliquer ailleurs pour modifier la localisation, et c'est idéal selon moi.
