### ISSUE TITLE
Utilisation "filter" dans la configuration json

### ISSUE THREAD

**Issue by DonovanMaillard** [PnX-SI/gn_module_monitoring#60]
Bonjour, 

J'ai configuré un sous-module pour nos suivis par tente malaise et autres pièges fixes. 

Je voudrais filtrer une liste de nomenclatures, j'ai vu que c'était prévu dans la doc. Mais (en tous cas avec ma conf) ça ne semble pas fonctionner. La configuration du widget est la suivante : 

```
"id_trap_type": {
      "type_widget": "datalist",
      "attribut_label": "Type de piège",
      "api": "nomenclatures/nomenclature/METH_OBS",
      "application": "GeoNature",
      "keyValue": "id_nomenclature",
      "keyLabel": "label_fr",
      "data_path": "values",
      "type_util": "nomenclature",
      "required": true,
      "default": {
        "cd_nomenclature": "52"
        }, 
      "filter" : {
        "cd_nomenclature":["52","53","73"]
        }
```

Il est bien probable que le soucis vienne de moi, je n'ai pas trouvé d'autres nomenclatures filtrées dans les autres modules déjà partagés. Avez-vous des pistes ? Merci d'avance !

**Comment by joelclems** [comment]
Bonjour donovan

il y a une coquille dans la doc et ce n'est pas filter mais filters avec un s

je pense que tu renseigne les id_nomenclature et non les cd_nomenclature (qui vont de 0 a 27)

**Comment by DonovanMaillard** [comment]
Salut Joel, merci pour ta réponse, 

Je rectifie donc ce s dans le sous-module, 

C'est bien les cd_nomenclatures dans mon fichier, mais il s'agit de nomenclatures filles de "VU" que nous avons créées en interne. Je l'ai signifié dans la doc, à cause de ca le sous-module ne peut pas être déployé tel quel dans d'autres instances, il y a uniquement ce point à modifier dans la conf du module et la vue synthèse.

**Comment by joelclems** [comment]
tu peux renseigner les nomenclature dans le fichier nomenclature.json et elles seront insérée si elle n'existent pas (s'il n'y a pas de nomenclaure avec le meme (cd_nomenclature, id_type)) à l'installation du module.

**Comment by DonovanMaillard** [comment]
C'est tout bon pour les filtres ! merci!

Actuellement c'est le type "technique d'observations" directement qui est en place, car on a mis nos différentes méthodes d'observations dans ces nomenclatures là. Mais ca vient injecter des nomenclatures qu'il faut gérer lors des exports inpn car elles ne sont pas dans le standard. 

Le plus propre serait de faire un type nomenclature dédié (ou vérifier si ce n'est pas déjà dans les anciennes nomenclatures "technique d'observation"). De tout rattacher à "VU" par défaut, et de faire cette modif seulement chez Flavia sur notre vue synthèse. 
A prévoir dans une prochaine mise à jour pour virer ce cas particulier ...

**Comment by camillemonchicourt** [comment]
OK corrigé dans la doc : https://github.com/PnX-SI/gn_module_monitoring/commit/46ddb0fe89e345755cc251602b26249e637cce37
