### ISSUE TITLE
Problème sur le CRUVED ? Rendre invisible certains sous-moodules

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#66]
Bonjour, je fais suite à mon ticket général https://github.com/PnX-SI/GeoNature/issues/1170.

Il me semblait qu'avant on pouvait masquer certains sous-module pour tels ou tels groupes/utilisateurs mais je n'arrive plus à le faire avec cette nouvelle version.

Est-ce que le problème viendrait de chez moi ? (Je mets toutes les actions à 0 si jamais)

**Comment by camillemonchicourt** [comment]
Vu avec @joelclems, cela n'a jamais été mis en place.
Mais pour la liste des sous-modules du module Monitorings, on pourrait ne les afficher que le R du CRUVED sur le sous-module est supérieur ou égal à 1.

Ainsi pour qu'un utilisateur ou groupe d'utilisateur n'ait pas accès à un sous-module du module, il faudrait lui surcoucher le CRUVED sur le sous-module en lui mettant le R à 0.

**Comment by joelclems** [comment]
Idéalement il faudrait aussi tester les JDD associés au module, si il ne recoupent pas ceux de l'utilisateur on n'affiche pas ce module (d'ailleur tout le travail sur l'accès aux données par rapport aux jdd auquels l'utilisateur à droit reste à faire). On peut profiter de cette issue pour afiner la définition des besoin

**Comment by maximetoma** [comment]
Ah okay, il me semblait avoir pu le faire en mettant effectivement le R à 0 sur l'ancienne version, mais c'est peut-être ma mémoire qui me joue des tours... @camillemonchicourt @joelclems mais en gros oui c'est l'idée :)

**Comment by camillemonchicourt** [comment]
> Idéalement il faudrait aussi tester les JDD associés au module, si il ne recoupent pas ceux de l'utilisateur on n'affiche pas ce module (d'ailleur tout le travail sur l'accès aux données par rapport aux jdd auquels l'utilisateur à droit reste à faire).

Je ne pense pas. On peut pouvoir accéder à un module pour consulter les données par exemple, sans avoir de lien avec aucun JDD du sous-module.

Les liens avec les JDD concernent les droits sur les données d'un sous-module, pas sur l'accès ou non au sous-module.

Et je garderai la même logique que pour les modules. Leur affichage ou non dans la barre de navigation est conditionné par un R supérieur à 0 sur le module pour l'utilisateur connecté.

Donc je ferai pareil pour les sous-modules.

**Comment by maximetoma** [comment]
Réglé dans une mise à jour : https://github.com/PnX-SI/gn_module_monitoring/releases/tag/0.2.2
