### ISSUE TITLE
[MAJ 0.2.1] Problème lors de l'update_configuration (Cannot find module 'protractor')

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#69]
Bonjour,

Faisant la MAJ vers la version 0.2.1, je suis confronté à un problème lors de l'update de la configuration mais je ne sais pas trop comment le résoudre...

![image](https://user-images.githubusercontent.com/66769358/104888966-c4068100-596d-11eb-8930-ee3ab905dabe.png)

-->[2021-01-18T08_07_35_501Z-debug.log](https://github.com/PnX-SI/gn_module_monitoring/files/5828732/2021-01-18T08_07_35_501Z-debug.log)

Merci d'avance pour votre aide,
Maxime

**Comment by joelclems** [comment]
Bonjour Maxime, quelle est ta version de GéoNature ?

**Comment by maximetoma** [comment]
Bonjour @joelclems 
Ah oui j'ai oublié de dire, je suis en 2.5.5

**Comment by joelclems** [comment]
Est ce que si tu execture la commande dans geonature/frontend
```
npm install ngx-mat-select-search
```
ça regle le probleme ?

**Comment by maximetoma** [comment]
Oui, la MAJ s'est bien installée merci beaucoup !
Me manque juste la MAJ des vues où le script s'est figé au bout de la deuxième vue mais ça vient peut etre de moi

**Comment by joelclems** [comment]
il faudrait indiquer de lancer `npm install <gn_module_monitring>/frontend/package.json`

mais comme ce composant n'est pas utilisé.... le mieux serait de refaire la release avec la correction

la commande 
```<gn_module_monitring>/update_views.sh <GeoNature>/config/settings.ini```
permet de récreer les vues (de jouer tous les fichiers synthese.sql présents dans le dossier des sous-modules

**Comment by maximetoma** [comment]
Ah en lançant la commande j'ai un message d'erreur équivalent pour chaque sous-module:
![image](https://user-images.githubusercontent.com/66769358/104917092-3f2e5e00-5993-11eb-9ac0-02a25464bd13.png)

**Comment by joelclems** [comment]
Désolé pour l'erreur

La commande est:
```
<gn_module_monitring>/update_views.sh <GeoNature>
```

**Comment by maximetoma** [comment]
Merci c'est marche !
Enfin j'ai toujours un blocage sur ma deuxième vue pourtant elle est copiée de la précédente...
![image](https://user-images.githubusercontent.com/66769358/104918478-1e670800-5995-11eb-8690-9b2cf68d8317.png)
