### ISSUE TITLE
Erreur de frappe doc - maj

### ISSUE THREAD

**Issue by Idaline** [PnX-SI/gn_module_monitoring#70]
Bonjour,

Dans la doc de mise à jour : 

for f in $(ls /home/`whoami`/gn_modudule_monitoring/config/monitoring/*/img.jpg); do
   module_path="$(dirname $f)"
   ln -s $f /home/`whoami`/gn_modudule_monitoring/fronted/assets/${module_path##*/}.img
done

Remplacer modudule par module, et fronted par frontend

Remplacer .img par .jpg ?

**Comment by maximetoma** [comment]
Erreur sur la doc pour taxonomy: cf. https://github.com/PnX-SI/gn_module_monitoring/issues/68#issuecomment-763589787
