### ISSUE TITLE
Erreur 500 pour les observateurs uniques (visites)

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#71]
Bonjour,

Je suis confronté à une erreur 500 (internal server error) lorsque je veux valider une visite avec le champ "observers" ayant le paramètre `multiple: false` au lieu de `multiple: true`.
![image](https://user-images.githubusercontent.com/66769358/106145086-66481500-6175-11eb-9ce7-70a09f7b3d76.png)

    "observers": {
      "type_widget": "datalist",
      "attribut_label": "Déterminateur",
      "api": "users/menu/__MODULE.ID_LIST_OBSERVER",
      "application": "GeoNature",
      "keyValue": "id_role",
      "keyLabel": "nom_complet",
      "type_util": "user",
      "multiple": false,
      "required": true
    },

**Comment by joelclems** [comment]
cela doit poser probleme car il s'attend à avoir un tableau
ce n'est pas possible en l'état
il faudrait soit 
- dans le options de datalist pouvoir rajouter une contrainte nbMax pour limiter le nombre de choix
- soit le traiter en backend et traiter le cas ou l'on a une id et non un tableau

**Comment by maximetoma** [comment]
Ah okay d'accord ! 
Oui c'est différent par rapport à l'utilisation de la datalist sur les observations (ou sites) où là le `multiple: false` marche
Je ne sais pas, par contre, laquelle des ces propositions et la plus optimisée 

Mais concernant l'ancienne variable "utilisateur", elle proposait un unique observateurs non ? Elle n'est plus compatible avec le nouveau monitoring ?

**Comment by joelclems** [comment]
pour les site, il s'agit du composant pour id_inventor, qui recupere un id_role, ce composant est à (multiple: false, en fait non défini mais c'est à false par defaut)

- la premiere option nécessite un changement dans GN c'est un peu plus lourd à mettre en place mais ce serait bien et pour une portée plus large
- la deuxième revient à changer la gestion des correlations pour monitoring dans le backend, et à s'adapter au cas ou l'on a une donnée simple et non un tableau d'id (dans ce cas on peut transformer cette donnée en un tableau de un éléments), ça fat un peu plus bricolage mis c'est intéressant aussi

je manque de temps en ce moment mais je pourrais regarder en fin de semaine

**Comment by maximetoma** [comment]
Okay , merci pour toutes ces précisions ! pas de soucis
