### ISSUE TITLE
[MAJ 0.2.2] Nouvelle gestion des permissions: affichage pour l'utilisateur

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#78]
Bonjour !

Merci beaucoup pour cette nouvelle mise à jour du module :)

J'ai cependant quelques soucis de manipulations avec le CRUVED:
Je cherche du coup à faire 2 choses:
- Rendre visible ou non les sous-modules dans l'interface principale du module selon l'utilisateur
- Ou rendre visible ou non les sites selon les utilisateurs
Est-il possible de le faire ? Si oui, en faisant quelles manœuvres avec la nouvelle gestion des perms ?
Merci d'avance

Maxime

**Comment by amandine-sahl** [comment]
Pour l'instant l'implémentation du cruved reste partielle. La notion de portée n'est pas gérée ce sera la prochaine étape.

Ce qui peut être fait actuellement se limite à pouvoir définir finement les actions de l'utilisateur, par sous-module et type d'objet (sites, visites, ...).

**Comment by camillemonchicourt** [comment]
Pour masquer un sous-module à un utilisateur ou groupe d'utilisateurs, je pense qu'il faut que tu mettes le R du CRUVED à 0 pour ce sous-module, pour le groupe (ou utilisateur) concerné.

**Comment by maximetoma** [comment]
@amandine-sahl Okay pas de soucis
@camillemonchicourt J'ai essayé mais je le sous-module s'affiche toujours

**Comment by amandine-sahl** [comment]
Effectivement il semble qu'il y ai un soucis d'héritage des permissions

**Comment by maximetoma** [comment]
Cela viendrai de mon côté ?

**Comment by maximetoma** [comment]
Bonjour @amandine-sahl,

Je n'avais pas encore vu tes modifications sur la branche develop ! J'ai fait cette modification de mon côté manuellement et effectivement ça fonctionne !!! Merci beaucoup :D

A modifier donc pour une prochaine release j'imagine !

**Comment by camillemonchicourt** [comment]
A priori corrigé dans la version 0.2.3 : https://github.com/PnX-SI/gn_module_monitoring/releases ?

Je suis un peu perdu avec ce qui est implémenté ou non dans ce module au niveau des permissions.
A préciser et indiquer dans la documentation des permissions du module que l'on peut afficher ou non un sous-module en fonction du CRUVED de l'utilisateur (https://github.com/PnX-SI/gn_module_monitoring#permissions) ?
