### ISSUE TITLE
Type widget/Type utils HABITAT (question)

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#79]
Bonjour,

J'ai vu dans le code qu'il est fait mention du type_util `habitat` et je voulais savoir si il existait un type_widget du même nom qui lui serait associé et fonctionnel dans la dernière MAJ de monitoring ?
Et si oui, quels serait les éléments à renseigner ?

Merci d'avance et bonne aprèm
Maxime

**Comment by joelclems** [comment]
Salut Maxime,

la PR de mounirjelassi propose un module avec un composant habitat (en datalist)

https://github.com/PnX-SI/gn_module_monitoring/pull/75/files#
fihcier site.json

```
    "habitat_a":{
      "type_widget": "datalist",
      "attribut_label": "Habitat Eunis côté A",
      "api": "habref/habitats/autocomplete",
      "application": "GeoNature",
      "keyValue": "cd_hab",
      "keyLabel": "search_name",
      "type_util": "habitat",
      "params": {
          "cd_typo": 7,
          "search_name": ""
      }
    },
      "habitat_b":{
        "type_widget": "datalist",
        "attribut_label": "Habitat Eunis côté B",
        "api": "habref/habitats/autocomplete",
        "application": "GeoNature",
        "keyValue": "cd_hab",
        "keyLabel": "search_name",
        "type_util": "habitat",
        "params": {
            "cd_typo": 7,
            "search_name": ""
        }
      },
```

**Comment by maximetoma** [comment]
Ah oui d'accord ! C'est vrai, je n'ai pas pensais à regarder de ce côté-là... Merci ! :)
