### ISSUE TITLE
Position des boutons ANNULER et ENREGISTRER

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#8]
Je propose de mieux séparer les boutons en les déplaçant : 

![image](https://user-images.githubusercontent.com/4418840/78586442-bd25dc00-783b-11ea-87a1-d5f9673d9e8b.png)

**Comment by joelclems** [comment]
fait dans 47fede3967c35706213efe23756ac396960b01bf
