### ISSUE TITLE
Problème exécution du sous module

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_module_monitoring#81]
J'ai installé le module de suivi generique et installé un sous module en me basant sur le sous module test donné.
L'installation du module suivi et sur sous module c'est déroulé sans erreur.
Pourtant cela ne fonctionne pas si je vais dans le module monitorings de geonature.
Dans les logs j'ai le message suivant :
Exception on /monitorings/modules [GET]
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/decorators.py", line 88, in __check_cruved_scope_monitoring
    cruved = cruved_scope_for_user_in_monitoring_module(module_code)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/decorators.py", line 55, in cruved_scope_for_user_in_monitoring_module
    append_to_select=append,
TypeError: cruved_scope_for_user_in_module() got an unexpected keyword argument 'append_to_select'
[2021-04-20 16:08:33 +0200] [12855] [ERROR] 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Pourquoi j'ai ce message : got an unexpected keyword argument 'append_to_select'
j'ai rajouté pour être sûr la variable curved avec comme valeur : "cruved": {"C": 3, "U": 3, "D": 3},

Que dois-je faire pour que cela ne fonctionne ?

J'avais fait une première installation sans la variable mais j'avais la même erreur. J'ai tout repris depuis un dump complet de la base et le répertoire initial de geonature. Sans effet visiblement.

j'ai une autre question : la commande suppression de module est elle effective ? j'avais vu que le sous module n'existait plus dans le répertoire geonature après commande hors j'avais toujours l'erreur même après reconstruction du front end.

Christian Bièche
Cistude Nature

**Comment by christianbieche** [comment]
Les fichiers json configures pour le sous module sentinelle

[mod_sentinelle.zip](https://github.com/PnX-SI/gn_module_monitoring/files/6344318/mod_sentinelle.zip)

**Comment by joelclems** [comment]
Bonjour christian
quelle version de geonature utilises tu ?

**Comment by christianbieche** [comment]
Oups j'ai oublié de le mettre la 2.5.5 qui est à priori celle requise.

**Comment by joelclems** [comment]
il y a une erreur avec les fichier manifest Il faudrait essayer avec la version 2.6.2

l'erreur viendrait de la function 
 `cruved_scope_for_user_in_module()`
qui n'accepte pas l'argument `append_select` mais qui doit marcher avec la dernière version de geonature (2.6.2)

**Comment by christianbieche** [comment]
oui c'est bien cette fonction. Le problème est que je suis en 2.5.5 et s'il faut que je passe en 2.6.2. Il faudra que je remette ensuite à jour mon serveur de prod que je viens juste d'adapter et visiblement sans garantie aucune de fonctionnement.
Est ce qu'il n'y pas un moyen de contourner ? et comment on fait les autres utilisateurs ?

**Comment by christianbieche** [comment]
je viens d'expérimenter des problèmes avec les applications mobiles en changeant de version donc je ne suis pas très chaud pour la manip.

**Comment by christianbieche** [comment]
d'ailleurs dans le même ordre d'idée. j'ai l'impression qu'une fois le module installé, la modification et la suppression des sous modules ne sont pas triviales. Sans parler des modifications de base si on a ajouté des données complémentaires ....

**Comment by joelclems** [comment]
pour contourner on pourrait commenter la ligne 56 du fichier <monitoring>/backend/routes/decorator.py

```
append_to_select=append,
```
à essayer...

on ne permet pas la suppression d'un sous-module en ligne de commande s'il y a des données associées existantes. (peut être que l'on peux ajouter une option --force ??)

**Comment by camillemonchicourt** [comment]
Tu peux modifier comme tu le souhaites les fichiers json de configuration d'un sous-module de suivi sans devoir tout réinstaller

**Comment by joelclems** [comment]
Il n'y a qu'a recharger la page du naviguateur pour voir les effets d'un changement de configuration du sous-module

**Comment by christianbieche** [comment]
C'est bon j'ai commenté le code pour ne fournir que 2 paramètres à la fonction, ensuite j'ai refait le front end  et c'est bon le module apparaît.
Le rechargement ne semble pas suffire ....

**Comment by christianbieche** [comment]
@camillemonchicourt par contre lors d'une nouvelle version de geonature que se passe-t-il ? La base est la même donc cela va mais il faut probablement réinstaller le sous-module et d'après ce que je viens de tester cela ne marche pas. Il détecte que le module existe d'après moi.

**Comment by camillemonchicourt** [comment]
Je ne comprends pas bien de quoi vous parlez mais non, quand on met à jour GeoNature, on ne doit pas réinstaller le module Monitoring, ni ses sous-modules.

**Comment by christianbieche** [comment]
Ben le module apparait dans les répertoire de geonature d'après ce que j'ai vu. Il me semble avoir lu que pour les modules il faut réinstaller après coup puisque l'on part d'une version git qui ne comprends pas ni le module ni le sous module.
Le script de mise à jour de geonature remet tout comme il faut alors très bien.

**Comment by camillemonchicourt** [comment]
Non les modules externes, comme Monitoring, ainsi que ses sous-modules, ne sont pas à mettre dans le dossier de GeoNature, mais dans un dossier à côté, au même niveau.

**Comment by maximetoma** [comment]
C'est vrai, j'ai fait la même erreur au début: il n'est pas spécifié (à part dans la commande d'installation d'un module externe) qu'il faut le mettre dans le dossier de l'utilisateur : http://docs.geonature.fr/installation-all.html#installation-d-un-module-geonature

**Comment by camillemonchicourt** [comment]
OK peut-être à repréciser dans la doc d'installation du module

**Comment by christianbieche** [comment]
@camillemonchicourt c'est ce que j'ai fait. N'empêche quand on installe, les json se retrouvent dans le répertoire geonature.
\home\geonatureadmin\geonature\external_modules\monitorings\config\monitoring\
avec le répertoire sentinelle et generic 
Du coup, j'ai mal à savoir ce qui est pris en compte réellement sinon à quooi sert ces répertoires.
Vraiment ce n'est pas clair du tout.

**Comment by joelclems** [comment]
C'est un lien symbolique

**Comment by christianbieche** [comment]
@joelclems Ah super.

**Comment by christianbieche** [comment]
Merci pour tous vos commentaires. 
Effectivement j'ai pu modifier les éléments que j'avais ajouté et rajouté par exemple une nouvelle donnée.
C'est pris en compte et si l'on remodifie la donnée elle apparaît bien en base dans le json.
Très bien.
