### ISSUE TITLE
Booléen - checkbox

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/gn_module_monitoring#82]
Bonjour,

Est-il possible d'ajouter un booléen comme nouvelle variable spécifique d'un module ? 
Et donc d'ajouter une checkbox comme widget ? Voir une liste de checkbox ?

Merci !

**Comment by joelclems** [comment]
A tester avec type : 'bool_radio'
```
    "b_synthese": {
      "type_widget": "bool_checkbox",
      "attribut_label": "Activer la synthèse ?",
      "definition": "Insertion automatique des nouvelles données dans la synthèse."
    },
```
peut être des effets de bord avec required ? et disabled ??

**Comment by RNF-SI** [comment]
Bonjour, merci ça marche parfaitement avec "bool_checkbox". 
Je n'ai pas testé le required ni disabled, mais je n'en ai pas l'intérêt dans mon cas.
