### ISSUE TITLE
Récupération d'une valeur de site dans visit

### ISSUE THREAD

**Issue by RNF-SI** [PnX-SI/gn_module_monitoring#84]
Bonjour,

Dans site.json je définie un champ "domaine" : 
```
"domaine": {
      "type_widget": "select",
      "required": true,
      "attribut_label": "Domaine",
      "values": ["Terrestre", "Maritime", "Mixte"]
    }
```
Comment puis-je récupérer sa valeur dans visit.json pour mettre un affichage conditionnel dessus ? Du style :

```
"etat_eau": {
      "type_widget": "select",
      "required": false,
      "attribut_label": "Etat de l'eau",
      "values": ["Normal", "Asséché", "Gelé"],
      "hidden": "({value}) => (site.domaine != 'Terrestre' && site.domaine != 'Mixte')"
    }
```

Merci !

**Comment by joelclems** [comment]
à tester.... je suis pas sur à 100%
```
"hidden": "({meta}) => (meta.parents.site.domaine != 'Terrestre' && meta.parents.site.domaine != 'Mixte')"
```

**Comment by RNF-SI** [comment]
Merci pour le retour. Mais ça ne marche pas, il ne s'affiche plus du tout, peu importe la valeur de "domaine".

**Comment by joelclems** [comment]
c'était `meta.parents.site.properties.domaine` et c'est caché quand hidden est vrai

```
"hidden": "({meta}) => ['Terrestre', 'Mixte'].includes(meta.parents.site.properties.domaine)"
```

**Comment by RNF-SI** [comment]
Merci c'est parfait ! Et comme je voulais effectivement que ça soit caché si domaine n'était pas égal à 'Terrestre' ou 'Mixte' (Ici c'est pour l'état de l'eau terrestre - à renommer probablement) j'ai remis ça :

`"hidden": "({meta}) =>  (meta.parents.site.properties.domaine != 'Terrestre' && meta.parents.site.properties.domaine != 'Mixte')"`
