### ISSUE TITLE
Bug d'installation apostrophe dans le nom du sous-module

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#86]
J'ai remarqué un bug d'installation pour un sous-module:

Quand le nom du module présente une apostrophe, la requête n'est plus reconnue côté postgres.
Je ne sais pas si ça peut être gérer autrement au cas-où ou si on doit juste le spécifier sur la doc ?

Le problème viendrait surtout que pour l'insertion dans la table t_sources

---

File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) ERREUR:  erreur de syntaxe sur ou près de « eau »
LINE 10: ...rique (sous-module: mesures multi-paramètres de l'eau [rnldn...
                                                              ^

[SQL:
    INSERT INTO gn_synthese.t_sources(
        name_source,
        desc_source,
        entity_source_pk_field,
        url_source
    )
    VALUES (
        'MONITORING_MULTIPARAM_EAU_RNLDN',
        'Données issues du module de suivi générique (sous-module: mesures multi-paramètres de l'eau [rnldn])',
        'gn_monitoring.vs_multiparam_eau_rnldn.entity_source_pk_value',
        '#/monitoring/object/multiparam_eau_rnldn/observation'
    );
        ]

**Comment by joelclems** [comment]
il n' y pas de pb pour la ligne dans `gn_commons.t_modules` ?

**Comment by maximetoma** [comment]
A mon avis non, ou alors c'est bizarre:
J'ai reessayé en mettant une double apostrophe du coup est voici ce que j'ai dans les deux tables:
- t_modules
`Mesures multi-paramètres de l''eau [RNLDN]`
- t_sources
`Données issues du module de suivi générique (sous-module: mesures multi-paramètres de l'eau [rnldn])`

D'un côté il garde la double apostrophe, de l'autre non

**Comment by joelclems** [comment]
dans le fichier `backend/command/cmd_install.py`, le module est inséré par modèle sqlalchemy et la source par commande sql
d'ou la différence de comportement

il faudrait insérer la source par commande sql et il n'aurait plus de pb

**Comment by maximetoma** [comment]
Ah okay effectivement, après je connais moins sqlalchemy... Mais je vois merci :)
