### ISSUE TITLE
Data - Ménage ?

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_monitoring#9]
Il y a des fichiers ou une partie de leurs contenus à supprimer dans le dossier /data ?
- cheveches.sql
- dans patch_data au moins la création de ``gn_commons.cor_module_dataset`` et la nomenclature 'POINT_ECOUTE_CHEVECHE'

**Comment by joelclems** [comment]
fait dans 
4cf8dc2
