### ISSUE TITLE
[Bug] - installation sous-module test

### ISSUE THREAD

**Issue by lepontois** [PnX-SI/gn_module_monitoring#91]
Salut !

Je passe en phase de test du module monitoring afin d'évaluer s'il peut répondre à notre besoin de suivi dans le cadre du programme "flore".

Pour info, je suis sur la V2.6.2 de GeoNature

J'ai donc réalisé une installation en local du module monitoring (en git clone) sans trop de difficulté.
Proposition : pour faciliter l'installation, on pourrait peut-être indiqué dans la doc le chemin type (ex : pour bien faire, <path_to_module_monitoring> devrait correspondre à ./geontaure/contrib/gn_module_monitoring). Perso, j'ai du le déplacer après coup pensant que l'installation du module s'en chargerais lui même... (et reconstruire le lien symbolique dans ./geonature/external_module/)
Bref, du détail.

Par contre, j'ai voulu installer le sous-module test afin de pouvoir le décortiquer avant de réaliser mon propre sous-module. Malheureusement, lorsque je fais "flask monitorings install contrib/gn_module_monitoring/contrib/test/" il me retourne "config directory for module test does not exist".
L'interface graphique du module tourne alors en boucle -> erreur 500 sur http://10.0.0.239/geonature/api/monitorings/config car No such file or directory: '/home/geonature/geonature/external_modules/monitorings/backend/config/../../config/monitoring/test'

**Comment by joelclems** [comment]
L'emplacement des modules n'a pas vraiment d'importance au final, sauf en dev ou on ne veux pas qu'ils interfère avec le git de geonature.

ça doit êtrele deuxième lien `/home/geonature/geonature/external_modules/monitorings/config/monitoring` devrait être absolu

tu peux soit recréer le lien soit desinstaller reinstaller le sous module avec les commandes

```
flask monitorings remove test
flask monitorings install /home/geonature/geonature/contrib/gn_module_monitoring/contrib/test

```
