### ISSUE TITLE
Problème avec id_nomenclature_type_site au niveau d'un site

### ISSUE THREAD

**Issue by lepontois** [PnX-SI/gn_module_monitoring#94]
Bonjour,

Je rencontre un problème lors de l'enregistrement d'un site:
- j'ai ajouté une nomenclature de type TYPE_SITE ayant pour cd_nomenclature "SUIVI_FLORE" dont l'id_nomenclature = 586
- J'ai configuré mon site.json avec : 
```
{
  "label":"Station",
  "display_properties": [
    "base_site_name",
    "base_site_code",
    "base_site_description",
    "id_inventor",
    "first_use_date",
    "last_visit",
    "nb_visits"
  ],
  "geometry_type": "Point",
  "specific": {
    "active": {
      "type_widget": "radio",
      "attribut_label": "Station active",
      "values": ["Oui", "Non"]
    },
    "id_nomenclature_type_site": {
      "type_widget": "text",
      "attribut_label": "Type site",
      "type_util": "nomenclature",
      "value": {
        "code_nomenclature_type": "TYPE_SITE",
        "cd_nomenclature": "SUIVI_FLORE"
      },
      "hidden": true
    }
  }
}
```

Dans  la console de mon navigateur, je vois bien l'id_nomenclature_type_site passer avec la valeur 586.
Et pourtant j'ai une erreur 500 en retour avec le message suivant dans les logs 
`
MONITORING: create_or_update monitoringobject androsace_herissee, site, None : (psycopg2.errors.NotNullViolation) null value in column "id_nomenclature_type_site" violates not-null constraint
DETAIL:  Failing row contains (4, 10, 10, null, TEST_01, TEST_01, TEST_01, 2021-05-12, 0101000020E61000008CDAFD2AC077B33F5F7F129F3B9D4540, 01010000206A080000847077165E381C41B6D667F9B3CE5741, null, null, 4575ddef-b75d-401a-8f87-6f1dd3a17bbd, 2021-05-12 14:05:23.85205, null).
`

Merci par avance.

**Comment by joelclems** [comment]
J'ai verifié et ça marche avec (si on met "cd_nomenclature": "2") est ce que tu n'a pas une coquille quelque part sur la nomenclature TYPE_SITE, SUIVI_FLORE ?

tu peux mettre hidden à false le temps vérifier que tu as bien l'id_nomenclature voulu

**Comment by lepontois** [comment]
Salut joël,

Je te partage la ligne en base dans t_nomenclatures concernant mon type de site "SUIVI_FLORE" :
```
id_nomenclature = 586
id_type = 116
cd_nomenclature = SUIVI_FLORE
mnemonique = Suivi flore
label_default = Suivi flore
definition_default = Site de type suivi floristique
label_fr = Suivi flore
definition_fr = Site de type suivi floristique
label_en = NULL
definition_en = NULL
label_es = NULL
definition_es = NULL
label_de = NULL
definition_de = NULL
label_it = NULL
definition_it = NULL
source = GEONATURE
statut = Non validé
id_broader = 0
hierarchy = NULL
meta_create_date = 2021-05-12 13:16:20.046157
meta_update_date = 2021-05-17 07:45:49.0267
active = True
```

J'ai passé à false le paramètre hidden et le champ m'affiche bien 586 comme valeur.
Dans la console, je vois bien que cet id est envoyé en XHR mais il se perd quelque part mais je n'arrive pas à comprendre ou...

J'ai également testé en passant le "cd_nomenclature" à "2" mais j'ai la même erreur.

**Comment by lepontois** [comment]
Solution trouvé !

Parce que j'aime bien me mettre des battons dans les roues, j'avais supprimé la partie : 
```
"id_nomenclature_type_site": {
      "type_widget": "datalist",
      "attribut_label": "Type site",
      "api": "nomenclatures/nomenclature/TYPE_SITE",
      "application": "GeoNature",
      "keyValue": "id_nomenclature",
      "keyLabel": "label_fr",
      "data_path": "values",
      "type_util": "nomenclature",
      "required": true
    },
```
dans external_modules/monitorings/config/monitoring/generic/site.json
Estimant que je n'aurais jamais besoin d'une liste déroulante de type de suite dans mes suivi, je me suis cru malin de l'enlever.

Du coup, je suis désolé pour le dérangement !
Mais en même temps, ça m'a poussé à porter un regard sur le backend...

En tout cas, merci Joël pour ton suivi toujours très actif !
