### ISSUE TITLE
Définition de sous-module : l'enchaînement de la saisie ne fonctionne pas

### ISSUE THREAD

**Issue by christianbieche** [PnX-SI/gn_module_monitoring#95]
Bonjour,
Suite aux dernières ajustements (voir Définition de sous-module : impossible de valider la saisie #93) puisque le module est presque au point, j'ai tenté de réaliser l'enchaînement de saisie. Fonctionnalité très intéressante puisqu'elle permet visiblement d'enchaîner des saisies pratiquement identiques.
Malheureusement cela ne semble pas fonctionner. J'ai essayé sur mon module en cours de validation et sur un module d'essai beaucoup plus simple et impossible d'enchaîner les saisies. 
Une première saisie est validée, mais la suivante reste en l'air, cela mouline indéfiniment comme lors de l'absence du cd_nom en saisie.
J'ai récupéré des erreurs qui semble montrer qu'un nouvel id n'est pas donné pour la nouvelle observation provoquant un plantage.
Ci-dessous les logs récupérés : 
Trace dans la console de l'explorateur au moment de la validation
==========================================================================================================================

polyfills.0a5c396d95c9f43a3a61.js:1 PATCH https://cistude-geonat.xyz/geonature/api/monitorings/object/sentinelle_odonates/observation/32? 500 (INTERNAL SERVER ERROR)
m @ polyfills.0a5c396d95c9f43a3a61.js:1

PAYLOAD lors de la requête dans la partie réseau de la console de l'explorateur
==========================================================================================================================
{
  "id_observation": null,
  "id_base_visit": 18,
  "cd_nom": 65076,
  "comments": null,
  "medias": [],
  "grpEsp": 638,
  "nbreObs": 10,
  "dateDeb": "2021-5-26",
  "dateFin": "2021-5-26",
  "heurDeb": "10",
  "heurFin": "10",
  "temperatur": 10,
  "humidite": 50,
  "ventBeaufo": 10,
  "couvNuage": "0",
  "pluie": "non",
  "precipitations": null,
  "luminosite": null,
  "typeAcquisition": "Suivis-STELI imagos",
  "procObserv": "A vue",
  "sexe": null,
  "comportmt": null,
  "denbrType": null,
  "denbr": null
}

trace dans les logs geonature
=========================================================================================================================
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/decorators.py", line 107, in __check_cruved_scope_monitoring
    return fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.7/site-packages/utils_flask_sqla/response.py", line 23, in _json_resp
    res = fn(*args, **kwargs)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/monitoring.py", line 106, in update_object_api
    return create_or_update_object_api(module_code, object_type, id)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/routes/monitoring.py", line 92, in create_or_update_object_api
    .create_or_update(post_data)
  File "/home/geonatureadmin/geonature/external_modules/monitorings/backend/monitoring/repositories.py", line 136, in create_or_update
    .format(self, str(e))
geonature.utils.errors.GeoNatureError: MONITORING: create_or_update monitoringobject sentinelle_odonates, observation, 32 : (psycopg2.errors.NotNullViolation) ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « id_observation »
DETAIL:  La ligne en échec contient (null, 18, 65076, null, da2ea658-2039-44b3-95be-da762586bda5)

[SQL: UPDATE gn_monitoring.t_observations SET id_observation=%(id_observation)s WHERE gn_monitoring.t_observations.id_observation = %(gn_monitoring_t_observations_id_observation)s]
[parameters: {'id_observation': None, 'gn_monitoring_t_observations_id_observation': 32}]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
[2021-05-26 15:37:47 +0200] [6507] [ERROR] 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by joelclems** [comment]
Sur quelle version du module est tu ? Je crois que c'est corrigé dans develop?

**Comment by christianbieche** [comment]
toujours la même version 0.2.3 pour le module monitoring

**Comment by christianbieche** [comment]
Bonjour,
Pas  de réponses sur le sujet.
Est ce quelqu'un à réussit à faire fonctionner l'enchaînement des saisies pour les sous-modules ?
si oui quel est le problème dans mon cas ?
Christian Bièche
Cistude Nature

**Comment by joelclems** [comment]
Normalement les enchainements marchent sur la branche develop, un release est à venir

**Comment by christianbieche** [comment]
D'accord, merci Joel,  j'attends donc la release.
Est ce que tu as une date prévue de cette version et quels sont les prérequis en terme de version de geonature ?

**Comment by maximetoma** [comment]
Le problème semble avoir été corrigé sur la version https://github.com/PnX-SI/gn_module_monitoring/releases/tag/0.2.4 mais je ne peux toujours pas enchainer les saisies :(

**Comment by joelclems** [comment]
Bonjour maxime, est ce que tu peux donner plus de précisions / ou la config de ton module
de mon côté, je n'ai pas de soucis pour enchainer la saisie des visites sur le module de test

**Comment by maximetoma** [comment]
Bonjour, en fait c'est surtout que je ne peux pas valider la deuxième saisie, le bouton ne s'active pas. Mais ça ne me fais pas ça sur tous les sous-modules
Quels fichiers t'intéresserai ?

**Comment by joelclems** [comment]
pour tester il me faudrait le repertoire de config du module ou cela ne marche pas, et sur quel objet cela ne marche pas (site, visite ?)

**Comment by maximetoma** [comment]
Oui pardon j'ai oublié de préciser !! C'est pour les observations
Voici le dossier config : [config.zip](https://github.com/PnX-SI/gn_module_monitoring/files/6860519/config.zip)
Et aussi l'autre répertoire config du répertoire backend au cas ou : [config_backend.zip](https://github.com/PnX-SI/gn_module_monitoring/files/6860518/config_backend.zip)

**Comment by joelclems** [comment]
je n'ai que le dossier monitoring/generic dans config.zip
il me faudrait la config du sous-module ou cela ne marche pas,
est ce pour ce sous module que le cd_nom est caché avec une valeur par défaut ?

**Comment by maximetoma** [comment]
Ah oui ça n'a pas pris du coup les liens perma...
Voici le module en question: [comptage_rnmo.zip](https://github.com/PnX-SI/gn_module_monitoring/files/6860570/comptage_rnmo.zip)
Non pour le cd_nom

**Comment by joelclems** [comment]
un problème avec la saisie enchainée, est qu'on ne garde pas les valeurs par default sur la deuxième saisie
le champs id_nomenclature_confidential qui est caché et obligatoire prend la valeur nulle et le bouton validé est toujours grisé

une solution est d'ajouter 

```
"keep": [
    "id_nomenclature_confidential"
]
```

on peut idéalement ici ajouter tous les champs de type nomenclature et tout les champs qui sont supposés ne pas trop bouger d'une saisie à l'autre
les valeurs de champs présents dans keep sont persitantes d'une saisie à l'autre

l'idéal serait de pouvoir :
  - garder la valeur par défaut des champs d'une saisie à l'autre
  - afficher les champs requis manquant dans le formulaire (plus généralement les message d'erreur de saisie) en particulier pou rpouvoir déceler les champs caché non valides

**Comment by maximetoma** [comment]
Oui :)
Après est-ce que les autres champs de nomenclatures peuvent être mis dans `keep` et est-ce que il seront toujours modifiables par la suite ?

**Comment by joelclems** [comment]
oui on peut toujours les modifier

**Comment by maximetoma** [comment]
ça marche, merci beaucoup pour le beau coup d'oeil ! :)

**Comment by joelclems** [comment]
j'était déjà tombé sur ce genre de problème
l'idéal serait d'avoir un formulaire plus parlant sur les erreurs

**Comment by christianbieche** [comment]
En version 0.2.6, Effectivement, le problème d'enchaînement de la saisie est résolu mais il faut obligatoirement utiliser le paramètre keep pour conserver les données. Ce que je n'avais pas compris parce que je pensais que cela concerner uniquement les champs confidentiels et cachés.

Du coup, où peut-on trouver les fonctionnalités ou corrections  ajoutés aux versions et la façon dont cela fonctionne ? 
Y-a-t-il d'autres fonctionnalités cachées ??? Les release mentionne parfois des informations pas visiblement pas tout ce qui est nécessaire à connaître.
