### ISSUE TITLE
Arrangement - Ce petit "i"

### ISSUE THREAD

**Issue by Idaline** [PnX-SI/gn_module_monitoring#97]
Bonjour !

L'équipe rencontre des difficultés pour s'approprier les modules, particulièrement à cause de ce petit "i". Quand on arrive sur le sous-module c'est l'action "ajouter un (groupe de) site" qui saute aux yeux. C'est contre-intuitif de devoir cliquer sur ce petit "i" qui nous amène à "ajouter une visite".

Est-il possible de re-travailler ce déroulement svp ? 

De notre côté le plus pertinent serait d'avoir sur une page "ajouter une visite au site:" -> Sélection du site et groupe de site (sur la même page pour éviter les clics). Puis une nouvelle page pour rentrer les infos relatives à la visite ou l'observation.

**Comment by camillemonchicourt** [comment]
En fait la logique est un peu différente.
Le "i" (pour "informations") permet d'accéder à la fiche détail d'un site.
Et depuis la fiche info d'un site, on peut y ajouter une visite.
Depuis la liste des sites, on pourrait ajouter un bouton "+" pour directement accéder à l'ajout d'une visite sur ce site, sans passer par l'intermédiaire de sa fiche info, mais c'est pas forcément très conseillé d'ajouter trop d'action sur une liste, d'autant plus si celles-ci sont de niveau de différent.
Mais pourquoi pas, faire cela pour permettre d'accéder aux infos du site, ou directement au formulaire d'ajout d'une visite depuis la liste des sites.

Par contre, je n'ai pas sous la main de module Monitoring avec des groupes de sites, donc je vois pas ce que ça donne quand on a des groupes de sites.
Les protocoles avec des groupes de sites sont un cas particulier, qui n'est pas toujours le cas.

Je ne comprends pas la proposition d'ajouter une "page" "ajouter une visite au site". Et ensuite sélectionner le site et le groupe de site. Je ne vois pas bien ce fonctionnement ?

**Comment by Idaline** [comment]
Pour les groupes de sites, cela rajoute une étape de clic (une page en plus) : groupe de site > site > visite.

Oui je comprends bien. A voir ce qui est possible ! Ma proposition était seulement d'avoir un bouton ou symbole indiquant clairement "ajouter une visite" au niveau de la page où sont listés les sites.

**Comment by camillemonchicourt** [comment]
OK, alors là c'est plus clair pour moi.
Dans ce cas, oui pourquoi pas ajouter un bouton d'action + (Ajouter une visite au site) au niveau de la liste des sites, comme évoqué ci-dessus.
Et peut-être que pour clarifier le bouton d'accès à la fiche de détail d'un groupe de site, d'un site ou d'une visite, on pour remplacer l'icone "i" du bouton, par un œil ou du genre, plus intuitif.

**Comment by joelclems** [comment]
J'ai changé le petit `i` par une icône oeil et j'ai ajouter un bouton `+` juste à côté pour ajouter un petit enfant ?? si l'objet enfant peut en posséder.

Par exemple 
- sur la page module, dans la liste de sites (enfant) on propose d'ajouter une visite pour le site correspondant à la ligne 
- sur la page site, dans la liste des visites on propose d'ajouter une observation.
