### ISSUE TITLE
[GeoNature 2.7.2] Erreur 500: chargement de "config"

### ISSUE THREAD

**Issue by maximetoma** [PnX-SI/gn_module_monitoring#99]
Bonjour,

J'ai récent mis à jour notre GeoNature en 2.7.2, hors le module monitoring ne se charge plus...
En vérifiant, je tombe sur une erreur lié au fichier/dossier config ?

![image](https://user-images.githubusercontent.com/66769358/125270251-c38de800-e309-11eb-80f4-d3c2e7cfe29b.png)

Avez-vous une idée de ce qui coince de mon côté ?
Merci beaucoup d'avance,
Maxime

**Comment by bouttier** [comment]
Bonjour,
Afin de pouvoir mieux vous aider, pouvez-vous partager les logs du serveur ? Ils se trouvent dans `geonature/var/log/gn_errors.log`.

**Comment by maximetoma** [comment]
Oui, voici : [gn_errors.log](https://github.com/PnX-SI/gn_module_monitoring/files/6800627/gn_errors.log)

**Comment by maximetoma** [comment]
Okay merci Elie, j'ai regardé dans ce fichier et effectivement je me suis aperçu que dans le dossier `config/monitoring/generic` j'ai eu une création de lien symboliques des dossiers `sites_group_aside`, `sites_group_top`, `test` et `contrib`
A moins que ce soit normal mais dans le code source, il n'y a pourtant pas tout ça...

EDIT: En fait j'ai également eu une création bizarre de liens symbolique à l'intérieur du sous-module `test`, surement fausse manip lors de la MAJ...
![image](https://user-images.githubusercontent.com/66769358/125283230-7feeaa80-e318-11eb-847e-fc3e44ee816e.png)

Mais le problème est résolu en supprimant tout ça ! Merci beaucoup Elie pour l'info du fichier de log !

**Comment by camillemonchicourt** [comment]
OK à voir si cela n'est pas une évolution dans la MAJ des modules fait avec la 2.7.x de GeoNature ?
